.github/containerscan/allowedlist.yaml
.github/workflows/actions.yml
Dockerfile

uncomment actions to enable tests and scans
|https://github.com/dell/csm/issues/243 |

try fix actions

---

scripts/common.bash
scripts/install.sh
scripts/install_olm.sh
scripts/uninstall.sh
scripts/uninstall_olm.sh
scripts/verify.sh

Enhancement of instal_olm scripts in CSM operator.
|https://github.com/dell/csm/issues/254 |
installation without olm:
Uninstall without olm: 
Installation with olm: 
Uninstallation with olm:
ll :

KRV-3610 : Enhancement of instal_olm scripts in CSM operator

---

scripts/install.sh
scripts/install_olm.sh
scripts/uninstall_olm.sh

Enhance the scripts to pick the namespace from the manifests
| https://github.com/dell/csm/issues/254 |
** Installation with olm : ** 
** Installation of olm without namespace available on system : ** 
** Uninstall with olm : **

KRV-4562 : Enhance the scripts to pick the namespace from the manifests

---

.github/workflows/actions.yml
Makefile
core/semver/semver.go

Semver implementation
| https://github.com/dell/csm/issues/254  |
installation tested and verified in both k8s and openshift environment.

KRV-4021 : Semver implementation

---

controllers/csm_controller.go
controllers/csm_controller_test.go
pkg/drivers/commonconfig.go

Adding owner-reference support to csm-operator
|https://github.com/dell/csm/issues/255 |

Adding owner reference

---

tests/e2e/go.mod
tests/e2e/go.sum

PR to fix dependency vulnurability

fix dependency bot

---

.github/CODEOWNERS
Dockerfile
README.md
bundle/manifests/dell-csm-operator.clusterserviceversion.yaml
config/manager/manager.yaml
config/samples/storage_v1_csm_powerscale.yaml
deploy/operator.yaml
main.go

This PR:
- Update UBI image
- Update manifests
- Update Readme for support matrix
- Update CodeOwners file
| https://github.com/dell/csm/issues/243 |

Update UBI image, manifests and Readme

---

.github/containerscan/allowedlist.yaml
.github/workflows/actions.yml
samples/storage_csm_powerscale_v220.yaml
samples/storage_csm_powerscale_v230.yaml

Adding node-toleration support for powerscale
| |

Node toleration

---

.github/workflows/actions.yml
Dockerfile
Makefile
bundle/manifests/dell-csm-operator.clusterserviceversion.yaml
config/install/kustomization.yaml
config/manager/kustomization.yaml
config/manifests/bases/dell-csm-operator.clusterserviceversion.yaml
deploy/olm/operator_community.yaml
deploy/operator.yaml
docker.mk

Bump up CSM Operator version to v0.3.0
**Validation Screenshot**

Bump up operator version to 0.3.0

---

README.md
bundle/manifests/dell-csm-operator.clusterserviceversion.yaml
config/manifests/bases/dell-csm-operator.clusterserviceversion.yaml
scripts/install.sh
scripts/install_olm.sh
tests/README.md

This PR modifies the name, short description and detailed description in CSV of CSM Operator so that the same will be reflected in OperatorHub.io
Validation screenshots
**Before fix - Name and short description**
**After fix - Name and short description**
**Before fix - Detailed description**
**After fix - Detailed description**

Update Operator name, descriptions in CSV

---

.github/containerscan/allowedlist.yaml
Dockerfile

Update UBI image to 8.6-902
|https://github.com/dell/csm/issues/350|
Ran sanity with the changes
[csm-operator-sanity-k8s-1.24.log](https://github.com/dell/csm-operator/files/9477912/csm-operator-sanity-k8s-1.24.log)
Ran make recipes

UBI image update

---

operatorconfig/driverconfig/common/default.yaml
operatorconfig/driverconfig/common/k8s-1.21-values.yaml
operatorconfig/driverconfig/common/k8s-1.22-values.yaml
operatorconfig/driverconfig/common/k8s-1.23-values.yaml
operatorconfig/driverconfig/common/k8s-1.24-values.yaml

https://osj-sio-03-prd.cec.lab.emc.com/job/CSM-Operator/job/dell-csm-operator-sanity-k8s-v124/4/
https://osj-sio-03-prd.cec.lab.emc.com/job/CSM-Operator/job/dell-csm-operator-sanity-ocp-kv410/8/

Update all sidecars to latest versions

---

samples/storage_csm_powerscale_v240.yaml

Adding nodeSelector and tolerations to storage_csm_powerscale_v240.yaml

Add nodeselector and tolerations to storage_csm_powerscale_v240.yaml

---

.github/containerscan/allowedlist.yaml
Dockerfile
Makefile
bundle/manifests/dell-csm-operator.clusterserviceversion.yaml
config/install/kustomization.yaml
config/manager/kustomization.yaml
config/manifests/bases/dell-csm-operator.clusterserviceversion.yaml
deploy/olm/operator_community.yaml
deploy/operator.yaml
docker.mk

Bumps up the version from 0.3.0 to 1.0.0
| https://github.com/dell/csm/issues/491 |

Bump up version to 1.0.0

---

.github/workflows/actions.yml
Dockerfile
go.mod
tests/e2e/go.mod

Update GO version
| https://github.com/dell/csm/issues/491 |
https://osj-sio-03-prd.cec.lab.emc.com/job/CSM-Operator/job/csm-operator-build/206/

Update GO version

---

controllers/csm_controller.go
controllers/csm_controller_test.go
operatorconfig/moduleconfig/observability/v1.2.0/karavi-metrics-powerflex.yaml
operatorconfig/moduleconfig/observability/v1.2.0/karavi-otel-collector.yaml
operatorconfig/moduleconfig/observability/v1.2.0/karavi-topology.yaml
operatorconfig/moduleconfig/observability/v1.3.0/karavi-metrics-powerflex.yaml
pkg/modules/observability.go
pkg/modules/observability_test.go
pkg/modules/testdata/cr_powerflex_observability.yaml
samples/storage_csm_powerflex_v230.yaml
samples/storage_csm_powerflex_v240.yaml
tests/e2e/steps/step_common.go
tests/e2e/testfiles/storage_csm_powerflex_observability.yaml
tests/e2e/testfiles/values.yaml

* Support topology component
* Support powerflex metrics component for both 1.3.0 & 1.2.0
* Support Otel collector
* Add related UT
* Add related e2e
Support PowerFlex Observability Module
|https://github.com/dell/csm/issues/488|
```
controllers# go test ./... -coverprofile c.out
ok      github.com/dell/csm-operator/controllers        1.135s  coverage: 88.5% of statements
modules# go test ./... -coverprofile c.out
ok      github.com/dell/csm-operator/pkg/modules        0.275s  coverage: 87.2% of statements
```
```
STEP: Getting test environment variables
STEP: Reading values file …
```

Support PowerFlex Observability Module

---

Dockerfile

Updating the UBI image digest
| |

Ubi update

---

operatorconfig/driverconfig/powerflex/v2.3.0/controller.yaml
operatorconfig/driverconfig/powerflex/v2.3.0/node.yaml
operatorconfig/driverconfig/powerflex/v2.4.0/controller.yaml
operatorconfig/driverconfig/powerflex/v2.4.0/node.yaml
samples/storage_csm_powerflex_v230.yaml
samples/storage_csm_powerflex_v240.yaml

Mount in certs from secret for connecting to pflex arrays 
| https://github.com/dell/csm/issues/477 |

Add certs for pflex

---

tests/e2e/testfiles/storage_csm_powerflex.yaml
tests/e2e/testfiles/storage_csm_powerflex_auth.yaml
tests/e2e/testfiles/storage_csm_powerflex_observability.yaml

Add missing env variable to testfiles 
| https://github.com/dell/csm/issues/477 |

Add missing var to testfiles 

---

Dockerfile

Updated the UBI image
|  ttps://github.com/dell/csm/issues/491 |

Updated the UBI image

---

operatorconfig/driverconfig/common/default.yaml
operatorconfig/driverconfig/common/k8s-1.21-values.yaml
operatorconfig/driverconfig/common/k8s-1.23-values.yaml
operatorconfig/driverconfig/common/k8s-1.24-values.yaml
operatorconfig/driverconfig/common/k8s-1.25-values.yaml

Updated sidecar
| https://github.com/dell/csm/issues/491 |

Updated sidecar

---

tests/README.md
tests/e2e/testfiles/values.yaml

Authorization e2e corrected statement in values file
| #https://github.com/dell/csm/issues/511  |

Authorization e2e pre requisite step added in doc

---

operatorconfig/moduleconfig/observability/v1.4.0/karavi-metrics-powerflex.yaml
operatorconfig/moduleconfig/observability/v1.4.0/karavi-metrics-powerscale.yaml
operatorconfig/moduleconfig/observability/v1.4.0/karavi-otel-collector.yaml
operatorconfig/moduleconfig/observability/v1.4.0/karavi-topology.yaml
samples/storage_csm_powerflex_v250.yaml

update manifest files for Observability 1.4
| https://github.com/dell/csm/issues/491|

update manifest files for Observability 1.4

---

operatorconfig/driverconfig/common/default.yaml
operatorconfig/driverconfig/common/k8s-1.21-values.yaml
operatorconfig/driverconfig/common/k8s-1.22-values.yaml
operatorconfig/driverconfig/common/k8s-1.23-values.yaml
operatorconfig/driverconfig/common/k8s-1.24-values.yaml
operatorconfig/driverconfig/powerflex/v2.3.0/node.yaml
operatorconfig/driverconfig/powerflex/v2.4.0/node.yaml
operatorconfig/driverconfig/powerflex/v2.5.0/node.yaml
pkg/modules/testdata/cr_powerflex_observability.yaml
samples/storage_csm_powerflex_v230.yaml
samples/storage_csm_powerflex_v240.yaml
samples/storage_csm_powerflex_v250.yaml
tests/config/driverconfig/powerflex/v2.3.0/node.yaml
tests/e2e/testfiles/storage_csm_powerflex.yaml
tests/e2e/testfiles/storage_csm_powerflex_auth.yaml
tests/e2e/testfiles/storage_csm_powerflex_observability.yaml
tests/e2e/testfiles/storage_csm_powerflex_observability_auth.yaml

Bumping the sdc image for csi-powerflex
| |

updating sdc image

---

bundle/manifests/dell-csm-operator.clusterserviceversion.yaml
config/samples/storage_v1_csm_powerflex.yaml

SDC version updates to manifests
| |

SDC version updates to manifests

---

api/v1/types.go
config/crd/bases/storage.dell.com_containerstoragemodules.yaml
config/samples/storage_v1_csm_powerstore.yaml
deploy/crds/storage.dell.com_containerstoragemodules.yaml
operatorconfig/driverconfig/powerstore/v2.4.0/controller.yaml
operatorconfig/driverconfig/powerstore/v2.5.0/controller.yaml
operatorconfig/driverconfig/powerstore/v2.6.0/controller.yaml
operatorconfig/driverconfig/powerstore/v2.6.0/csidriver.yaml
operatorconfig/driverconfig/powerstore/v2.6.0/driver-config-params.yaml
operatorconfig/driverconfig/powerstore/v2.6.0/node.yaml
operatorconfig/driverconfig/powerstore/v2.6.0/upgrade-path.yaml
pkg/drivers/common_test.go
pkg/drivers/commonconfig.go
pkg/drivers/powerstore.go
samples/storage_csm_powerstore_v250.yaml
samples/storage_csm_powerstore_v260.yaml
tests/config/driverconfig/powerstore/v2.6.0/bad.yaml
tests/config/driverconfig/powerstore/v2.6.0/controller.yaml
tests/config/driverconfig/powerstore/v2.6.0/csidriver.yaml
tests/config/driverconfig/powerstore/v2.6.0/driver-config-params.yaml
tests/config/driverconfig/powerstore/v2.6.0/node.yaml
tests/config/driverconfig/powerstore/v2.6.0/upgrade-path.yaml
tests/e2e/testfiles/storage_csm_powerstore.yaml

- Added v2.6 CSI Powerstore driver support
- Changes to update storage capacity value
| https://github.com/dell/csm/issues/613 |
Sanity test:

Add Powerstore v2.6 samples

---

Dockerfile
bundle/manifests/dell-csm-operator.clusterserviceversion.yaml
bundle/manifests/storage.dell.com_containerstoragemodules.yaml
config/manifests/bases/dell-csm-operator.clusterserviceversion.yaml

https://osj-sio-03-prd.cec.lab.emc.com/job/CSM-Operator/job/dell-csm-operator-sanity-k8s-v125/40/console

Update UBI image, Update storage capacity permissions for Powerstore in CSV

---

samples/storage_csm_powerflex_v260.yaml
samples/storage_csm_powerscale_v260.yaml

Authorization sidecar updates for supported drivers.
| https://github.com/dell/csm/issues/583|

Update CSM Authorization sidecar

---

.github/containerscan/allowedlist.yaml
Makefile
bundle/manifests/dell-csm-operator.clusterserviceversion.yaml
config/manifests/bases/dell-csm-operator.clusterserviceversion.yaml
config/samples/storage_v1_csm_powerflex.yaml
config/samples/storage_v1_csm_powerscale.yaml
config/samples/storage_v1_csm_powerstore.yaml
operatorconfig/moduleconfig/common/version-values.yaml

**#** Description
- This PR has final updates to manifests
- Updated allowed list yaml with the latest found vulnerability details
Ran Sanity jobs and they are working as expected

Final updates to manifests

---

.github/containerscan/allowedlist.yaml
bundle/manifests/dell-csm-operator.clusterserviceversion.yaml
config/samples/storage_v1_csm_powerflex.yaml

This PR has final updates to manifests
https://osj-sio-03-prd.cec.lab.emc.com/job/CSM-Operator/job/dell-csm-operator-sanity-k8s-v126/51/console

Updates to manifests after changes in PowerFlex samples

---

operatorconfig/moduleconfig/application-mobility/v0.3.0/app-mobility-controller-manager-metrics-service.yaml
operatorconfig/moduleconfig/application-mobility/v0.3.0/app-mobility-controller-manager.yaml
operatorconfig/moduleconfig/application-mobility/v0.3.0/app-mobility-webhook-service.yaml
operatorconfig/moduleconfig/application-mobility/v0.3.0/appMobilitycrds.all.yaml
operatorconfig/moduleconfig/application-mobility/v0.3.0/certificate.yaml
samples/application-mobility/config.yaml

Added YAMLs for supporting Application Mobility
| |
This will be tested pending further development in other stories

App mobility add yamls

---

operatorconfig/moduleconfig/authorization/v1.7.0/ingress.yaml
pkg/modules/authorization.go
pkg/modules/testdata/cr_auth_proxy.yaml
samples/authorization/certificate.yaml
samples/authorization/csm_authorization_proxy_server.yaml
tests/e2e/steps/steps_def.go
tests/e2e/testfiles/csm_authorization_proxy_server.yaml

Removes Authorization role-service ingress.
|https://github.com/dell/csm/issues/725|
Manual tests verifying that operator is able to deploy services without ingress exposure and karavictl role commands work through the proxy-server.

Feature-725: Remove role-service ingress

---

bundle/manifests/dell-csm-operator.clusterserviceversion.yaml
config/manifests/bases/dell-csm-operator.clusterserviceversion.yaml

Add OLM support for Unity driver on CSM Operator
|https://github.com/dell/csm/issues/756 |
Tested creating and deleting CR using the mage generated from this branch and results look good

Adding OLM support for Unity driver on CSM Operator

---

controllers/csm_controller_test.go
pkg/modules/resiliency_test.go
pkg/modules/testdata/cr_powerstore_resiliency.yaml

Unit tests for Resiliency
|https://github.com/dell/csm/issues/739|
To run controller test I ran: make controller-unit-test
To run resiliency test I ran: go clean -cache && go test -v -coverprofile c.out ./... -run ^TestResiliency
Coverage for resiliency_test.go : 95.2 %
Coverage for csm_controller_test.go : 88.4 %

Resiliency-unit-test

---

README.md
operatorconfig/moduleconfig/resiliency/v1.6.0/container-powerstore-controller.yaml
operatorconfig/moduleconfig/resiliency/v1.6.0/container-powerstore-node.yaml
pkg/modules/resiliency.go
pkg/utils/utils.go
samples/storage_csm_powerstore_v270.yaml

Multi components for resiliency module to set right args to podmon sidecar.
|https://github.com/dell/csm/issues/739|

Multi component for resiliency module

---

pkg/modules/resiliency.go

Podmon container reordering in controller and node pods
|https://github.com/dell/csm/issues/739|

Podmon container reordering

---

bundle/manifests/dell-csm-operator.clusterserviceversion.yaml
config/samples/storage_v1_csm_powerflex.yaml
pkg/utils/status.go
samples/storage_csm_powerflex_v250.yaml
samples/storage_csm_powerflex_v260.yaml
samples/storage_csm_powerflex_v270.yaml

Updated sample files and name/namespace references to match new docs
|https://github.com/dell/csm/issues/810 |

Sample update

---

README.md
bundle/metadata/annotations.yaml

This PR 
- Updates the install steps of Operator in Readme.
- Updates the Openshift versions in annotations

Update Readme.Update Openshift versions in annotations

---

operatorconfig/driverconfig/common/default.yaml
operatorconfig/driverconfig/common/k8s-1.21-values.yaml
operatorconfig/driverconfig/common/k8s-1.24-values.yaml
operatorconfig/driverconfig/common/k8s-1.25-values.yaml
operatorconfig/driverconfig/common/k8s-1.26-values.yaml
operatorconfig/driverconfig/common/k8s-1.27-values.yaml
operatorconfig/driverconfig/powerscale/v2.7.0/controller.yaml

Metadata sidecar version bump
|https://github.com/dell/csm/issues/843|

metadata sidecar version bump

---

operatorconfig/driverconfig/powermax/v2.6.0/node.yaml
operatorconfig/driverconfig/powermax/v2.7.0/node.yaml

|https://github.com/dell/csm/issues/846|

Add missing env for vsphere hostname

---

tests/e2e/run-e2e-test.sh
tests/e2e/steps/steps_def.go
tests/e2e/steps/steps_runner.go
tests/e2e/testfiles/storage_csm_powerflex_observability_auth.yaml
tests/e2e/testfiles/storage_csm_powerscale_observability_auth.yaml
tests/e2e/testfiles/values.yaml

Updated e2e tests in areas involving PowerScale and PowerFlex for Observability with Authorization. 
|https://github.com/dell/csm/issues/853|

More e2e test fixes

---

bundle/manifests/dell-csm-operator.clusterserviceversion.yaml
config/manifests/bases/dell-csm-operator.clusterserviceversion.yaml
config/samples/storage_v1_csm_powerflex.yaml
config/samples/storage_v1_csm_powermax.yaml
config/samples/storage_v1_csm_powerscale.yaml

Final manifest updates after Authorization module changes

Final manifest updates after Authorization module changes

---

.github/workflows/actions.yml
controllers/csm_controller.go
controllers/csm_controller_test.go
operatorconfig/moduleconfig/application-mobility/v0.3.0/velero-deployment.yaml
pkg/modules/application_mobility.go
samples/application-mobility/csm_application_mobility_v030.yaml
tests/e2e/steps/step_common.go
tests/e2e/testfiles/csm_application_mobility_cert_manager.yaml
tests/e2e/testfiles/csm_application_mobility_controller_diff_env.yaml
tests/e2e/testfiles/csm_application_mobility_test_velero.yaml
tests/e2e/testfiles/csm_application_mobility_vanilla.yaml
tests/e2e/testfiles/csm_application_mobility_velero_diff_env.yaml
tests/e2e/testfiles/csm_application_mobility_velero_with_cert.yaml

Add test coverage for controller as well as getting all actions to pass.

Controller unit test

---

samples/storage_csm_powermax_v260.yaml
samples/storage_csm_powermax_v270.yaml

Updating  nodeSelector and tolerations entries in powermax samples .
|https://github.com/dell/csm/issues/890 |

Updating node selector entries

---

Dockerfile
Makefile
bundle/manifests/dell-csm-operator.clusterserviceversion.yaml
config/install/kustomization.yaml
config/manager/kustomization.yaml
config/manifests/bases/dell-csm-operator.clusterserviceversion.yaml
deploy/olm/operator_community.yaml
deploy/operator.yaml
docker.mk

Bump up csm-operator version to v1.3.0
| https://github.com/dell/csm/issues/885 |
Sanity checks:

Bump-up csm-operator version to 1.3.0

---

api/v1/types.go
config/crd/bases/storage.dell.com_containerstoragemodules.yaml
deploy/crds/storage.dell.com_containerstoragemodules.yaml
operatorconfig/moduleconfig/application-mobility/v0.3.0/restic.yaml
operatorconfig/moduleconfig/application-mobility/v0.3.0/velero-crds.yaml
pkg/modules/application_mobility.go
pkg/modules/testdata/cr_application_mobility.yaml
pkg/utils/utils.go
samples/application-mobility/csm_application_mobility_v030.yaml

Adding restic support for application-mobility in csm-operator
| |

Adding restic support

---

bundle/manifests/dell-csm-operator.clusterserviceversion.yaml
config/samples/storage_v1_csm_unity.yaml
operatorconfig/driverconfig/unity/v2.8.0/controller.yaml
operatorconfig/driverconfig/unity/v2.8.0/csidriver.yaml
pkg/drivers/common_test.go
pkg/drivers/unity.go
samples/storage_csm_unity_v280.yaml
tests/config/driverconfig/unity/v2.8.0/controller.yaml
tests/config/driverconfig/unity/v2.8.0/csidriver.yaml
tests/e2e/testfiles/storage_csm_unity.yaml

Added SCT support for Unity XT on csm-operator
| https://github.com/dell/csm/issues/897|
Tested SCT feature for unity on csm-operator by installing the csm-operator build with SCT changes and creating a Unity CR using the Unity build with SCT changes. Test results look good

Feature 897 sct support for unity on csm operator

---

operatorconfig/moduleconfig/application-mobility/v0.3.0/velero-deployment.yaml
pkg/utils/utils.go

Added service yaml for velero deployment

Application mobility service yamls

---

bundle/manifests/dell-csm-operator.clusterserviceversion.yaml
config/manifests/bases/dell-csm-operator.clusterserviceversion.yaml
pkg/modules/testdata/cr_powerstore_resiliency.yaml
tests/e2e/testfiles/storage_csm_powerstore.yaml
tests/e2e/testfiles/storage_csm_powerstore_resiliency.yaml

Updated PowerStore e2e test files for volume limits feature.
Driver version bump in manifest yamls.
| https://github.com/dell/csm/issues/878 |

PowerStore: Updated e2e test files for volume limits feature

---

operatorconfig/moduleconfig/application-mobility/v0.3.0/appMobilitycrds.all.yaml
pkg/modules/application_mobility.go

Fixed unit-test and improved coverage to 93.6% 
| |

Fix crd and unit-test

---

samples/storage_csm_powerflex_v270.yaml
samples/storage_csm_powerflex_v280.yaml
samples/storage_csm_powerscale_v270.yaml
samples/storage_csm_powerscale_v280.yaml
samples/storage_csm_powerstore_v270.yaml
samples/storage_csm_powerstore_v280.yaml

|https://github.com/dell/csm/issues/898 |

Removed arrayConnectivityConnectionLossThreshold from podmon-node in Sample Files

---

tests/e2e/env-e2e-test.sh
tests/e2e/verify-app-mobility.sh

Initial changes for verify script to work with new dellctl version 
This is NOT main branch 
| |

modify verify script

---

operatorconfig/moduleconfig/application-mobility/v0.3.0/app-mobility-controller-manager.yaml
operatorconfig/moduleconfig/application-mobility/v0.3.0/node-agent.yaml
operatorconfig/moduleconfig/application-mobility/v0.3.0/velero-deployment.yaml
operatorconfig/moduleconfig/common/cert-manager.yaml
operatorconfig/moduleconfig/common/cert-manager/cert-manager.yaml
pkg/utils/status.go

Adding Application mobility status field and also checking services dependent on application-mobility if its succeeded in deploying
https://jira.cec.lab.emc.com/browse/KRV-15319
| |

App mob status

---

operatorconfig/driverconfig/powermax/v2.6.0/controller.yaml
operatorconfig/driverconfig/powermax/v2.7.0/controller.yaml
operatorconfig/driverconfig/powermax/v2.8.0/controller.yaml
operatorconfig/moduleconfig/csireverseproxy/v2.7.0/controller.yaml
operatorconfig/moduleconfig/observability/v1.4.0/karavi-metrics-powermax.yaml
operatorconfig/moduleconfig/observability/v1.6.0/karavi-metrics-powermax.yaml
pkg/modules/testdata/cr_powermax_reverseproxy.yaml
samples/storage_csm_powermax_v280.yaml

- Updates obs/proxy versions
- Removes duplicate key
|https://github.com/dell/csm/issues/885|

CSI Powermax: Updates Obs/proxy versions

---

controllers/csm_controller_test.go

Add some tests to hit some coverage gaps and bring coverage up to where main is.
Ran controller unit tests, confirmed passing.

Bump up controller unit test coverage for application-mobility branch

---

Dockerfile
Makefile
bundle/manifests/dell-csm-operator.clusterserviceversion.yaml
config/install/kustomization.yaml
config/manager/kustomization.yaml
config/manifests/bases/dell-csm-operator.clusterserviceversion.yaml
deploy/olm/operator_community.yaml
deploy/operator.yaml
docker.mk

Bump up csm-operator version to 1.4.0
|https://github.com/dell/csm/issues/1012|

Bump up csm-operator version to 1.4.0

---

controllers/csm_controller.go

Chaging the annotation case from snakecase to camelcase
| |

Annotation Camelcase

---

samples/storage_csm_unity_v260.yaml
samples/storage_csm_unity_v270.yaml
samples/storage_csm_unity_v280.yaml
tests/e2e/testfiles/storage_csm_unity.yaml

Added volume name prefix for Unity driver .
| https://github.com/dell/csm/issues/989|
Executed cert-csi tests .

Adding volume prefix for Unity

---

bundle/manifests/dell-csm-operator.clusterserviceversion.yaml
config/manifests/bases/dell-csm-operator.clusterserviceversion.yaml
config/samples/storage_v1_csm_powerflex.yaml
operatorconfig/driverconfig/common/default.yaml
operatorconfig/driverconfig/common/k8s-1.21-values.yaml
operatorconfig/driverconfig/common/k8s-1.22-values.yaml
operatorconfig/driverconfig/common/k8s-1.23-values.yaml
operatorconfig/driverconfig/common/k8s-1.24-values.yaml
operatorconfig/driverconfig/common/k8s-1.25-values.yaml
operatorconfig/driverconfig/common/k8s-1.26-values.yaml
operatorconfig/driverconfig/common/k8s-1.27-values.yaml
operatorconfig/driverconfig/common/k8s-1.28-values.yaml
operatorconfig/driverconfig/powerflex/v2.9.0/node.yaml
samples/storage_csm_powerflex_v290.yaml
tests/config/driverconfig/powerflex/v2.9.0/node.yaml
tests/e2e/testfiles/powerflex_alt_vals_4_values.csv
tests/e2e/testfiles/powerflex_alt_vals_5_values.csv
tests/e2e/testfiles/storage_csm_powerflex.yaml
tests/e2e/testfiles/storage_csm_powerflex_alt_vals_1.yaml
tests/e2e/testfiles/storage_csm_powerflex_alt_vals_2.yaml
tests/e2e/testfiles/storage_csm_powerflex_alt_vals_3.yaml
tests/e2e/testfiles/storage_csm_powerflex_alt_vals_4.yaml
tests/e2e/testfiles/storage_csm_powerflex_alt_vals_5.yaml
tests/e2e/testfiles/storage_csm_powerflex_auth.yaml
tests/e2e/testfiles/storage_csm_powerflex_observability.yaml
tests/e2e/testfiles/storage_csm_powerflex_observability_auth.yaml
tests/e2e/testfiles/storage_csm_powerflex_replica.yaml
tests/e2e/testfiles/storage_csm_powerflex_resiliency.yaml

SDC version changed from 4.5 to 3.6.1 for Powerflex
| https://github.com/dell/csm/issues/1012

SDC version changed from 4.5 to 3.6.1 for Powerflex

---

operatorconfig/driverconfig/powerflex/v2.9.0/controller.yaml
operatorconfig/driverconfig/powerflex/v2.9.0/node.yaml
operatorconfig/driverconfig/powerstore/v2.9.0/controller.yaml
operatorconfig/driverconfig/powerstore/v2.9.0/node.yaml
tests/config/driverconfig/powerflex/v2.9.0/controller.yaml
tests/config/driverconfig/powerflex/v2.9.0/node.yaml
tests/config/driverconfig/powerstore/v2.9.0/controller.yaml
tests/config/driverconfig/powerstore/v2.9.0/node.yaml

Sidecars version update for powerstore and powerflex
|https://github.com/dell/csm/issues/1012|

Sidecars version update for powerstore and powerflex

---

README.md
bundle.Dockerfile
bundle/metadata/annotations.yaml

Update OCP 4.14 changes
|  https://github.com/dell/csm/issues/1012 |
- Sanity tests

Update OCP 4.14 changes

---

operatorconfig/driverconfig/powerflex/v2.9.0/node.yaml
operatorconfig/driverconfig/powerstore/v2.9.0/node.yaml
tests/config/driverconfig/powerflex/v2.9.0/node.yaml
tests/config/driverconfig/powerstore/v2.9.0/node.yaml

Registrar version update for powerstore and powerflex
|https://github.com/dell/csm/issues/1012|

Registrar version update

---

bundle/manifests/dell-csm-operator.clusterserviceversion.yaml
config/manifests/bases/dell-csm-operator.clusterserviceversion.yaml
config/samples/storage_v1_csm_powerflex.yaml
operatorconfig/driverconfig/common/default.yaml
operatorconfig/driverconfig/common/k8s-1.21-values.yaml
operatorconfig/driverconfig/common/k8s-1.22-values.yaml
operatorconfig/driverconfig/common/k8s-1.23-values.yaml
operatorconfig/driverconfig/common/k8s-1.24-values.yaml
operatorconfig/driverconfig/common/k8s-1.25-values.yaml
operatorconfig/driverconfig/common/k8s-1.26-values.yaml
operatorconfig/driverconfig/common/k8s-1.27-values.yaml
operatorconfig/driverconfig/common/k8s-1.28-values.yaml
operatorconfig/driverconfig/powerflex/v2.9.0/node.yaml
samples/storage_csm_powerflex_v290.yaml
tests/config/driverconfig/powerflex/v2.9.0/node.yaml
tests/e2e/testfiles/powerflex_alt_vals_4_values.csv
tests/e2e/testfiles/powerflex_alt_vals_5_values.csv
tests/e2e/testfiles/storage_csm_powerflex.yaml
tests/e2e/testfiles/storage_csm_powerflex_alt_vals_1.yaml
tests/e2e/testfiles/storage_csm_powerflex_alt_vals_2.yaml
tests/e2e/testfiles/storage_csm_powerflex_alt_vals_3.yaml
tests/e2e/testfiles/storage_csm_powerflex_alt_vals_4.yaml
tests/e2e/testfiles/storage_csm_powerflex_alt_vals_5.yaml
tests/e2e/testfiles/storage_csm_powerflex_auth.yaml
tests/e2e/testfiles/storage_csm_powerflex_observability.yaml
tests/e2e/testfiles/storage_csm_powerflex_observability_auth.yaml
tests/e2e/testfiles/storage_csm_powerflex_replica.yaml
tests/e2e/testfiles/storage_csm_powerflex_resiliency.yaml

SDC version changed to 4.5 for PowerFlex
| https://github.com/dell/csm/issues/1012

SDC version changed to 4.5 for PowerFlex

---

operatorconfig/driverconfig/common/default.yaml
operatorconfig/driverconfig/common/k8s-1.24-values.yaml
operatorconfig/driverconfig/common/k8s-1.25-values.yaml
operatorconfig/driverconfig/common/k8s-1.26-values.yaml
operatorconfig/driverconfig/common/k8s-1.27-values.yaml
operatorconfig/driverconfig/common/k8s-1.28-values.yaml

Update sidecar versions in common places.
| https://github.com/dell/csm/issues/1012 |

Update sidecar versions

---

config/samples/storage_v1_csm_powerflex.yaml
operatorconfig/driverconfig/powerflex/v2.9.0/controller.yaml
operatorconfig/driverconfig/powerflex/v2.9.0/node.yaml
pkg/drivers/commonconfig.go
pkg/drivers/powerflex.go
samples/storage_csm_powerflex_v290.yaml

CSI Health monitor for Node added for PowerFlex
| https://github.com/dell/csm/issues/1058

CSI Health monitor for Node added for PowerFlex

---

bundle/manifests/dell-csm-operator.clusterserviceversion.yaml
config/manifests/bases/dell-csm-operator.clusterserviceversion.yaml
config/samples/storage_v1_csm_powermax.yaml
pkg/modules/testdata/cr_powermax_observability.yaml
samples/storage_csm_powermax_v290.yaml
tests/e2e/testfiles/storage_csm_powermax_observability.yaml

Observability metrics version bump for powermax
|https://github.com/dell/csm/issues/1012|

Update pmax metrics version

---

bundle.Dockerfile
bundle/manifests/dell-csm-operator.clusterserviceversion.yaml
bundle/manifests/storage.dell.com_apexconnectivityclients.yaml
bundle/manifests/storage.dell.com_containerstoragemodules.yaml
bundle/metadata/annotations.yaml
config/crd/bases/storage.dell.com_apexconnectivityclients.yaml
config/manager/manager.yaml
config/manifests/bases/dell-csm-operator.clusterserviceversion.yaml
deploy/crds/storage.dell.com.crds.all.yaml
deploy/operator.yaml

Final Manifest update

---

operatorconfig/clientconfig/apexconnectivityclient/v1.0.0/statefulset.yaml

PR for adding permissions for deleting license secrets.
| |

Add Permissions for deleting license secrets

---

Dockerfile
Makefile
bundle/manifests/dell-csm-operator.clusterserviceversion.yaml
config/install/kustomization.yaml
config/manager/kustomization.yaml
config/manifests/bases/dell-csm-operator.clusterserviceversion.yaml
deploy/olm/operator_community.yaml
deploy/operator.yaml
docker.mk

Bump up csm-operator version to v1.4.1
|https://github.com/dell/csm/issues/1109 |
make install
make run

Bump up csm-operator version to v1.4.1

---

operatorconfig/driverconfig/powerflex/v2.7.0/node.yaml
operatorconfig/driverconfig/powerflex/v2.8.0/node.yaml
operatorconfig/driverconfig/powerflex/v2.9.0/node.yaml
operatorconfig/driverconfig/powerflex/v2.9.1/node.yaml
tests/config/driverconfig/powerflex/v2.9.1/node.yaml

This PR reverts the changes in #426 
| https://github.com/dell/csm/issues/1109|

Reverting #426 Changes

---

operatorconfig/clientconfig/apexconnectivityclient/v1.0.0/statefulset.yaml
tests/config/clientconfig/apex/v1.0.0/statefulset.yaml

|https://github.com/dell/csm/issues/1029|

Add csm watch permissions.

---

operatorconfig/moduleconfig/application-mobility/v1.0.0/app-mobility-controller-manager.yaml
operatorconfig/moduleconfig/application-mobility/v1.0.0/velero-deployment.yaml
operatorconfig/moduleconfig/common/cert-manager.yaml
operatorconfig/moduleconfig/common/cert-manager/cert-manager.yaml
operatorconfig/moduleconfig/observability/v1.5.0/karavi-metrics-powerflex.yaml
operatorconfig/moduleconfig/observability/v1.5.0/karavi-metrics-powermax.yaml
operatorconfig/moduleconfig/observability/v1.5.0/karavi-metrics-powerscale.yaml
operatorconfig/moduleconfig/observability/v1.5.0/karavi-otel-collector.yaml
operatorconfig/moduleconfig/observability/v1.5.0/karavi-topology.yaml
operatorconfig/moduleconfig/observability/v1.6.0/karavi-metrics-powerflex.yaml
operatorconfig/moduleconfig/observability/v1.6.0/karavi-metrics-powermax.yaml
operatorconfig/moduleconfig/observability/v1.6.0/karavi-metrics-powerscale.yaml
operatorconfig/moduleconfig/observability/v1.6.0/karavi-otel-collector.yaml
operatorconfig/moduleconfig/observability/v1.6.0/karavi-topology.yaml
operatorconfig/moduleconfig/observability/v1.7.0/karavi-metrics-powerflex.yaml
operatorconfig/moduleconfig/observability/v1.7.0/karavi-metrics-powermax.yaml
operatorconfig/moduleconfig/observability/v1.7.0/karavi-metrics-powerscale.yaml
operatorconfig/moduleconfig/observability/v1.7.0/karavi-otel-collector.yaml
operatorconfig/moduleconfig/observability/v1.7.0/karavi-topology.yaml
pkg/modules/application_mobility.go
pkg/modules/commonconfig.go
pkg/modules/observability.go
pkg/utils/status.go
samples/storage_csm_powerflex_v290.yaml

Issue - CSM Operator was not calculating status correctly when driver was installed indepedently
It would show as failed even though pods were up and running
solution - the CSM status was not factoring the driver pods to calculate status as it would skip over a condition.
Fixed it by applying a new logic which checks driver status and module status as well
But the code has been changed to calculate the status of all supported modules in dreadnaught.
| https://github.com/dell/csm/issues/1130|
1) when driver is installed with no modules installed, since patch release has only …

Add csm-module status

---

Dockerfile
Makefile
bundle.Dockerfile
bundle/manifests/dell-csm-operator.clusterserviceversion.yaml
config/install/kustomization.yaml
config/manager/kustomization.yaml
config/manifests/bases/dell-csm-operator.clusterserviceversion.yaml
controllers/csm_controller.go
deploy/olm/operator_community.yaml
deploy/operator.yaml
docker.mk
tests/e2e/steps/steps_def.go

Update the CSM operator version to 1.4.2
| https://github.com/dell/csm/issues/1136 |
Fresh install in a non-olm env followed by driver install:
CSM operator installation in OLM env followed by driver install:

Bump up CSM Operator version to 1.4.2

---

tests/e2e/env-e2e-test.sh
tests/e2e/steps/steps_def.go

Update Authorization e2e for configurable proxy host address for karavictl.
| https://github.com/dell/csm/issues/1136|

[feature-1136]: Fix Authorization e2e

---

tests/e2e/steps/steps_def.go

Skip certificate validation in Authorization e2e.
|https://github.com/dell/csm/issues/1091 |

[feature-1136]: Skip Certificate Validatin in Authorization e2e

---

pkg/drivers/commonconfig.go
pkg/drivers/commonconfig_test.go

|https://github.com/dell/csm/issues/1103|

Fixing FSGroupPolicy issue

---

pkg/modules/application_mobility.go
pkg/modules/authorization.go
tests/e2e/testfiles/storage_csm_powerstore.yaml

fix vetting issues

---

Dockerfile
Makefile

Changes to include common golang image
|https://github.com/dell/csm/issues/1098 |

Changes to include common golang image

---

samples/storage_csm_powerflex_v2100.yaml
samples/storage_csm_powermax_v2100.yaml
samples/storage_csm_powerscale_v2100.yaml
samples/storage_csm_powerstore_v2100.yaml
samples/storage_csm_unity_v2100.yaml

Offline bundle sidecar issue ( workaround provide for now ) 
|https://github.com/dell/csm/issues/1094|
- 
- 
note : csi-metadata-retriever:v1.7.0 not released due to that used the csi-metadata-retriever:nightly  image 
Note : offline bundle against the main

Offline bundle sidecar issue

---

operatorconfig/moduleconfig/application-mobility/v1.0.2/app-mobility-controller-manager-metrics-service.yaml
operatorconfig/moduleconfig/application-mobility/v1.0.2/app-mobility-controller-manager.yaml
operatorconfig/moduleconfig/application-mobility/v1.0.2/app-mobility-crds.yaml
operatorconfig/moduleconfig/application-mobility/v1.0.2/app-mobility-webhook-service.yaml
operatorconfig/moduleconfig/application-mobility/v1.0.2/certificate.yaml
operatorconfig/moduleconfig/application-mobility/v1.0.2/node-agent.yaml
operatorconfig/moduleconfig/application-mobility/v1.0.2/velero-backupstoragelocation.yaml
operatorconfig/moduleconfig/application-mobility/v1.0.2/velero-crds.yaml
operatorconfig/moduleconfig/application-mobility/v1.0.2/velero-deployment.yaml
operatorconfig/moduleconfig/application-mobility/v1.0.2/velero-secret.yaml
operatorconfig/moduleconfig/application-mobility/v1.0.2/velero-volumesnapshotlocation.yaml
pkg/modules/testdata/cr_application_mobility.yaml
pkg/modules/testdata/cr_application_mobility_custom_region.yaml
tests/e2e/testfiles/application-mobility-templates/csm_application_mobility_vanilla.yaml
tests/e2e/testfiles/application-mobility-templates/csm_application_mobility_with_pflex.yaml
tests/e2e/testfiles/application-mobility-templates/csm_application_mobility_with_pflex_alt.yaml
tests/e2e/testfiles/application-mobility-templates/powerflex_noAM.yaml

This PR adds support for AM v1.0.2
>AM v1.0.2 is not released yet. This PR is assuming yamls needed for v1.0.0 and v1.0.2 are mostly the same. If not, will open another PR  
| https://github.com/dell/csm/issues/1164 |

Add AM 1.0.2 support

---

tests/e2e/testfiles/application-mobility-templates/powerflex_noAM.yaml
tests/e2e/testfiles/storage_csm_powerflex_observability_custom_cert.yaml
tests/e2e/testfiles/storage_csm_powerflex_observability_otel_custom_cert.yaml
tests/e2e/testfiles/storage_csm_powerflex_resiliency.yaml
tests/e2e/testfiles/storage_csm_powerscale_observability_top_custom_cert.yaml
tests/e2e/testfiles/storage_csm_powerscale_resiliency.yaml

Updating some E2E files for the v1.9.3 branch based on e2e testing. No actual code or image-related changes.
| https://github.com/dell/csm/issues/1164 |
Ran e2e tests

Updating e2e files

---

operatorconfig/driverconfig/powerflex/v2.7.0/node.yaml
operatorconfig/driverconfig/powerflex/v2.8.0/node.yaml
operatorconfig/driverconfig/powerflex/v2.9.0/node.yaml
operatorconfig/driverconfig/powerflex/v2.9.1/node.yaml

Updating older node.yaml config for CSM 1.9.3
|https://github.com/dell/csm/issues/1164|

Update node config

---

config/manifests/bases/dell-csm-operator.clusterserviceversion.yaml

Updated mandatory metadata annotations for CSM Operator. More details below:
https://app.partner.engage.redhat.com/e/es?s=940793389&e=60999&elqTrackId=d16e4b66f8074d27a3e8187b25322b95&elq=a80ad559e2fe45a4bbbb63b8724cd760&elqaid=4115&elqat=1
| https://github.com/dell/csm/issues/1091|

Updated mandatory metadata annotations

---

bundle/manifests/dell-csm-operator.clusterserviceversion.yaml
operatorconfig/driverconfig/common/default.yaml
operatorconfig/driverconfig/common/k8s-1.24-values.yaml
operatorconfig/driverconfig/common/k8s-1.25-values.yaml
operatorconfig/driverconfig/common/k8s-1.26-values.yaml
operatorconfig/driverconfig/common/k8s-1.27-values.yaml
operatorconfig/driverconfig/common/k8s-1.28-values.yaml
operatorconfig/driverconfig/common/k8s-1.29-values.yaml
operatorconfig/driverconfig/powerscale/v2.10.0/controller.yaml
samples/storage_csm_powerflex_v2100.yaml
samples/storage_csm_powermax_v2100.yaml
samples/storage_csm_powerscale_v2100.yaml
samples/storage_csm_powerstore_v2100.yaml
samples/storage_csm_unity_v2100.yaml

This PR updates csi-metadata-retriever version
|https://github.com/dell/csm/issues/1091 |

Updated csi-metadata-retriever version

---

operatorconfig/moduleconfig/application-mobility/v1.0.3/app-mobility-controller-manager-metrics-service.yaml
operatorconfig/moduleconfig/application-mobility/v1.0.3/app-mobility-controller-manager.yaml
operatorconfig/moduleconfig/application-mobility/v1.0.3/app-mobility-crds.yaml
operatorconfig/moduleconfig/application-mobility/v1.0.3/app-mobility-webhook-service.yaml
operatorconfig/moduleconfig/application-mobility/v1.0.3/certificate.yaml
operatorconfig/moduleconfig/application-mobility/v1.0.3/node-agent.yaml
operatorconfig/moduleconfig/application-mobility/v1.0.3/velero-backupstoragelocation.yaml
operatorconfig/moduleconfig/application-mobility/v1.0.3/velero-crds.yaml
operatorconfig/moduleconfig/application-mobility/v1.0.3/velero-deployment.yaml
operatorconfig/moduleconfig/application-mobility/v1.0.3/velero-secret.yaml
operatorconfig/moduleconfig/application-mobility/v1.0.3/velero-volumesnapshotlocation.yaml
tests/e2e/testfiles/application-mobility-templates/csm_application_mobility_vanilla.yaml
tests/e2e/testfiles/application-mobility-templates/csm_application_mobility_with_pflex.yaml
tests/e2e/testfiles/application-mobility-templates/csm_application_mobility_with_pflex_alt.yaml
tests/e2e/testfiles/application-mobility-templates/powerflex_noAM.yaml

A new patch of AM is coming out 🥳 
This PR adds support for v1.0.3 in operator 
| |

add v1.0.3 support

---

Dockerfile
bundle/manifests/dell-csm-operator.clusterserviceversion.yaml
config/install/kustomization.yaml
config/manager/kustomization.yaml
config/manifests/bases/dell-csm-operator.clusterserviceversion.yaml
controllers/csm_controller.go
deploy/olm/operator_community.yaml
deploy/operator.yaml
docker.mk

Update csm-operator versions from v1.4.3 to v1.4.4 and csm versions from v1.9.3 to v1.9.4.
| none yet |
Installed driver with operator and confirmed correct versions are shown.

CSM_Operator v1.4.4 version updates

---

operatorconfig/clientconfig/apexconnectivityclient/v1.0.0/statefulset.yaml

Adding the namespaces to the statefulset.yaml causes them to be deleted, so we need to remove them and have the customer create them manually.
| |

Don't delete namespaces on uninstall

---

scripts/install_connectivity_client.sh
scripts/uninstall_connectivity_client.sh

Add scripts for installation and uninstallation of the connectivity client.
[1233](https://github.com/dell/csm/issues/1233) |

Add scripts to install and uninstall ACC

---

Dockerfile
bundle/manifests/dell-csm-operator.clusterserviceversion.yaml
config/install/kustomization.yaml
config/manager/kustomization.yaml
config/manifests/bases/dell-csm-operator.clusterserviceversion.yaml
controllers/csm_controller.go
deploy/olm/operator_community.yaml
deploy/operator.yaml
docker.mk

Initial patch-v1.10.2 updates
|https://github.com/dell/csm/issues/1280|

Initial patch-v1.10.2 updates

---

go.mod
go.sum
operatorconfig/moduleconfig/authorization/v2.0.0-alpha/deployment.yaml
pkg/modules/authorization.go
pkg/modules/authorization_test.go

Remove karavi-storage-secret references for v2.
| |

Remove Karavi Storage Secret for v2

---

bundle/manifests/dell-csm-operator.clusterserviceversion.yaml
config/manager/manager.yaml
config/samples/storage_v1_csm_powerflex.yaml
config/samples/storage_v1_csm_powermax.yaml
config/samples/storage_v1_csm_powerscale.yaml
config/samples/storage_v1_csm_powerstore.yaml
config/samples/storage_v1_csm_unity.yaml
deploy/operator.yaml
operatorconfig/driverconfig/common/default.yaml
operatorconfig/driverconfig/common/k8s-1.24-values.yaml
operatorconfig/driverconfig/common/k8s-1.25-values.yaml
operatorconfig/driverconfig/common/k8s-1.26-values.yaml
operatorconfig/driverconfig/common/k8s-1.27-values.yaml
operatorconfig/driverconfig/common/k8s-1.28-values.yaml
operatorconfig/driverconfig/common/k8s-1.29-values.yaml
operatorconfig/driverconfig/powerscale/v2.10.1/controller.yaml
samples/storage_csm_powerflex_v2101.yaml
samples/storage_csm_powermax_v2101.yaml
samples/storage_csm_powerscale_v2101.yaml
samples/storage_csm_powerstore_v2101.yaml
samples/storage_csm_unity_v2101.yaml

|https://github.com/dell/csm/issues/1284|

metadata retriever sidecar update

---

operatorconfig/moduleconfig/authorization/v2.0.0-alpha/deployment.yaml

Update lease permissions for authorization-controller

Update lease permissions for authorization-controller

---

operatorconfig/clientconfig/apexconnectivityclient/v1.0.0/statefulset.yaml
operatorconfig/moduleconfig/application-mobility/v1.0.3/app-mobility-controller-manager-metrics-service.yaml
operatorconfig/moduleconfig/application-mobility/v1.0.3/app-mobility-controller-manager.yaml
operatorconfig/moduleconfig/application-mobility/v1.0.3/app-mobility-crds.yaml
operatorconfig/moduleconfig/application-mobility/v1.0.3/app-mobility-webhook-service.yaml
operatorconfig/moduleconfig/application-mobility/v1.0.3/certificate.yaml
operatorconfig/moduleconfig/application-mobility/v1.0.3/node-agent.yaml
operatorconfig/moduleconfig/application-mobility/v1.0.3/velero-backupstoragelocation.yaml
operatorconfig/moduleconfig/application-mobility/v1.0.3/velero-crds.yaml
operatorconfig/moduleconfig/application-mobility/v1.0.3/velero-deployment.yaml
operatorconfig/moduleconfig/application-mobility/v1.0.3/velero-secret.yaml
operatorconfig/moduleconfig/application-mobility/v1.0.3/velero-volumesnapshotlocation.yaml
pkg/utils/utils.go
tests/e2e/testfiles/application-mobility-templates/csm_application_mobility_vanilla.yaml
tests/e2e/testfiles/application-mobility-templates/csm_application_mobility_with_pflex.yaml
tests/e2e/testfiles/application-mobility-templates/csm_application_mobility_with_pflex_alt.yaml
tests/e2e/testfiles/application-mobility-templates/powerflex_noAM.yaml

Cherrypick changes from v1.4.4 release into main.
| |
Successfully ran operator e2e sanity test suite.
Successfully connected a cluster and installed csi-powerflex with observability and app-mobility through DN:

Cherrypick v1.4.4 changes into main

---

controllers/csm_controller.go
operatorconfig/driverconfig/powerflex/v2.10.0/upgrade-path.yaml
operatorconfig/driverconfig/powerflex/v2.8.0/upgrade-path.yaml
operatorconfig/driverconfig/powerflex/v2.9.0/upgrade-path.yaml
operatorconfig/driverconfig/powerflex/v2.9.1/upgrade-path.yaml
operatorconfig/driverconfig/powerflex/v2.9.2/upgrade-path.yaml
pkg/utils/utils.go

The Previous PR(https://github.com/dell/csm-operator/pull/575) had unsigned commits in the PR. so raising a new PR by cherry picking commits from previous PR
| |

Add downgrade support

---

operatorconfig/moduleconfig/authorization/v2.0.0-alpha/deployment.yaml
pkg/modules/testdata/cr_auth_proxy.yaml
pkg/modules/testdata/cr_auth_proxy_bad_vault_cert.yaml
pkg/modules/testdata/cr_auth_proxy_bad_vault_key.yaml
pkg/modules/testdata/cr_auth_proxy_no_redis.yaml
pkg/modules/testdata/cr_auth_proxy_openshift.yaml
pkg/modules/testdata/cr_auth_proxy_vault_cert.yaml
samples/authorization/csm_authorization_proxy_server_v200-alpha.yaml
tests/e2e/testfiles/authorization-templates/csm_authorization_proxy_server.yaml

1. Fix sentinel deployment timeout. 
2. Fix redis commander pod name
https://github.com/dell/csm/issues/1281

fix sentinel timeout

---

controllers/csm_controller.go
operatorconfig/moduleconfig/application-mobility/v1.0.3/upgrade-path.yaml

Added app-mobility module upgrade support
| https://github.com/dell/csm/issues/1324 |

Added annotations for app-mobility upgrade

---

operatorconfig/clientconfig/apexconnectivityclient/v1.0.0/statefulset.yaml

Update permission for containerstorage module
| https://github.com/dell/csm/issues/1221 |

Update permission for containerstorage module

---

bundle/manifests/dell-csm-operator.clusterserviceversion.yaml
config/manager/manager.yaml
config/manifests/bases/dell-csm-operator.clusterserviceversion.yaml
config/samples/storage_v1_csm_connectivity_client.yaml
controllers/acc_controller.go
controllers/acc_controller_test.go
deploy/operator.yaml
operatorconfig/clientconfig/apexconnectivityclient/v1.1.0/brownfield-onboard.yaml
operatorconfig/clientconfig/apexconnectivityclient/v1.1.0/statefulset.yaml
operatorconfig/clientconfig/apexconnectivityclient/v1.1.0/upgrade-path.yaml
pkg/resources/statefulset/statefulset.go
samples/connectivity_client_secret.yaml
samples/connectivity_client_v100.yaml
samples/connectivity_client_v110.yaml
scripts/install_connectivity_client.sh
tests/config/clientconfig/apexconnectivityclient/v1.1.0/bad.yaml
tests/config/clientconfig/apexconnectivityclient/v1.1.0/statefulset.yaml
tests/config/clientconfig/badclient/v1.1.0/statefulset.yaml
tests/e2e/testfiles/connectivity_client.yaml
tests/shared/common.go

ANK8S connectivity client latest version support 
|https://github.com/dell/csm/issues/1221|

Connectivity client latest

---

operatorconfig/moduleconfig/common/version-values.yaml
samples/storage_csm_powermax_v2110.yaml

Update latest sample with resiliency section
| https://github.com/dell/csm/issues/1221|
- Cluster Build

Update latest sample with resiliency section

---

operatorconfig/driverconfig/powermax/v2.10.0/node.yaml
operatorconfig/driverconfig/powermax/v2.11.0/node.yaml
operatorconfig/driverconfig/powermax/v2.9.0/node.yaml
operatorconfig/driverconfig/powermax/v2.9.1/node.yaml
tests/e2e/testfiles/scenarios.yaml

- Updates csi-powermax changes for current features
|https://github.com/dell/csm/issues/1221|

Updates few csi-powermax files for current features

---

pkg/drivers/unity_test.go

| https://github.com/dell/csm/issues/1222 |

Add missing UT for allowed networks 

---

pkg/modules/authorization_test.go
pkg/modules/testdata/cr_auth_proxy_diff_namespace.yaml

Add unit test for dynamic namespaces with kube-mgmt policies for Authorization.
|https://github.com/dell/csm/issues/1205 |
New unit test.

[bug-1205]: Add unit test for kube-mgmt policies

---

tests/e2e/run-e2e-test.sh
tests/e2e/steps/steps_def.go
tests/e2e/testfiles/application-mobility-templates/csm_application_mobility_n_minus_1.yaml
tests/e2e/testfiles/application-mobility-templates/csm_application_mobility_no_velero.yaml
tests/e2e/testfiles/application-mobility-templates/csm_application_mobility_with_pflex.yaml
tests/e2e/testfiles/application-mobility-templates/csm_application_mobility_with_pflex_alt.yaml
tests/e2e/testfiles/application-mobility-templates/velero-values.yaml
tests/e2e/testfiles/scenarios.yaml
tests/e2e/verify-app-mobility.sh

Update all application mobility operator e2e tests and fix misconfigurations.
| https://github.com/dell/csm/issues/1221 |
[am-test-results.txt](https://github.com/user-attachments/files/16274622/am-test-results.txt)

Fix Application Mobility E2E Tests

---

bundle/manifests/dell-csm-operator.clusterserviceversion.yaml
bundle/manifests/storage.dell.com_apexconnectivityclients.yaml
config/manifests/bases/dell-csm-operator.clusterserviceversion.yaml

Corrected unintended changes that were generated during final manifest updates
|https://github.com/dell/csm/issues/1221 |

Correct manifest changes 160

---

pkg/modules/reverseproxy.go

WIP - Minimal sample files
| |

Draft PR, do not merge: Added default values for minimal yaml

---

pkg/drivers/powerscale.go
samples/minimal-samples/unity.yaml

Added minmal unity yaml

---

samples/authorization/csm_authorization_proxy_server_v200-alpha.yaml
samples/authorization/csm_authorization_proxy_server_v200.yaml

Merge Powerscale and Powermax support branch into main for Authorization v2.
|https://github.com/dell/csm/issues/1281 |
Existing unit tests and manual installation with cert-csi.

[feature-1281]: Merge Powerscale support to main for Authorization v2

---

config/crd/bases/storage.dell.com_containerstoragemodules.yaml
deploy/crds/storage.dell.com.crds.all.yaml
operatorconfig/moduleconfig/authorization/v2.0.0/authorization-crds.yaml

Update `config/crd/bases/storage.dell.com_containerstoragemodules.yaml` and `deploy/crds/storage.dell.com.crds.all.yaml` with multiple Vault configuration.
| https://github.com/dell/csm/issues/1281|
Manually installed Operator and installed Authorization CR.

[feature-1281]: Update base CSM CRD and all CRDs with multiple Vault configuration

---

pkg/drivers/unity.go

Update unity code

---

deploy/operator.yaml

Fix Operator image.
| https://github.com/dell/csm/issues/1281|
Existing tests.

Use correct image in deploy/operator.yaml

---

samples/minimal-samples/powerflex.yaml
samples/minimal-samples/powermax.yaml
samples/minimal-samples/powerscale.yaml
samples/minimal-samples/powerstore.yaml
samples/minimal-samples/unity.yaml

This PR has the changes for minimizing the manifest file for All the Driver
|https://github.com/dell/csm/issues/1449|
[x] Test A: I have run the basic sanity in my setup

Minimal manifest changes for Drivers

---

samples/minimal-samples/powermax.yaml

This PR has the changes for minimizing the manifest file for the Authorization Module in the PowerMax Driver
| https://github.com/dell/csm/issues/1449|

Minimal manifest changes for powermax with authorization module

---

tests/README.md

Change in the readme file to include namespace creation for PowerMax and PowerStore for their respective e2e testing.
| |

Readme change pmax + pstore

---

operatorconfig/moduleconfig/replication/v1.8.1/controller.yaml
operatorconfig/moduleconfig/replication/v1.9.0/controller.yaml
pkg/modules/replication.go
pkg/utils/utils.go
samples/minimal-samples/powerflex.yaml
samples/minimal-samples/powerscale.yaml

Added support to install Replication module with the minimal manifest for PowerFlex and PowerScale.
|dell/csm#1449|

Added support for replication with minimal manifest

---

operatorconfig/driverconfig/common/default.yaml
operatorconfig/driverconfig/common/k8s-1.24-values.yaml
operatorconfig/driverconfig/common/k8s-1.25-values.yaml
operatorconfig/driverconfig/common/k8s-1.26-values.yaml
operatorconfig/driverconfig/common/k8s-1.27-values.yaml
operatorconfig/driverconfig/common/k8s-1.28-values.yaml
operatorconfig/driverconfig/common/k8s-1.29-values.yaml
operatorconfig/driverconfig/common/k8s-1.30-values.yaml
operatorconfig/driverconfig/common/k8s-1.31-values.yaml
operatorconfig/moduleconfig/csireverseproxy/v2.11.0/container.yaml
pkg/modules/testdata/cr_powermax_reverseproxy.yaml

Updated the CSI powermax reverseproxy version to 2.11.0
| https://github.com/dell/csm/issues/1435|
- Installed powermax with reverproxy with nightly image
[reverseproxylog.txt](https://github.com/user-attachments/files/17363550/reverseproxylog.txt)

CSI powermax reverseproxy version update

---

tests/e2e/testfiles/minimal-testfiles/scenarios.yaml

Fix for the E2E tests for resilinecy module in PowerFlex driver.
|https://github.com/dell/csm/issues/1449 |
- [X ] I have maintained at least 90% code coverage
- [ X] I have made corresponding changes to the documentation
- [ X] I have added tests that prove my fix is effective or that my feature works
- [ X] I have maintained backward compatibility
- [ X] Tested the scenario on the k8s cluster:

E2E tests fix for Pflex driver in minimal manifest file

---

tests/e2e/run-e2e-test.sh

Added the condition in the function **checkForDellctl** to check if the file already exists.
|https://github.com/dell/csm/issues/1541 |
- [X ] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [ X] I have verified that new and existing unit tests pass locally with my changes
- [ X] I have not allowed coverage numbers to degenerate
- [ X] I have maintained at least 90% code coverage
- [X ] I have commented my code, particularly in hard-to-understand areas
- [X ] I have made corresponding changes to the documentation
- [X ] I have added tests that prove my fix is effective or that my feature works
- [X ] I have maintained backward …

Operator E2E script fix

---

bundle/manifests/dell-csm-operator.clusterserviceversion.yaml
config/install/kustomization.yaml
config/manager/kustomization.yaml
config/manager/manager.yaml
config/manifests/bases/dell-csm-operator.clusterserviceversion.yaml
config/samples/storage_v1_csm_powerflex.yaml
config/samples/storage_v1_csm_powermax.yaml
config/samples/storage_v1_csm_powerscale.yaml
config/samples/storage_v1_csm_powerstore.yaml
config/samples/storage_v1_csm_unity.yaml
deploy/olm/operator_community.yaml
deploy/operator.yaml
operatorconfig/driverconfig/common/default.yaml
operatorconfig/driverconfig/common/k8s-1.31-values.yaml
samples/storage_csm_powerflex_v2120.yaml
samples/storage_csm_powermax_v2120.yaml
samples/storage_csm_powerscale_v2120.yaml
samples/storage_csm_powerstore_v2120.yaml
samples/storage_csm_unity_v2120.yaml
tests/e2e/testfiles/minimal-testfiles/storage_csm_powerscale_replica.yaml
tests/e2e/testfiles/storage_csm_powermax.yaml
tests/e2e/testfiles/storage_csm_powermax_authorization.yaml
tests/e2e/testfiles/storage_csm_powermax_observability.yaml
tests/e2e/testfiles/storage_csm_powermax_resiliency.yaml
tests/e2e/testfiles/storage_csm_powermax_sidecar.yaml

This PR addresses 2 changes:
- Update image path to quay.io
- Update module versions
| https://github.com/dell/csm/issues/1435 |

update image path to quay

---

Dockerfile
bundle/manifests/dell-csm-operator.clusterserviceversion.yaml
config/install/kustomization.yaml
config/manager/kustomization.yaml
config/manifests/bases/dell-csm-operator.clusterserviceversion.yaml
controllers/csm_controller.go
deploy/olm/operator_community.yaml
deploy/operator.yaml
docker.mk

CSM version update

---

samples/storage_csm_powerflex_v2101.yaml
samples/storage_csm_powerflex_v2110.yaml
samples/storage_csm_powerflex_v2120.yaml
samples/storage_csm_powermax_v2101.yaml
samples/storage_csm_powermax_v2110.yaml
samples/storage_csm_powermax_v2120.yaml
samples/storage_csm_powerscale_v2101.yaml
samples/storage_csm_powerscale_v2110.yaml
samples/storage_csm_powerscale_v2120.yaml
samples/storage_csm_powerstore_v2101.yaml
samples/storage_csm_powerstore_v2110.yaml
samples/storage_csm_powerstore_v2120.yaml
samples/storage_csm_unity_v2101.yaml
samples/storage_csm_unity_v2110.yaml
samples/storage_csm_unity_v2120.yaml

Updated the comments with proper default values of parameter in sample files.
| https://github.com/dell/csm/issues/1559 |

Updated the comments with proper default values of parameter in sample files.

---

tests/e2e/testfiles/powermax-templates/powermax_reverse_proxy_config.yaml

Revert "Fix for reverse proxy config"

---

.github/workflows/release.yaml

Added action to release operator
|dell/csm#1490 |

Action to release operator

---

go.mod
k8s/client.go
k8s/client_test.go

Increase the k8s package unit test coverage past the 90% threshold.
| https://github.com/dell/csm/issues/1707 |
```
2025-02-12T16:34:16.6526316Z PASS
2025-02-12T16:34:16.6526625Z coverage: 90.3% of statements
2025-02-12T16:34:16.6527001Z ok  	github.com/dell/csm-operator/k8s	1.139s	coverage: 90.3% of statements
```

Increase the k8s Unit Test Coverage

---

Makefile
controllers/csm_controller.go
pkg/modules/testdata/cr_powermax_observability_use_secret.yaml

Add missing observability testdata file.
```
PASS
coverage: 90.3% of statements
ok      github.com/dell/csm-operator/pkg/modules        0.821s  coverage: 90.3% of statements
```

Add missing testdata files

---

tests/e2e/testfiles/minimal-testfiles/scenarios.yaml
tests/e2e/testfiles/scenarios.yaml

This is an attempt to resolve the issue where the feature content hasn't been released and to stop the pipelines from running these.
These will be reintroduced once the feature changes are merged into csi-powermax.
| |

Remove tags from mount credentials e2e

---

operatorconfig/driverconfig/powerflex/v2.13.1/controller.yaml
operatorconfig/driverconfig/powerflex/v2.13.1/csidriver.yaml
operatorconfig/driverconfig/powerflex/v2.13.1/driver-config-params.yaml
operatorconfig/driverconfig/powerflex/v2.13.1/node.yaml
operatorconfig/driverconfig/powerflex/v2.13.1/upgrade-path.yaml
samples/minimal-samples/powerflex_v2131.yaml
samples/storage_csm_powerflex_v2131.yaml

csi-powerflex v2.13.1 to capture the fixes in https://github.com/dell/csm-operator/pull/913.
|https://github.com/dell/csm/issues/1782 |
Manual installation of the Operator and driver with application issue described in noted GH issue tested to be fixed.

[bug-1782]: Fixes for patch release

---

bundle/manifests/dell-csm-operator.clusterserviceversion.yaml
config/manager/manager.yaml
config/manifests/bases/dell-csm-operator.clusterserviceversion.yaml
config/samples/storage_v1_csm_powerflex.yaml
deploy/olm/operator_community.yaml
deploy/operator.yaml
operatorconfig/driverconfig/powerflex/v2.13.1/node.yaml
operatorconfig/moduleconfig/common/version-values.yaml

Updates references from:
- operator:v1.8.0 -> operator:v1.8.1
- csi-vxflexos:v2.13.0 -> csi-vxflexos:v2.13.1
| https://github.com/dell/csm/issues/1811 |

Upgrade versions for patch

---

controllers/csm_controller.go
controllers/csm_controller_test.go
deploy/operator.yaml
operatorconfig/driverconfig/powerflex/v2.13.1/node.yaml
pkg/drivers/powerflex.go
pkg/drivers/powerflex_test.go
tests/config/driverconfig/powerflex/v2.13.1/bad.yaml
tests/config/driverconfig/powerflex/v2.13.1/controller.yaml
tests/config/driverconfig/powerflex/v2.13.1/csidriver.yaml
tests/config/driverconfig/powerflex/v2.13.1/driver-config-params.yaml
tests/config/driverconfig/powerflex/v2.13.1/node.yaml
tests/config/driverconfig/powerflex/v2.13.1/upgrade-path.yaml

This PR fixes an issue discovered when installing CSM 1.13.1 on OCP, as well as updating versions for the new patch, 
| https://github.com/dell/csm/issues/1811 |

Update Versions for patch, fix install issue on OCP

---

.github/workflows/release.yaml

This PR updates the release workflow in the GitHub actions to the latest version.
|https://github.com/dell/csm/issues/1782 |
This action update is tested and working in `main`.

Update release workflow to match main branch

---

operatorconfig/driverconfig/powermax/v2.14.0/controller.yaml
operatorconfig/driverconfig/powermax/v2.14.0/node.yaml

Driver RBAC changes for PowerMax
| https://github.com/dell/csm/issues/1751 |
Logs: [cert-csi-rbac-pmax-operator.txt](https://github.com/user-attachments/files/19811422/cert-csi-rbac-pmax-operator.txt)

Driver RBAC changes for PowerMax

---

operatorconfig/moduleconfig/observability/v1.12.0/karavi-metrics-powermax.yaml

RBAC changes for PowerMax Observability module.
| https://github.com/dell/csm/issues/1751 |

RBAC Changes for Observability PowerMax

---

controllers/csm_controller.go
operatorconfig/driverconfig/powerflex/v2.13.1/node.yaml
operatorconfig/moduleconfig/authorization/v2.2.0/deployment.yaml
pkg/modules/replication.go
pkg/modules/replication_test.go
pkg/utils/utils.go
pkg/utils/utils_test.go

Added functionality to install the Replication CRDs into the local cluster.
| |
- Tested Replication install/uninstall both cases where CRD was not installed and installed prior to install.

Install Replication CRDs with module.

---

tests/config/driverconfig/powerflex/v2.14.0/controller.yaml
tests/config/driverconfig/powerflex/v2.14.0/node.yaml
tests/config/driverconfig/powermax/v2.14.0/controller.yaml
tests/config/driverconfig/powermax/v2.14.0/node.yaml
tests/config/driverconfig/powerscale/v2.14.0/controller.yaml
tests/config/driverconfig/powerscale/v2.14.0/node.yaml
tests/config/driverconfig/powerstore/v2.14.0/controller.yaml
tests/config/driverconfig/powerstore/v2.14.0/node.yaml
tests/config/driverconfig/unity/v2.14.0/controller.yaml
tests/config/driverconfig/unity/v2.14.0/node.yaml

RBAC: Test files changes for operator e2e.
| https://github.com/dell/csm/issues/1751|
- operator e2e will be run from the feature branch.

RBAC: Test files changes for operator e2e

---

tests/e2e/testfiles/powerflex_alt_vals_4_values.csv
tests/e2e/testfiles/powerflex_alt_vals_5_values.csv
tests/e2e/testfiles/storage_csm_powerflex.yaml
tests/e2e/testfiles/storage_csm_powerflex_alt_vals_1.yaml
tests/e2e/testfiles/storage_csm_powerflex_alt_vals_2.yaml
tests/e2e/testfiles/storage_csm_powerflex_alt_vals_3.yaml
tests/e2e/testfiles/storage_csm_powerflex_alt_vals_4.yaml
tests/e2e/testfiles/storage_csm_powerflex_auth.yaml
tests/e2e/testfiles/storage_csm_powerflex_auth_n_minus_1.yaml
tests/e2e/testfiles/storage_csm_powerflex_health_monitor.yaml
tests/e2e/testfiles/storage_csm_powerflex_no_sdc.yaml
tests/e2e/testfiles/storage_csm_powerflex_observability.yaml
tests/e2e/testfiles/storage_csm_powerflex_observability_auth.yaml
tests/e2e/testfiles/storage_csm_powerflex_observability_custom_cert.yaml
tests/e2e/testfiles/storage_csm_powerflex_observability_otel_custom_cert.yaml
tests/e2e/testfiles/storage_csm_powerflex_replica.yaml
tests/e2e/testfiles/storage_csm_powerflex_resiliency.yaml

|https://github.com/dell/csm/issues/1752|
- Scenarios Executed:
Install PowerFlex Driver(Standalone)
Install PowerFlex Driver with first set of alternate values
Install PowerFlex Driver with second set of alternate values
Install PowerFlex Driver with third set of alternate values
Install PowerFlex Driver with fourth set of alternate values
Install PowerFlex Driver without SDC
Install PowerFlex Driver with health monitor
Install Powerflex Driver (With Replication)
Install Powerflex Driver (Standalone), …

sftp e2e changes

---

README.md
docs/SUPPORT.md

Readme broken link fix for Documentation
|https://github.com/dell/csm/issues/1707 |

README.md fix

---

tests/e2e/testfiles/scenarios.yaml

Remove scenario that installs driver on multiple platforms as it conflicts with the CICD pipeline requirements.
|https://github.com/dell/csm/issues/1896|

Remove multiplatform test.

---

operatorconfig/driverconfig/powerstore/v2.15.0/controller.yaml

While powerstore and replication can be installed via operator, they cannot actually create RGs. This is due to missing permissions in our operatorconfig yaml. 
These are the errors you can spot in the logs:
```
"level":"error","msg":"getClusterUuid error: namespaces \"kube-system\" is forbidden: User \"system:serviceaccount:powerstore:powerstore-controller\" cannot get resource \"namespaces\" in API group \"\" in the namespace \"kube-system\"","time":"2025-07-14T20:09:49.137346638Z"} 
```
and
```
{"error":"persistentvolumes \"csivol-0fa9100f75\" is forbidden: User \"system:serviceaccount:openshift-operators:powerstore-controller\" cannot update resource \"persistentvolumes\" in API …
```

Fix replication and powerstore permission issue 

---

bundle/manifests/csm-config-params_v1_configmap.yaml
config/samples/storage_v1_csm_authorization_v2.yaml
pkg/modules/testdata/cr_auth_proxy_certs.yaml
pkg/modules/testdata/cr_auth_proxy_certs_missing_key.yaml
pkg/modules/testdata/cr_auth_proxy_k8s_secret.yaml
pkg/modules/testdata/cr_auth_proxy_k8s_secret_and_secret_provider_class.yaml
pkg/modules/testdata/cr_auth_proxy_no_k8s_secret_and_secret_provider_class.yaml
pkg/modules/testdata/cr_auth_proxy_no_redis.yaml
pkg/modules/testdata/cr_auth_proxy_openshift.yaml
pkg/modules/testdata/cr_auth_proxy_secret_provider_class.yaml
pkg/modules/testdata/cr_auth_proxy_v230.yaml

A follow-up PR to https://github.com/dell/csm-operator/pull/1050 - updating the parameter name at other places (eg: 2.3.0 config/test files).
| https://github.com/dell/csm/issues/1970 |
Operator image was built successfully.

Updated references to Concurrent storage requests

---

api/v1/csm_types.go
api/v1/types.go
bundle/manifests/dell-csm-operator.clusterserviceversion.yaml
bundle/manifests/storage.dell.com_containerstoragemodules.yaml
catalog-template/csm-operator-template.yaml
config/crd/bases/storage.dell.com_containerstoragemodules.yaml
config/manager/manager.yaml
config/manifests/bases/dell-csm-operator.clusterserviceversion.yaml
config/rbac/auth_endpointslice_clusterrole.yaml
config/rbac/auth_endpointslice_role_binding.yaml
config/rbac/kustomization.yaml
config/rbac/role.yaml
controllers/csm_controller.go
deploy/crds/storage.dell.com.crds.all.yaml
deploy/operator.yaml

The PR addresses the following issues:
- The CSV and CRD in bundle folder were not updated.
-  Also, operator.yaml in deploy folder was not generated properly. 
- Node status and controller status were showing invalid in OCP UI
- Upgrade path was missing in catalog-template
| https://github.com/dell/csm/issues/1896 |
Installed operator using OCP UI followed by a driver installation.

Update CSV and CRD

---

pkg/drivers/powerstore.go
pkg/drivers/powerstore_test.go

This reverts commit 77c5a350c24177e95cb982e7d666caee4133611f.
| |

Revert "Added check for auth env. (#1130)"
