dell/csm-operator

k8s/client.go, k8s/client_test.go, main.go
Fetch the right config file in case of Openshift environment
| https://github.com/dell/csm/issues/254 |
Installation in k8s : 
Installation in OCP:
=> KRV-3862 : Fetch the right config file in case of Openshift environment

bundle/manifests/dell-csm-operator-leader-election-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml, bundle/manifests/dell-csm-operator-proxy-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, bundle/manifests/dell-csm-operator.clusterserviceversion.yaml, config/default/kustomization.yaml, config/manager/manager.yaml, config/rbac/auth_proxy_role_binding.yaml, config/rbac/leader_election_role_binding.yaml, config/rbac/role_binding.yaml, config/serviceaccount/serviceaccount.yaml, deploy/olm/operator_community.yaml, deploy/operator.yaml
This PR 
- Fixes the issue where CSV was getting installed in all namepaces
- Sets the namespace to default for all objects 
- Corrects the ServiceAccount name
Validation Screenshots
**Before fix**
**After fix**
=> Set namespace to default and correct serviceaccount name

Dockerfile
Update ubi image to 8.6-902.1661794353
- Ran sanity
[build-logs-latest-ubi-image-update.log](https://github.com/dell/csm-operator/files/9496414/build-logs-latest-ubi-image-update.log)
=> Update ubi image to latest

bundle/manifests/dell-csm-operator.clusterserviceversion.yaml, config/samples/storage_v1_csm_powerscale.yaml, controllers/csm_controller_test.go, pkg/modules/authorization_test.go, pkg/modules/testdata/cr_powerscale_auth.yaml, tests/e2e/testfiles/storage_csm_powerscale.yaml, tests/e2e/testfiles/storage_csm_powerscale_auth.yaml
Update driver and module versions in manifests
- https://osj-sio-03-prd.cec.lab.emc.com/job/CSM-Operator/job/dell-csm-operator-sanity-k8s-v124/5/consoleFull
- https://osj-sio-03-prd.cec.lab.emc.com/job/CSM-Operator/job/dell-csm-operator-sanity-ocp-kv49/2/consoleFull
- https://osj-sio-03-prd.cec.lab.emc.com/job/CSM-Operator/job/dell-csm-operator-upgrade-test-ocp-kv49/68/console
=> Update version of driver and modules in manifests

README.md, api/v1/types.go, controllers/csm_controller.go, controllers/csm_controller_test.go, operatorconfig/moduleconfig/common/version-values.yaml, operatorconfig/moduleconfig/observability/v1.3.0/karavi-topology.yaml, pkg/modules/observability.go, pkg/modules/observability_test.go, pkg/modules/testdata/cr_powerscale_observability.yaml, pkg/utils/utils.go, samples/storage_csm_powerscale_v240.yaml, scripts/run-e2e-test.sh, tests/e2e/steps/step_common.go, tests/e2e/steps/steps_def.go, tests/e2e/testfiles/storage_csm_powerscale.yaml, tests/e2e/testfiles/storage_csm_powerscale_observability.yaml, tests/e2e/testfiles/values.yaml
add observability topology for PowerScale, UT, e2e and etc
| https://github.com/dell/csm/issues/488 |
Current coverage:
`[root@vpi6179 controllers]# go test ./... -coverprofile cover.out
ok      github.com/dell/csm-operator/controllers        0.591s  coverage: 88.5% of statements
[root@vpi6179 modules]# go test ./... -coverprofile cover.out
ok      github.com/dell/csm-operator/pkg/modules        0.105s  coverage: 88.9% of statements
`
`Running Suite: CSM Operator End-to-End Tests
============================================
Random Seed: 1664430799 - Will randomize all specs
Will …
=> add observability topology for PowerScale, UT, e2e and etc

.github/containerscan/allowedlist.yaml, controllers/csm_controller.go, controllers/csm_controller_test.go, operatorconfig/moduleconfig/observability/v1.3.0/karavi-metrics-powerscale.yaml, operatorconfig/moduleconfig/observability/v1.3.0/karavi-otel-collector.yaml, pkg/modules/observability.go, pkg/modules/observability_test.go, pkg/modules/testdata/cr_powerscale_observability.yaml, samples/storage_csm_powerscale_v240.yaml, tests/e2e/e2e_test.go, tests/e2e/steps/step_common.go, tests/e2e/testfiles/storage_csm_powerscale.yaml, tests/e2e/testfiles/storage_csm_powerscale_observability.yaml, tests/e2e/testfiles/values.yaml
Add observability metrics for PowerScale
| https://github.com/dell/csm/issues/488|
PASS
```
~/csm-operator/controllers# go test ./... -coverprofile cover.out
ok      github.com/dell/csm-operator/controllers        0.730s  coverage: 88.6% of statements
~/csm-operator/pkg/modules# go test ./... -coverprofile cover.out
ok      github.com/dell/csm-operator/pkg/modules        0.130s  coverage: 89.3% of statements
```
PASS
```
Tests:
--------------------------------------------------------------
1. TestCase: VolumeIoSuite
Started:   2022-10-18 23:15:17.4351608 -0400 -0400
Ended: …
```
=> Add observability metrics for PowerScale

.github/containerscan/allowedlist.yaml, controllers/csm_controller.go, controllers/csm_controller_test.go, operatorconfig/moduleconfig/observability/v1.3.0/karavi-metrics-powerscale.yaml, operatorconfig/moduleconfig/observability/v1.3.0/karavi-otel-collector.yaml, pkg/modules/observability.go, pkg/modules/observability_test.go, pkg/modules/testdata/cr_powerscale_observability.yaml, samples/storage_csm_powerscale_v220.yaml, samples/storage_csm_powerscale_v230.yaml, samples/storage_csm_powerscale_v240.yaml, tests/e2e/e2e_test.go, tests/e2e/steps/step_common.go, tests/e2e/testfiles/storage_csm_powerscale.yaml, tests/e2e/testfiles/storage_csm_powerscale_observability.yaml, tests/e2e/testfiles/values.yaml
- Removing the older method of checking owner reference as we have a new logic to check for owner reference
| https://github.com/dell/csm/issues/477|
We get owner reference from deployment resource of driver in new logic 
Dell-csm-operator and driver pods are up and running
=> Removing older ownerref

Makefile, controllers/csm_controller.go, controllers/csm_controller_test.go, operatorconfig/moduleconfig/observability/v1.3.0/karavi-metrics-powerscale.yaml, pkg/modules/observability.go, pkg/modules/observability_test.go, pkg/modules/testdata/cr_powerscale_observability.yaml, pkg/resources/deployment/deployment.go, pkg/utils/common.go, pkg/utils/utils.go, tests/e2e/steps/step_common.go, tests/e2e/steps/steps_def.go, tests/e2e/testfiles/storage_csm_powerscale_observability_auth.yaml, tests/e2e/testfiles/values.yaml
enable authorization for observability metrics-powerscale.
| https://github.com/dell/csm/issues/488|
```
~/csm-operator/controllers# go test ./... -coverprofile cover.out
ok      github.com/dell/csm-operator/controllers        0.884s  coverage: 89.0% of statements
~/csm-operator/pkg/modules# go test ./... -coverprofile cover.out
ok      github.com/dell/csm-operator/pkg/modules        0.153s  coverage: 89.3% of statements
```
Passed: enable both modules observability and authorization
output:
```
~/csm-operator/tests/e2e
Oct 23 09:55:31.811: INFO: The --provider flag is not set. …
```
=> enable authorization for observability metrics-powerscale

deploy/operator.yaml
This PR reverts some changes related to permissions for volumesnapshot related entities required for csi-powerflex.
|https://github.com/dell/csm/issues/529 |
Successful e2e
=> [bug-529]: Fix csi-powerflex installation

README.md, main.go, operatorconfig/driverconfig/common/k8s-1.25-values.yaml
Changes to add support for k8s 1.25
|  https://github.com/dell/csm/issues/478 |
- Sanity
- Jenkins job to install operator, then powerscale driver and create test pods.
[build.log](https://github.com/dell/csm-operator/files/9935986/build.log)
=> k8s 1.25 support

samples/observability/custom-cert.yaml, samples/observability/selfsigned-cert.yaml
Added sample certificates for Observability documentation
| https://github.com/dell/csm/issues/488 |
=> add sample certificates for Observability documentation

controllers/csm_controller.go, controllers/csm_controller_test.go, operatorconfig/moduleconfig/observability/v1.3.0/karavi-metrics-powerflex.yaml, pkg/modules/observability.go, pkg/modules/observability_test.go, pkg/modules/testdata/cr_powerflex_observability.yaml, pkg/utils/utils.go, samples/storage_csm_powerflex_v230.yaml, tests/e2e/testfiles/storage_csm_powerflex_observability_auth.yaml, tests/e2e/testfiles/values.yaml
enable authorization for observability metrics-powerflex:
- add authorization module to the sample files of PowerFlex;
- enable authorization for observability metrics-powerflex;
- copy secrets from csi driver namespace to observability namespace;
- add observability components control in oldStandAloneModuleCleanup;
- change Annotation content of previously-applied-configuration in oldStandAloneModuleCleanup;
- add related UT;
- add related e2e;
| https://github.com/dell/csm/issues/488|
```
~/csm-operator/controllers# go test ./... -coverprofile cover.out
ok …
```
=> enable authorization for observability metrics-powerflex

api/v1/types.go, config/crd/bases/storage.dell.com_containerstoragemodules.yaml, controllers/csm_controller.go, controllers/csm_controller_test.go, deploy/crds/storage.dell.com_containerstoragemodules.yaml, pkg/modules/authorization.go, pkg/modules/authorization_test.go, pkg/modules/testdata/cr_auth_proxy.yaml, pkg/utils/status.go, pkg/utils/utils.go, samples/authorization/csm_authorization_proxy_server.yaml, tests/e2e/testfiles/csm_authorization_proxy_server.yaml, tests/shared/crclient/client.go
PR to address a timing issue when creating Ingresses using the NGINX ingress controller. Ingresses are created only after the NGINX ingress controller deployment is running to ensure the `ingress-nginx-admission` webhook can validate Ingress definitions.
A `timed out waiting for the condition` is expected as we will only poll the status of the NGINX ingress controller deployment at 10 second intervals before reconciling again.
|https://github.com/dell/csm/issues/511 |
=> Update Authorization Ingresses

Dockerfile
Reverting UBI image back to 8.6 for consistency
| |
=> Reverting UBI back to 8.6

bundle/manifests/dell-csm-operator.clusterserviceversion.yaml, config/samples/storage_v1_csm_powerscale.yaml, operatorconfig/moduleconfig/common/version-values.yaml, pkg/modules/replication.go, samples/storage_csm_powerscale_v250.yaml, tests/e2e/testfiles/storage_csm_powerscale.yaml, tests/e2e/testfiles/storage_csm_powerscale_replica.yaml
bumping replication-controller image for csi-powerscale- v2.5.0
|https://github.com/dell/csm/issues/491 |
=> update rep-controller image

samples/storage_csm_powerflex_v230.yaml
This PR corrects Powerflex config map name in samples and test files
| https://github.com/dell/csm/issues/491 |
=> Correct Powerflex config map name in manifests

Dockerfile, Makefile, bundle.Dockerfile, bundle/manifests/dell-csm-operator.clusterserviceversion.yaml, config/install/kustomization.yaml, config/manager/kustomization.yaml, config/manifests/bases/dell-csm-operator.clusterserviceversion.yaml, deploy/olm/operator_community.yaml, deploy/operator.yaml, docker.mk, licenses/LICENSE
Bumps up the operator version to 1.1.0
Added license folder which was required for container scans during certification
Installed Powerscale driver v2.5.0 via csm-operator
=> Bump up operator version to 1.1.0

.github/containerscan/allowedlist.yaml, pkg/utils/status.go
Powerstore CSM object Fails on dell-csm-operator
Unit test failure will be fixed once https://github.com/dell/csm-operator/pull/158 this pr is merged.
| https://github.com/dell/csm/issues/613 |
=> Powerstore CSM object Fails on dell-csm-operator

config/samples/storage_v1_csm_powerstore.yaml, operatorconfig/driverconfig/powerstore/v2.4.0/controller.yaml, operatorconfig/driverconfig/powerstore/v2.5.0/controller.yaml, pkg/drivers/powerstore.go, samples/storage_csm_powerstore_v240.yaml, samples/storage_csm_powerstore_v250.yaml
Volume mount fails for NFS mounts for csi-powerstore deployed using csm-operator
|  https://github.com/dell/csm/issues/613 |
=> Volume mount fails for NFS mounts for csi-powerstore deployed using csm-operator

operatorconfig/moduleconfig/authorization/v1.6.0/policies.yaml
Updates the powermax-volume-create policy to allow zero quota.
|https://github.com/dell/csm/issues/654 |
Manually deployed Authorization and verified policies are expected.
=> [bug-654]: Add zero quota policy to powermax

operatorconfig/driverconfig/powerflex/v2.6.0/node.yaml, pkg/drivers/commonconfig.go, pkg/drivers/powerflex.go, samples/storage_csm_powerflex_v260.yaml
This pr adds the Support for Powerflex 2.6 features( ApproveSdc,RenameSdc) to the csm-operator
| https://github.com/dell/csm/issues/402 |
=> Add powerflex 2.6 features(ApproveSdc,RenameSdc) support to csm-operator

tests/config/driverconfig/powerflex/v2.6.0/node.yaml, tests/e2e/testfiles/storage_csm_powerflex.yaml
Minor changes to unit-test for powerflex -2.6
| https://github.com/dell/csm/issues/402 |
Unit-test :
--- PASS: TestCustom (22.46s)
--- PASS: TestCustom/TestAuthorizationServerReconcile (20.48s)
--- PASS: TestCustom/TestContentWatch (0.02s)
--- PASS: TestCustom/TestCsmFinalizerError (0.00s)
--- PASS: TestCustom/TestCsmPreCheckModuleError (0.00s)
--- PASS: TestCustom/TestCsmPreCheckModuleUnsupportedVersion (0.00s)
--- PASS: TestCustom/TestCsmPreCheckTypeError (0.00s)
--- PASS: TestCustom/TestCsmPreCheckVersionError (0.00s)
--- PASS: TestCustom/TestCsmUpgrade (0.17s)
--- PASS: …
=> Test variables added

README.md, main.go
This pr adds the changes to support mke 3.5.x for latest vxflexos driver.
| https://github.com/dell/csm/issues/699  |
=> add the changes to support mke 3.5.x for latest vxflexos.

config/samples/storage_v1_csm_powerstore.yaml, samples/storage_csm_powerstore_v240.yaml, samples/storage_csm_powerstore_v250.yaml, samples/storage_csm_powerstore_v260.yaml
Added the required comments for the authSecret field in the manifest file.
|https://github.com/dell/csm/issues/583|
-  Deployed the PowerStore driver via CSM-operator after the comment has been added.
=> Added comment to authSecret field in manifest

samples/storage_csm_powerflex_v240.yaml, samples/storage_csm_powerflex_v250.yaml, samples/storage_csm_powerflex_v260.yaml
1. Remove configmap creation from PowerFlex sample files to address defect.
2. Removed environment variables that were not configurable in sample files
| https://github.com/dell/csm/issues/713 |
1. For removal of configmap creation: Deleted driver installation, namespace (to ensure all configmaps were gone) and csm- 
operator. Reinstalled everything successfully with the configmap-less sample file. Confirmed that configmaps did not exist 
before doing a `kubectl create -f` on the sample file and that it did exist afterward. Repeated for all supported versions.
2. Removing environment variables : Deleted older driver installation (to ensure older csm-operator pods and driver pods are deleted). reinstalled the …
=> Remove configmap creation from PowerFlex sample files

tests/e2e/cleanup-e2e-test.sh, tests/e2e/testfiles/storage_csm_unity.yaml, tests/e2e/testfiles/values.yaml
- Add e2e test for csi-unity 
| https://github.com/dell/csm/issues/756 |
E2e tests are run and working fine as expected.
=> Add e2e test for csi-unity

pkg/drivers/common_test.go, pkg/drivers/unity_test.go, tests/config/driverconfig/badDriver/v2.4.0/bad.yaml, tests/config/driverconfig/badDriver/v2.4.0/controller.yaml, tests/config/driverconfig/badDriver/v2.4.0/csidriver.yaml, tests/config/driverconfig/badDriver/v2.4.0/driver-config-params.yaml, tests/config/driverconfig/badDriver/v2.4.0/upgrade-path.yaml, tests/config/driverconfig/badDriver/v2.5.0/bad.yaml, tests/config/driverconfig/badDriver/v2.5.0/controller.yaml, tests/config/driverconfig/badDriver/v2.5.0/csidriver.yaml, tests/config/driverconfig/badDriver/v2.5.0/driver-config-params.yaml, tests/config/driverconfig/badDriver/v2.5.0/upgrade-path.yaml, tests/shared/common.go
Some of the badDriver yaml files required for unit testing were removed in a recent PR. This PR adds them back in, and also adds a unit tests for unity to bring up the drivers package coverage to 95%.
| https://github.com/dell/csm/issues/756 |
Ran driver and controller unit tests to confirm tests pass and coverage is improved.
=> Add testing files and unit test coverage for unity

pkg/drivers/common_test.go, pkg/drivers/commonconfig.go
Fix a bug where the operator crashes if we try to set tolerations in node or controller. The issue is that we were treating the tolerationSeconds parameter as mandatory when it is in fact optional. By trying to pass it in by default, we ended up dereferencing <nil> if it hadn't been specified. Now, there is a check to see if the parameter is nil before dereferencing it.
- Ran driver unit tests and controller unit tests, confirmed passing and the additional code is covered.
- Successfully installed csi-powerscale with tolerations
=> fix toleration bug by making tolerationseconds optional

config/rbac/role.yaml, controllers/csm_controller.go, deploy/operator.yaml
This PR is for fixing the RBAC clusterroles updating correctly for node & adding delete permission to volumeattachments required for resiliency module.
| https://github.com/dell/csm/issues/739 |
=> Updated RBAC clusterrole fix

pkg/drivers/powerstore.go
Validation of authSecret field for Powerstore driver in csm-operator
|  https://github.com/dell/csm/issues/784 |
=> Validation of authSecret field for Powerstore driver in csm-operator

operatorconfig/driverconfig/powerstore/v2.7.0/node.yaml, operatorconfig/moduleconfig/resiliency/v1.6.0/container-powerstore-node.yaml
Updated kubelet config directory path for powerstore 2.7.0 config node.yaml & pods-path indentation fix.
| https://github.com/dell/csm/issues/739 |
=> Updated PowerStore kubelet config directory path

bundle/manifests/dell-csm-operator.clusterserviceversion.yaml, config/samples/storage_v1_csm_unity.yaml, controllers/csm_controller.go, operatorconfig/driverconfig/unity/v2.5.0/controller.yaml, operatorconfig/driverconfig/unity/v2.5.0/node.yaml, operatorconfig/driverconfig/unity/v2.6.0/controller.yaml, operatorconfig/driverconfig/unity/v2.6.0/node.yaml, operatorconfig/driverconfig/unity/v2.7.0/controller.yaml, operatorconfig/driverconfig/unity/v2.7.0/node.yaml, pkg/drivers/common_test.go, pkg/drivers/commonconfig.go, pkg/drivers/commonconfig_test.go, pkg/drivers/unity.go, pkg/drivers/unity_test.go, samples/storage_csm_unity_v250.yaml, samples/storage_csm_unity_v260.yaml, samples/storage_csm_unity_v270.yaml, scripts/common.bash, tests/config/driverconfig/unity/v2.6.0/controller.yaml, tests/config/driverconfig/unity/v2.6.0/node.yaml, tests/e2e/testfiles/storage_csm_unity.yaml
The PR adds validation to create certs only if we are providing  X509 certificates in our certs 
| https://github.com/dell/csm/issues/756 |
Sanity test:
CSI Unity Driver Installation when X_CSI_UNITY_SKIP_CERTIFICATE_VALIDATION is true
CSI Unity Driver Installation when X_CSI_UNITY_SKIP_CERTIFICATE_VALIDATION is false
=> Added validation for empty secrets for CSI Unity XT driver

pkg/modules/resiliency_test.go
Updated unit test for better coverage of resiliency file
| https://github.com/dell/csm/issues/739|
coverage is:
=> Resiliency-unit-test-Updated

operatorconfig/driverconfig/powerflex/v2.7.0/controller.yaml, samples/storage_csm_powerflex_v270.yaml
Extending sample file for supporting resiliency module
|https://github.com/dell/csm/issues/739 |
=> Extending sample file for supporting resiliency module

bundle/manifests/dell-csm-operator.clusterserviceversion.yaml, config/samples/storage_v1_csm_powerscale.yaml, operatorconfig/driverconfig/powerscale/v2.7.0/controller.yaml, operatorconfig/driverconfig/powerscale/v2.7.0/csidriver.yaml, pkg/drivers/common_test.go, pkg/drivers/commonconfig.go, pkg/drivers/commonconfig_test.go, pkg/drivers/powerscale.go, samples/storage_csm_powerscale_v270.yaml, tests/config/driverconfig/powerscale/v2.7.0/controller.yaml, tests/config/driverconfig/powerscale/v2.7.0/csidriver.yaml, tests/e2e/testfiles/storage_csm_powerscale.yaml, tests/shared/common.go
Added Storage Capacity Tracking Support for CSI-PowerScale in CSM-Operator.
|https://github.com/dell/csm/issues/743 |
- Installed driver using CSM-operator
- Ran Cert-CSI
=> Added Storage Capacity Tracking Support for CSI-PowerScale in CSM-Operator

controllers/csm_controller.go, pkg/utils/status.go
Fix for CSM object getting into failed state when we scale down deployments in csm-operator
|https://github.com/dell/csm/issues/816 |
Tested this specific scenario by scaling down and scaling up the deployment replicas. Also ran sanity jobs on k8s 1.27 and the results look good
Scaling down to 1
Scaling up to 2
=> Csm object fails during down scale

bundle/manifests/dell-csm-operator.clusterserviceversion.yaml, config/samples/storage_v1_csm_unity.yaml, operatorconfig/driverconfig/unity/v2.5.0/node.yaml, operatorconfig/driverconfig/unity/v2.6.0/node.yaml, operatorconfig/driverconfig/unity/v2.7.0/node.yaml, pkg/drivers/common_test.go, pkg/drivers/unity.go, samples/storage_csm_unity_v250.yaml, samples/storage_csm_unity_v260.yaml, samples/storage_csm_unity_v270.yaml, tests/config/driverconfig/unity/v2.6.0/controller.yaml, tests/config/driverconfig/unity/v2.6.0/node.yaml, tests/e2e/testfiles/storage_csm_unity.yaml
Remove test prefix from Unity namespace, name and authsecrets.
Sanity tests:
=> Remove test prefix from Unity namespace, name and authsecrets

tests/e2e/steps/step_common.go
e2e tests can't compile on latest changes made 
this removes the syntax issue 
```
Failed to compile e2e:
steps/step_common.go:16:2: "bytes" imported and not used
Ginkgo ran 1 suite in 24.260316404s
```
| |
=> fix test compile error

samples/storage_csm_powerstore_v260.yaml, samples/storage_csm_powerstore_v270.yaml
Enabled storage capacity tracking in Powerstore 2.6 and 2.7 samples
|https://github.com/dell/csm/issues/743 |
- Executed storage capacity tracking suite using cert-csi
=> CSI-PowerStore: Enabling Storage Capacity Tracking 

operatorconfig/driverconfig/powermax/v2.6.0/controller.yaml, operatorconfig/driverconfig/powermax/v2.6.0/node.yaml, operatorconfig/driverconfig/powermax/v2.7.0/node.yaml, operatorconfig/moduleconfig/csireverseproxy/v2.5.0/controller.yaml, samples/csireverseproxy/config.yaml, samples/storage_csm_powermax_v260.yaml
- Add missing v2.5.0 config for csireverseproxy
|https://github.com/dell/csm/issues/838|
=> Adds v2.5.0 config for csireverseproxy

controllers/csm_controller_test.go, pkg/resources/serviceaccount/serviceaccount.go
This PR has fix for secrets getting regenerated on `kubectl apply` of any driver manifest. 
1. Installed the operator followed by install of Unity driver. 
2. Make change to any of the field in driver manifest and apply the changes
3. Check the secrets. It should not get generated. 
Repeat step 2 couple of times and ensure that secrets are not getting regenerated.
=> Fix for secrets getting regenerated on apply of driver manifest

bundle/manifests/dell-csm-operator.clusterserviceversion.yaml, config/manifests/bases/dell-csm-operator.clusterserviceversion.yaml, controllers/csm_controller.go
This PR updates the annotations and the description in CSV
Installed operator v1.1.0 followed by install by previous version of PowerScale driver
Upgraded the operator to 1.2.0 followed by PowerScale driver upgrade
=> Update annotations for CSI Driver and description in CSV

tests/e2e/steps/steps_def.go
Scenario "Install PowerScale Driver(With Authorization)" consistently failed with err: failed to unmarshal token apiVersion: v1. Issue discovered with latest version of karavictl built from main. Karavictl is now returning YAML which breaks the JSON unmarshalling.
|https://github.com/dell/csm/issues/853|
- [X ] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [X ] Install PowerScale Driver(With Authorization) passes. Code is used in common step to setup token.
=> Step fails as Karavictl returns YAML instead of JSON

samples/storage_csm_powerflex_v270.yaml, samples/storage_csm_powerscale_v270.yaml, samples/storage_csm_powerstore_v270.yaml, samples/storage_csm_powerstore_v280.yaml
Add image label to sample configuration files for resiliency so that the users can customize the image to deploy resiliency with operator. Also added the extra args as per user's request.
|https://github.com/dell/csm/issues/898|
Deployed the driver with resiliency enabled in e2e test on a local Kubernetes setup. Modified the resiliency image to use different versions/tags and repos to verify that users can specify a different resiliency image.
=> Add resiliency image label and extra args in sample yaml files

config/rbac/role.yaml, controllers/csm_controller.go, controllers/csm_controller_test.go, deploy/operator.yaml, operatorconfig/moduleconfig/application-mobility/v0.3.0/app-mobility-controller-manager.yaml, operatorconfig/moduleconfig/application-mobility/v0.3.0/certificate.yaml, operatorconfig/moduleconfig/authorization/v1.6.0/cert-manager.yaml, operatorconfig/moduleconfig/common/cert-manager.yaml
Reverted webhook-server-cert designation to cert-manager-webhook-ca to maintain consistency between other installations.
=> reverted webhook-server-cert designation to cert-manager-webhook-ca

samples/storage_csm_powerscale_v270.yaml, samples/storage_csm_powerscale_v280.yaml, samples/storage_csm_powerstore_v270.yaml, samples/storage_csm_powerstore_v280.yaml
Remove the duplicated `arrayConnectivityPollRate` args in CR yaml files.
|https://github.com/dell/csm/issues/898 |
- [] I have maintained at least 90% code coverage
- [] I have added tests that prove my fix is effective or that my feature works
- [] I have maintained backward compatibility
Deployed the driver with resiliency enabled in e2e test on a local Kubernetes setup. Modified the resiliency image to use different versions/tags and repos to verify that users can specify a different resiliency image.
=> Remove resiliency duplicated extra args in sample yaml files

Dockerfile, bundle.Dockerfile
Update UBI image to ubi-micro with ubi9
| https://github.com/dell/csm/issues/922 |
1. Build the image and ensured that are no build errors
2. Did one round of sanity by installing the operator followed by Unity driver install. This scenario was tried in both OLM and non-OLM environments
=> Update base image from ubi-minimal to ubi9 micro image

config/rbac/role.yaml, controllers/csm_controller.go, controllers/csm_controller_test.go, deploy/operator.yaml, main.go, operatorconfig/moduleconfig/common/cert-manager/cert-manager.yaml, pkg/modules/commonconfig_test.go, pkg/modules/observability.go, pkg/utils/utils.go, samples/storage_csm_powerflex_v260.yaml, samples/storage_csm_powerflex_v270.yaml, samples/storage_csm_powerflex_v280.yaml, samples/storage_csm_powerscale_v260.yaml, samples/storage_csm_powerscale_v270.yaml, samples/storage_csm_powerscale_v280.yaml, tests/e2e/testfiles/authorization-templates/csm_authorization_proxy_server_no_cert.yaml, tests/e2e/testfiles/observability-cert.yaml, tests/e2e/testfiles/storage_csm_powerflex_observability.yaml, tests/e2e/testfiles/storage_csm_powerflex_observability_auth.yaml, tests/e2e/testfiles/storage_csm_powerscale_observability.yaml, tests/e2e/testfiles/storage_csm_powerscale_observability_auth.yaml, tests/e2e/testfiles/values.yaml
Added automatic cert-manager install into observability install and added support for installing cert-manager CRDs.
- Added code into utils.GetModuleComponentsObj() to read CRD definitions from yaml files
- Used helm dry-run option to help create the new cert-manager.yaml file and added crd definitions to it.
- Added necessary 
- Updated all PowerFlex and PowerScale sample files, in both `samples` and `tests/e2e/testfiles` to add cert-manager code into the observability block
- Utils.IsComponentEnabled(), utils.IsModuleComponentEnabled(), and utils.IsAuthorizationComponentEnabled() all do the same thing. The redundant functions were removed and utils.IsModuleComponentEnabled() is now used everywhere.
- Corresponding doc PR: https://github.com/dell/csm-docs/pull/737
List the GitHub issues …
=> Automate install of cert-manager for observability

scripts/csm-offline-bundle.sh
CSM offline bundle script to create the bundle for the CSM operator. This creates a tar of the latest images of the operator, drivers, and modules.
| https://github.com/dell/csm/issues/939 |
- Tested the script on the existing v1.2.0 branch of the operator to ensure that the images are pulled as expected using the podman builder tool.
=> csm offline bundle - create bundle

config/samples/storage_v1_csm_powerflex.yaml, operatorconfig/driverconfig/powerflex/v2.8.0/controller.yaml, pkg/drivers/powerflex.go, samples/storage_csm_powerflex_v280.yaml, tests/config/driverconfig/powerflex/v2.8.0/controller.yaml, tests/e2e/testfiles/storage_csm_powerflex.yaml, tests/e2e/testfiles/storage_csm_powerflex_alt_vals_1.yaml, tests/e2e/testfiles/storage_csm_powerflex_alt_vals_2.yaml, tests/e2e/testfiles/storage_csm_powerflex_alt_vals_3.yaml, tests/e2e/testfiles/storage_csm_powerflex_alt_vals_4.yaml, tests/e2e/testfiles/storage_csm_powerflex_alt_vals_5.yaml
Changes added for NFS support in PowerFlex.
| https://github.com/dell/csm/issues/763 |
controller pod with env vars set for driver:
```
driver:
Container ID:  containerd://b2939bxxxxxxxxxxxx
Image:         <local-artifactory>:5036/csi-vxflexos:vmain-latest
Image ID:      <local-artifactory>:5036/csi-vxflexos@sha256:c23420xxxxxxxxxxxx
Port:          <none>
Host Port:     <none>
Command:
/csi-vxflexos.sh
Args:
--leader-election
--array-config=/vxflexos-config/config
--driver-config-params=/vxflexos-config-params/driver-config-params.yaml
State:          Running
Started:      Mon, 07 …
```
=> powerflex: support added for NFS

.github/workflows/actions.yml, pkg/drivers/commonconfig.go
- Updated common config file
- Excluded rule G101 to avoid false positive "Potential Hardcoded credentials"
|https://github.com/dell/csm/issues/876 |
Tested using local csm operator runs and the results look good
**When storageCapacity flag is set to false**:
**When storageCapacity flag is set to true**:
=> Updated common config file as part of SCT feature

bundle/manifests/dell-csm-operator.clusterserviceversion.yaml, config/samples/storage_v1_csm_powerflex.yaml, operatorconfig/driverconfig/powerflex/v2.8.0/controller.yaml, operatorconfig/driverconfig/powerflex/v2.8.0/csidriver.yaml, pkg/drivers/commonconfig.go, pkg/drivers/powerflex.go, samples/storage_csm_powerflex_v280.yaml, tests/config/driverconfig/powerflex/v2.8.0/controller.yaml, tests/config/driverconfig/powerflex/v2.8.0/csidriver.yaml, tests/e2e/testfiles/storage_csm_powerflex.yaml
This PR adds addresses changes in csm-operator to support Storage Capacity Tracking feature for PowerFlex driver
| (https://github.com/dell/csm/issues/876) |
```
INFO 1. ScalingSuite {replicas: 2, volumes: 5, volumeSize: 8Gi}
INFO 2. CloneVolumeSuite {pods: 2, volumes: 1, volumeSize: 8Gi}
INFO 3. VolumeIoSuite {volumes: 2, volumeSize: 8Gi chains: 2-2}
INFO 4. SnapSuite {snapshots: 3, volumeSize; 8Gi}
INFO 5. ReplicationSuite {pods: 2, volumes: 5, volumeSize: 8Gi}
Does it look OK? (Y)es/(n)o
-> y
INFO Avg time of a run:   60.37s
INFO Avg time of a del:   13.81s
INFO Avg time of all:     79.24s
INFO …
```
=> Storage Capacity Tracking for CSI-Powerflex

Dockerfile, bundle.Dockerfile, config/samples/storage_v1_csm_powerflex.yaml, samples/storage_csm_powerflex_v280.yaml, tests/README.md
This PR fixes a broken link in /test/README.md. Also, it fixes the maxVxflexosVolumesPerNode default value
Updated UBI 9.2-13 image as well
| https://github.com/dell/csm/issues/885 |
Tested the link
UBI 9 image tested - Sanity
=> Fix prerequisites link in readme

controllers/csm_controller.go, operatorconfig/driverconfig/powermax/v2.6.0/controller.yaml, operatorconfig/driverconfig/powermax/v2.7.0/controller.yaml, operatorconfig/driverconfig/powermax/v2.8.0/controller.yaml, operatorconfig/moduleconfig/observability/v1.4.0/karavi-topology.yaml, operatorconfig/moduleconfig/observability/v1.5.0/karavi-metrics-powermax.yaml, operatorconfig/moduleconfig/observability/v1.5.0/karavi-topology.yaml, operatorconfig/moduleconfig/observability/v1.6.0/karavi-topology.yaml, pkg/modules/observability.go, pkg/modules/observability_test.go, pkg/modules/testdata/cr_powermax_observability.yaml, pkg/modules/testdata/cr_powermax_replica.yaml, samples/storage_csm_powermax_v260.yaml, samples/storage_csm_powermax_v270.yaml, tests/config/driverconfig/powermax/v2.8.0/controller.yaml, tests/e2e/cleanup-e2e-test.sh, tests/e2e/steps/step_common.go, tests/e2e/testfiles/powermax-templates/powermax-secret-template.yaml, tests/e2e/testfiles/powermax-templates/powermax-storageclass-template.yaml, tests/e2e/testfiles/storage_csm_powermax.yaml, tests/e2e/testfiles/storage_csm_powermax_observability.yaml, tests/e2e/testfiles/values.yaml
- Add Observability for CSI Powermax
- Add unit tests for powermax related changes in observability.
- 
|https://github.com/dell/csm/issues/908|
=> Adds obsv samples for CSI Powermax

config/samples/storage_v1_csm_powerflex.yaml, operatorconfig/driverconfig/powerflex/v2.8.0/controller.yaml, pkg/drivers/powerflex.go, samples/storage_csm_powerflex_v280.yaml, tests/config/driverconfig/powerflex/v2.8.0/controller.yaml, tests/e2e/testfiles/storage_csm_powerflex.yaml, tests/e2e/testfiles/storage_csm_powerflex_alt_vals_1.yaml, tests/e2e/testfiles/storage_csm_powerflex_alt_vals_2.yaml, tests/e2e/testfiles/storage_csm_powerflex_alt_vals_3.yaml, tests/e2e/testfiles/storage_csm_powerflex_alt_vals_4.yaml, tests/e2e/testfiles/storage_csm_powerflex_alt_vals_5.yaml
This pr removed the redundent parameter ExternalAccess for csi-powerflex from csm-operator.
| https://github.com/dell/csm/issues/763 |
```
driver:
Container ID:  containerd://16ced8c7a52d9883e9a146a316d56f9de612df36df897a3b46efceebc526dde8
Image:         amaas-eos-mw1.cec.lab.emc.com:5036/csi-vxflexos:vmain-latest
Image ID:      amaas-eos-mw1.cec.lab.emc.com:5036/csi-vxflexos@sha256:b69860968dcb74fe3bb05068a44c19adabbf4d766f19c07d6f17481f2fb1af56
Port:          <none>
Host Port:     <none>
Command:
/csi-vxflexos.sh
Args:
--leader-election
--array-config=/vxflexos-config/config …
```
=> remove the externalAccess param from csi-powerflex.

config/samples/storage_v1_csm_powerflex.yaml, operatorconfig/driverconfig/powerflex/v2.8.0/controller.yaml, pkg/drivers/powerflex.go, samples/storage_csm_powerflex_v280.yaml, tests/config/driverconfig/powerflex/v2.8.0/controller.yaml, tests/e2e/testfiles/storage_csm_powerflex.yaml, tests/e2e/testfiles/storage_csm_powerflex_alt_vals_1.yaml, tests/e2e/testfiles/storage_csm_powerflex_alt_vals_2.yaml, tests/e2e/testfiles/storage_csm_powerflex_alt_vals_3.yaml, tests/e2e/testfiles/storage_csm_powerflex_alt_vals_4.yaml, tests/e2e/testfiles/storage_csm_powerflex_alt_vals_5.yaml
This pr removed the redundent parameter nfAcls for csi-powerflex from csm-operator.
| https://github.com/dell/csm/issues/763  |
```driver:
Container ID:  containerd://e5fc74538227f6587bc6f61a30b28b4720f1567bd46ee5618962d5acefd05c4b
Image:         xxxx/csi-vxflexos:remove-nfsAcls
Image ID:      xxxxx/csi-vxflexos@sha256:7facbaeabd345003cb167185e510dc8cf5aa1b8361c91f645a97e3a7a1736ba3
Port:          <none>
Host Port:     <none>
Command:
/csi-vxflexos.sh
Args:
--leader-election
--array-config=/vxflexos-config/config
--driver-config-params=/vxflexos-config-params/driver-config-params.ya …
```
=> remove the nfsAcls param from csi-powerflex.

config/rbac/role.yaml, controllers/csm_controller.go, controllers/csm_controller_test.go, operatorconfig/moduleconfig/application-mobility/v0.3.0/app-mobility-controller-manager-metrics-service.yaml, operatorconfig/moduleconfig/application-mobility/v0.3.0/app-mobility-controller-manager.yaml, operatorconfig/moduleconfig/application-mobility/v0.3.0/cleanupcrds.yaml, operatorconfig/moduleconfig/application-mobility/v0.3.0/node-agent.yaml, operatorconfig/moduleconfig/application-mobility/v0.3.0/velero-deployment.yaml, operatorconfig/moduleconfig/application-mobility/v0.3.0/velero-secret.yaml, operatorconfig/moduleconfig/application-mobility/v0.3.0/velero-volumesnapshotlocation.yaml, pkg/modules/application_mobility.go, pkg/modules/testdata/cr_application_mobility.yaml, pkg/utils/status.go, samples/application-mobility/csm_application_mobility_v030.yaml, samples/application-mobility/csm_application_mobility_with_driver.yaml, tests/e2e/testfiles/csm_application_mobility_cert_manager.yaml, tests/e2e/testfiles/csm_application_mobility_controller_diff_env.yaml, tests/e2e/testfiles/csm_application_mobility_test_velero.yaml, tests/e2e/testfiles/csm_application_mobility_vanilla.yaml, tests/e2e/testfiles/csm_application_mobility_velero_diff_env.yaml
This PR updates and fixes deployment of AM for Operator: 
1. Remove VELERO_NAMESPACE parameter 
2. Edit controllers.go to allow for AM and driver deployment from single yaml
- getDriverConfig now returns nil when no driver is specified instead of error 
- removeDriver and syncCSM will now check getDriverConfig return before returning nil for cases where there is no driver Before:
```
1.6946133137718441e+09  ERROR   Reconciler error        {"controller": "containerstoragemodule", "controllerGroup": "storage.dell.com", "controllerKind": "ContainerStorageModule", "containerStorageModule": {"name":"application-mobility","namespace":"application-mobility"}, "namespace": "application-mobility", "name": "application-mobility", "reconcileID": "a366e5d9-8d63-454c-8e01-c83f45f88195", "error": …
```
=> AM deployment fixes and updates 

.github/containerscan/allowedlist.yaml, config/samples/storage_v1_csm_powerstore.yaml, samples/storage_csm_powerstore_v260.yaml, samples/storage_csm_powerstore_v270.yaml, samples/storage_csm_powerstore_v280.yaml
Added `volume-name-prefix` argument in `provisioner` sidecar for updating volume prefix 
| https://github.com/dell/csm/issues/989 |
=> Powerstore: Added configurable volume prefix option

config/samples/storage_v1_csm_powerflex.yaml, samples/storage_csm_powerflex_v260.yaml, samples/storage_csm_powerflex_v270.yaml, samples/storage_csm_powerflex_v280.yaml
Added Volume Prefix support for Powerflex
| https://github.com/dell/csm/issues/989
Updated the volume prefix in sample yaml, installed the driver, created volumes. The new prefix "eg. kshitija" was getting updated.
=> Added Volume name Prefix support for Powerflex

controllers/csm_controller.go
Discovered a bug during testing where AM cert-manager.enabled field was being ignored and always installed. 
In this CR:  
```
- name: cert-manager
enabled: false
```
we can see that cert-manager is still being deployed anyway:  
```
[root@master-1-CMyNgvaXZTEw3 csm-operator]# kubectl get pods -n test-vxflexos
NAME                                                       READY   STATUS    RESTARTS   AGE
application-mobility-controller-manager-57d8c65d74-57xkf   2/2     Running   0          22m
application-mobility-controller-manager-57d8c65d74-l2gch   2/2     Running   0          22m
application-mobility-node-agent-7ssv5                      1/1     Running   0          22m
application-mobility-node-agent-8bdd9                      1/1     Running   0          22m …
```
=> fix CM.enabled flag for AM

controllers/csm_controller.go
Adding CSMVersion to annotation as a metadata that can be pulled and displayed in UI
current CSMVersion : V1.8.0
| |
Ran e2e test for powerscale 
--------------------------------------------------------------
[2023-10-16 16:36:29]  INFO Avg time of a run:   244.79s
[2023-10-16 16:36:29]  INFO Avg time of a del:   12.01s
[2023-10-16 16:36:29]  INFO Avg time of all:     260.38s
[2023-10-16 16:36:29]  INFO During this run 100.0% of suites succeeded
Oct 16 16:36:29.152: INFO: Running /bin/bash [check_parameters.sh testfiles/powerscale_health_monitor_values.csv dell powerscale]
6 occurences of external-health-monitor with value  found in controller
1 occurences of X_CSI_HEALTH_MONITOR_ENABLED with value true …
=> Adding CSMVersion

config/samples/storage_v1_csm_powermax.yaml, samples/storage_csm_powermax_v260.yaml, samples/storage_csm_powermax_v270.yaml, samples/storage_csm_powermax_v280.yaml
Added volume name prefix for Powermax driver .
| https://github.com/dell/csm/issues/989|
Executed cert-csi tests .
=> Adding volume Prefix for PowerMax

deploy/operator.yaml
Increase resource limits to fix `OOMKilled` error. 
| https://github.com/dell/csm/issues/982 |
=> Increase resource limits

controllers/csm_controller.go, controllers/csm_controller_test.go
This PR fixes an issue I found while working on AM E2E tests for Operator
Issue:
You cannot "disable" AM module from CR. If we flip this value from true to false:
```  modules:
- name: application-mobility
enabled: false
```
The AM pods remain 
=> fix am disable

bundle/manifests/dell-csm-operator.clusterserviceversion.yaml, config/rbac/role.yaml, controllers/acc_controller.go, deploy/operator.yaml, operatorconfig/clientconfig/apexconnectivityclient/v0.1.0/statefulset.yaml, tests/config/clientconfig/apex/v0.1.0/statefulset.yaml
[NOTE: this PR is for deploy-dcm-client, not main]
When deploying operator, the following ApexConnectivityClient-related error would show up in the operator logs and the pod would eventually go into a failed state: 
```
W1025 17:11:42.483744       1 reflector.go:533] pkg/mod/k8s.io/client-go@v0.27.2/tools/cache/reflector.go:231: failed to list *v1.ApexConnectivityClient: apexconnectivityclients.storage.dell.com is forbidden: User "system:serviceaccount:dell-csm-operator:dell-csm-operator-manager-service-account" cannot list resource "apexconnectivityclients" in API group "storage.dell.com" at the cluster scope
E1025 17:11:42.483773       1 reflector.go:148] pkg/mod/k8s.io/client-go@v0.27.2/tools/cache/reflector.go:231: Failed to watch *v1.ApexConnectivityClient: failed to list …
```
=> Fix serviceaccount error for ApexConnectivityClient

.github/workflows/actions.yml, Dockerfile, Makefile, bundle.Dockerfile
Use common base image
|  https://github.com/dell/csm/issues/1031 |
=> Use common base image

operatorconfig/driverconfig/powerflex/v2.9.0/node.yaml
Adding noderoot mount path to access root directory of the host from the node pod. We need this to run query_mdm command from the node pod on the worker host when driver calls the goscaleio call DrvCfgQuerySystems to fetch all the system ID's configured.
| https://github.com/dell/csm/issues/1020 |
=> PowerFlex: Adding noderoot mount path

operatorconfig/driverconfig/common/default.yaml, operatorconfig/driverconfig/common/k8s-1.24-values.yaml, operatorconfig/driverconfig/common/k8s-1.25-values.yaml, operatorconfig/driverconfig/common/k8s-1.26-values.yaml, operatorconfig/driverconfig/common/k8s-1.27-values.yaml, operatorconfig/driverconfig/common/k8s-1.28-values.yaml, operatorconfig/driverconfig/powerflex/v2.9.0/node.yaml, operatorconfig/driverconfig/powerstore/v2.9.0/node.yaml, tests/config/driverconfig/powerflex/v2.9.0/node.yaml, tests/config/driverconfig/powerstore/v2.9.0/node.yaml
Downgrade csi-node-driver-registrar to v2.9.1 due to the pull issue of `v2.9.2` image. Refer to : https://github.com/kubernetes-csi/node-driver-registrar/issues/359
| https://github.com/dell/csm/issues/1012 |
=> Downgrade csi-node-driver-registrar to v2.9.1

samples/storage_csm_powermax_v270.yaml, tests/config/driverconfig/powermax/v2.9.0/controller.yaml
Removes param that enables an unsupported feature in some CSI Powermax versions/samples.
|https://github.com/dell/csm/issues/983 |
=> Removes storageCapacity from unsupported CSI PMAX versions

operatorconfig/driverconfig/powermax/v2.9.0/node.yaml, tests/config/driverconfig/powermax/v2.9.0/node.yaml
Downgrade csi-node-driver-registrar to v2.9.1 due to the pull issue of `v2.9.2` image. Refer to : https://github.com/kubernetes-csi/node-driver-registrar/issues/359
| https://github.com/dell/csm/issues/1012 |
=> Powermax csi-node-driver-registrar downgrade 

pkg/drivers/powerflex.go
Fix variable name in Node for CSI Health Monitor for previous PR https://github.com/dell/csm-operator/pull/414
| https://github.com/dell/csm/issues/1058
Executed cert-csi and unit test
Node pod logs:
=> Fix variable name in Node for CSI Health Monitor

README.md, config/samples/storage_v1_csm_powerflex.yaml, config/samples/storage_v1_csm_powerscale.yaml, config/samples/storage_v1_csm_unity.yaml, samples/storage_csm_unity_v290.yaml
Changes done that are required for releasing v1.9.0
| https://github.com/dell/csm/issues/1012 |
=> Updating changes identified during release activity

config/rbac/role.yaml, controllers/csm_controller.go, deploy/operator.yaml
A bug was introduced last week that impacts AM (and possibly PowerFlex driver) deployment:
```
2024-01-03T14:07:38Z    ERROR   Reconciler error        {"controller": "containerstoragemodule", "controllerGroup": "storage.dell.com", "controllerKind": "ContainerStorageModule", "ContainerStorageModule": {"name":"vxflexos-app-mobility","namespace":"vxflexos"}, "namespace": "vxflexos", "name": "vxflexos-app-mobility", "reconcileID": "0cf852a6-5564-472b-a11e-32b13f3b72cd", "error": "failed to deploy application mobility: unable to reconcile Application Mobility controller Manager: clusterroles.rbac.authorization.k8s.io \"vxflexos-manager-role\" is forbidden: user \"system:serviceaccount:dell-csm-operator:dell-csm-operator-manager-service-account\" (groups=[\"system:serviceaccounts\" …
```
=> fix AM deployment bug

controllers/acc_controller_test.go, operatorconfig/clientconfig/apexconnectivityclient/v1.0.0/statefulset.yaml, samples/connectivity_client_v100.yaml, tests/config/clientconfig/apex/v1.0.0/statefulset.yaml, tests/e2e/testfiles/connectivity_client.yaml
Change the default namespace to dell-connectivity-client to match the documentation.
|[1029](https://github.com/dell/csm/issues/1029)|
=> Change namespace name to match documentation.

pkg/modules/authorization.go, pkg/modules/authorization_test.go, pkg/modules/testdata/cr_powerscale_auth_validate_cert.yaml
Updates the karavi-authorization-proxy container INSECURE env with the value of the SKIP CERTIFICATE VALIDATION env in the CR.
If `SKIP_CERTIFICATE_VALIDATION` is true, we keep the default value in `operatorconfig/moduleconfig/authorization/<release>/container.yaml`. If it's false, we set the env value to false.
|https://github.com/dell/csm/issues/1120 |
New unit test and manual installation.
=> [bug-1120]: Update Authorization sidecar to use insecure flag

bundle/manifests/dell-csm-operator.clusterserviceversion.yaml, bundle/metadata/annotations.yaml, config/samples/kustomization.yaml, config/samples/storage_v1_csm_connectivity_client.yaml
Final manifest update for posting activities of CSM Operator v1.4.1
| https://github.com/dell/csm/issues/1109 |
make bundle output:
=> Final manifest update for posting activities of CSM Operator v1.4.1

controllers/csm_controller.go, operatorconfig/moduleconfig/observability/v1.5.0/karavi-metrics-powerflex.yaml, operatorconfig/moduleconfig/observability/v1.5.0/karavi-metrics-powermax.yaml, operatorconfig/moduleconfig/observability/v1.5.0/karavi-metrics-powerscale.yaml, operatorconfig/moduleconfig/observability/v1.5.0/karavi-otel-collector.yaml, operatorconfig/moduleconfig/observability/v1.5.0/karavi-topology.yaml, operatorconfig/moduleconfig/observability/v1.6.0/karavi-metrics-powerflex.yaml, operatorconfig/moduleconfig/observability/v1.6.0/karavi-metrics-powermax.yaml, operatorconfig/moduleconfig/observability/v1.6.0/karavi-metrics-powerscale.yaml, operatorconfig/moduleconfig/observability/v1.6.0/karavi-otel-collector.yaml, operatorconfig/moduleconfig/observability/v1.6.0/karavi-topology.yaml, operatorconfig/moduleconfig/observability/v1.7.0/karavi-metrics-powerflex.yaml, operatorconfig/moduleconfig/observability/v1.7.0/karavi-metrics-powermax.yaml, operatorconfig/moduleconfig/observability/v1.7.0/karavi-metrics-powerscale.yaml, operatorconfig/moduleconfig/observability/v1.7.0/karavi-otel-collector.yaml, operatorconfig/moduleconfig/observability/v1.7.0/karavi-topology.yaml, pkg/modules/observability.go, pkg/utils/status.go
This PR makes a few adjustments to fix rare cases where csm status was not the correct:
1. Add getDeploymentStatus to calculateState, to prevent cases where an old failed status would overwrite the more recent correct status. I still left the current gds commented in as it looks like we plan to re-use that method at some point in the future
2. GetDaemonsetStatus will now use its own counter of running pods to determine available pods. This prevents a rare (1/1000 runs) issue where ds.Status.NumberAvailable was not updated in time, resulting in the CSM being marked as failed even though the operator saw there were 2 running pods
3. CSM namespace label has been added to obs. This is because the pod namespace might not be the same namespace as the csm object; resulting in the csm status …
=> Fix for controller race, daemon status, and obs namespace 

.github/workflows/actions.yml, controllers/csm_controller.go, operatorconfig/moduleconfig/authorization/v1.7.0/deployment.yaml, operatorconfig/moduleconfig/authorization/v1.7.0/nginx-ingress-controller.yaml, operatorconfig/moduleconfig/authorization/v1.8.0/deployment.yaml, operatorconfig/moduleconfig/authorization/v1.8.0/nginx-ingress-controller.yaml, operatorconfig/moduleconfig/authorization/v1.9.0/deployment.yaml, operatorconfig/moduleconfig/authorization/v1.9.0/nginx-ingress-controller.yaml, operatorconfig/moduleconfig/authorization/v1.9.1/deployment.yaml, operatorconfig/moduleconfig/authorization/v1.9.1/nginx-ingress-controller.yaml, pkg/modules/application_mobility.go, pkg/modules/authorization.go, pkg/modules/commonconfig.go, pkg/utils/status.go
Currently, the authorization proxy server status is always failed in csm-operator. This is for a couple reasons:
1) We are attempting to calculate the status of the daemonset, but since auth proxy has no daemonset, it always fails. To fix this, the daemonset is no longer considered when checking the auth proxy deployment.
2) Beyond that, the handleDeploymentUpdate function is now looking for a csm label on the deployment objects. If it doesn't find it, the handler exits without doing anything else. To fix this, labels were added to all of the auth proxy deployment objects.
| https://github.com/dell/csm/issues/1143 |
Please describe the tests that you ran to verify your changes. Please also list any relevant …
=> Auth proxy status fix

bundle/manifests/dell-csm-operator.clusterserviceversion.yaml, config/samples/storage_v1_csm_powermax.yaml
Update final manifests
| https://github.com/dell/csm/issues/1136 |
=> Update final manifests

operatorconfig/moduleconfig/authorization/v1.10.0/deployment.yaml, operatorconfig/moduleconfig/authorization/v1.10.0/nginx-ingress-controller.yaml
In the v1.4.2 patch release, labels were added to the config files for authorization so that we could process them in the csm status calculation logic. However, these labels were not in the 1.10 config files -- this PR adds them.
| https://github.com/dell/csm/issues/1091 |
Successfully installed auth proxy:
```
[root@master-1-Zaglt7mQUY8Wg e2e]# kubectl get pods -A
NAMESPACE           NAME                                                      READY   STATUS    RESTARTS      AGE
authorization       authorization-ingress-nginx-controller-7686cb6886-bvzkp   1/1     Running   0             48s
authorization       cert-manager-765754f9cd-z5knk                             1/1     Running   0             48s …
```
=> Update authorization 1.10 files to work with status logic

operatorconfig/driverconfig/powerflex/v2.10.0/node.yaml, operatorconfig/driverconfig/powerflex/v2.8.0/node.yaml, operatorconfig/driverconfig/powerflex/v2.9.0/node.yaml, operatorconfig/driverconfig/powerflex/v2.9.1/node.yaml
Mapping directory to sdc container from host
|https://github.com/dell/csm/issues/1152|
=> Mapping directory to sdc container from host

operatorconfig/driverconfig/powerflex/v2.9.2/controller.yaml, operatorconfig/driverconfig/powerflex/v2.9.2/csidriver.yaml, operatorconfig/driverconfig/powerflex/v2.9.2/driver-config-params.yaml, operatorconfig/driverconfig/powerflex/v2.9.2/node.yaml, operatorconfig/driverconfig/powerflex/v2.9.2/upgrade-path.yaml, samples/storage_csm_powerflex_v292.yaml
Added v2.9.2 configs for PowerFlex driver. The Configs contains the fix for sdc container failing to detecting the existing installation of sdc.
| https://github.com/dell/csm/issues/1152 |
make controller-unit-test
make driver-unit-test
make module-unit-test
=> Add v2.9.2 configs for PowerFlex driver

operatorconfig/driverconfig/common/k8s-1.24-values.yaml, operatorconfig/driverconfig/common/k8s-1.25-values.yaml, operatorconfig/driverconfig/common/k8s-1.26-values.yaml
This PR reverts the changes done to remove 1.21-1.26 k8s files to support n-2 and n-1 drivers
| https://github.com/dell/csm/issues/1091 |
Installation of csm-operator followed by 2.8.0 version of Unity driver
=> Adding back k8s versions file to support n-2 driver

Makefile
This PR fixes make build commands to build csm-operator image.
| https://github.com/dell/csm/issues/1091 |
make podman-build passed:
make docker-build passed:
make bundle passed:
=> Fix make build commands

controllers/csm_controller.go, pkg/utils/status.go
Work by @JacobGros . Basically, we fixed two minor bugs with csm status field:
1) When we detected a failed status for a csm object, we weren't necessarily doing anything about it. Now, we requeue the reconciler if we detect a failed state.
2) When we discover a new Succeeded state through SyncCSM, we were updating our local instance object but not writing that update anywhere. Now, we are writing the update back to the cluster by calling UpdateStatus in the HandleSuccess function.
| |
Installed AM 200 times back-to-back and confirmed state was always succeeded.
=> Fix intermittent app-mobility status error

operatorconfig/moduleconfig/common/version-values.yaml
Found a small defect while running e2e tests -- there was no entry for powerflex v2.9.2 in version-values.yaml, so I added one.
| https://github.com/dell/csm/issues/1164 |
Running e2e tests
=> Add PFlex v2.9.2 to version-values.yaml

bundle/manifests/dell-csm-operator.clusterserviceversion.yaml, config/samples/storage_v1_csm_connectivity_client.yaml, operatorconfig/clientconfig/apexconnectivityclient/v1.0.0/statefulset.yaml, samples/connectivity_client_v100.yaml, tests/config/clientconfig/apex/v1.0.0/statefulset.yaml
This PR consists of three items:
1. Restrict the access of the kube-proxy port to only connections within the client pod.
2. Update cert-persister version to the latest build and what we are testing now. 
3. Set image pull policy to reduce image downloads.
|[1029](https://github.com/dell/csm/issues/1029) |
- [XI have verified that new and existing unit tests pass locally with my changes
1. Deployed the client and validated that the access to the proxy from outside the pod, within the cluster is blocked. The service is not exported outside the cluster.
2. Onboarded the cluster and validated that the discovery of the cluster …
=> Restrict access to the kube-proxy to local pod connections only

operatorconfig/driverconfig/powermax/v2.10.0/node.yaml, operatorconfig/driverconfig/powermax/v2.8.0/node.yaml, operatorconfig/driverconfig/powermax/v2.9.0/node.yaml, operatorconfig/driverconfig/powermax/v2.9.1/node.yaml
Adding the parameter mountPropagation under volumemounts for Powermax node template.
|https://github.com/dell/csm/issues/1238 |
=> Updating mount param for PowerMax

.github/containerscan/allowedlist.yaml, operatorconfig/driverconfig/powerflex/v2.10.0/controller.yaml, operatorconfig/driverconfig/powerflex/v2.10.0/node.yaml, operatorconfig/driverconfig/powermax/v2.10.0/controller.yaml, operatorconfig/driverconfig/powermax/v2.10.0/node.yaml, operatorconfig/driverconfig/powerscale/v2.10.0/controller.yaml, operatorconfig/driverconfig/powerscale/v2.10.0/node.yaml, operatorconfig/driverconfig/powerstore/v2.10.0/controller.yaml, operatorconfig/driverconfig/powerstore/v2.10.0/node.yaml, operatorconfig/driverconfig/unity/v2.10.0/controller.yaml, operatorconfig/driverconfig/unity/v2.10.0/node.yaml
Make the default container to driver so it is easier to capture log and consistent with Helm Charts
| |
This hasn't been tested with the Operator ; the label is present in Helm Chart since several months : https://github.com/dell/helm-charts/blame/905c3951da497421276b54540a092712dc66b2b1/charts/csi-vxflexos/templates/controller.yaml#L171
Please share the protocol to try it out if any.
=> Set default container to driver

operatorconfig/moduleconfig/application-mobility/v1.0.0/velero-backupstoragelocation.yaml, operatorconfig/moduleconfig/application-mobility/v1.0.1/velero-backupstoragelocation.yaml, operatorconfig/moduleconfig/application-mobility/v1.0.2/velero-backupstoragelocation.yaml, pkg/modules/application_mobility.go
Add cacert parameter  for application mobility so user can setup velero BSL with cacert.
Feature is about parameter in custom resource, so test refer deploy CSM resource.
=> Add bucket cacert for application mobility

config/samples/storage_v1_csm_unity.yaml, operatorconfig/driverconfig/unity/v2.11.0/controller.yaml, operatorconfig/driverconfig/unity/v2.11.0/csidriver.yaml, operatorconfig/driverconfig/unity/v2.11.0/driver-config-params.yaml, operatorconfig/driverconfig/unity/v2.11.0/node.yaml, operatorconfig/driverconfig/unity/v2.11.0/upgrade-path.yaml, pkg/drivers/unity.go, samples/storage_csm_unity_v2110.yaml
This PR adds `allowedNetworks`  parameter to CSM CR when Unity is being installed. This enables the user to select which networks should be used for node <-> array communication.
| https://github.com/dell/csm/issues/1222|
- Manually tested installation with the new fieid in `envs` section of CR, and without new field to make sure no regression happend.
- Ran unit tests.
=> feat: allowedNetworks added to unity

.github/workflows/actions.yml, .github/workflows/linters.yaml, .golangci.yaml, controllers/acc_controller.go
Update GitHub Actions
| https://github.com/dell/csm/issues/1221 |
=> Update GitHub Actions

pkg/modules/application_mobility_test.go, pkg/modules/authorization_test.go, pkg/modules/observability_test.go, pkg/modules/replication_test.go, pkg/modules/resiliency_test.go, pkg/modules/reverseproxy_test.go
Update linter to v5. Fix new linter errors.
| https://github.com/dell/csm/issues/1291|
=> Fix linter errors

tests/e2e/steps/steps_def.go, tests/e2e/testfiles/authorization-templates/csm_authorization_proxy_server_n_minus_1.yaml, tests/e2e/testfiles/powerflex-templates/powerflex-secret-template.yaml, tests/e2e/testfiles/storage_csm_powerflex_auth_driver_only_upgrade.yaml, tests/e2e/testfiles/values.yaml
Added E2E Tests Scenarios for Authorization upgrade
| https://github.com/dell/csm/issues/1277
- Executed E2E test for upgrading Authorization proxy server from v1.9.1 to v1.10.0
- Executed E2E test for upgrading Authorization sidecar v1.9.1 to v1.10.0
=> Added E2E Tests Scenarios for Authorization upgrade

api/v1/types.go, config/crd/bases/storage.dell.com_apexconnectivityclients.yaml, config/crd/bases/storage.dell.com_containerstoragemodules.yaml, deploy/crds/storage.dell.com.crds.all.yaml, operatorconfig/moduleconfig/authorization/v2.0.0-alpha/deployment.yaml, pkg/modules/authorization.go, pkg/modules/testdata/cr_auth_proxy.yaml, pkg/modules/testdata/cr_auth_proxy_no_redis.yaml, samples/authorization/csm_authorization_proxy_server_v200-alpha.yaml
PR for adding Vault Role, which is required as an argument for the storage service for authorization
|https://github.com/dell/csm/issues/1281|
=> Adding Vault Role for Authorization

operatorconfig/moduleconfig/authorization/v2.0.0-alpha/deployment.yaml
Add login username and password to rediscommander web portal so that it's not exposed to anyone on the cluster.
| https://github.com/dell/csm/issues/1281|
Deployed rediscommander on k8s cluster with operator and manually tested.
=> Add username and password to rediscommander

controllers/csm_controller.go, tests/e2e/go.mod
Cert-manager reconciliation in authorizationReconcile was happening after authorization proxy reconcile. This was looking for cert-manager to be present causing it to fail and exit and never invoke cert manager reconcile (which was actually install cert-manager CRDs if not already present and requested)
Solution : move the code that does cert-manager reconciliation prior to the auth proxy reconcile. 
Recent changes to e2e tests probably left a stale entry, causing docker builds to fail. That is also fixed in this PR. 
https://github.com/dell/csm/issues/1281
|https://github.com/dell/csm/issues/1281 |
=> Fix cert-manager deployment, go mod updates

operatorconfig/moduleconfig/authorization/v2.0.0-alpha/policies.yaml
Add missing snapshot create policy for Authorization.
=> Add authorization snapshot policies

README.md, bundle.Dockerfile, bundle/manifests/dell-csm-operator.clusterserviceversion.yaml, bundle/metadata/annotations.yaml
Generated final manifests for the patch release
| https://github.com/dell/csm/issues/1284|
=> Updated final manifests

operatorconfig/moduleconfig/authorization/v2.0.0-alpha/deployment.yaml
Sentinel pod deployment occasionally cycles through all redis pods even before they come up and then fails. 
Adding retry logic in sentinel deployment (init container) to keep checking for redis pods with a delay of 30s if all redis pods have been checked and none of them are ready. 
This is not consistently reproducible and it depends on the particular environment when this manifests. The retry logic added should help. 
| https://github.com/dell/csm/issues/1281|
| |
=> Added sentinel retry logic

operatorconfig/clientconfig/apexconnectivityclient/v1.0.0/brownfield-onboard.yaml, pkg/utils/utils.go
When the DN client is deployed through ApexConnectivityClient CR, the csm-operator looks for the existing CSM objects and the operator adds the required roles(similar to the one for dell-csm namespace) for the namespaces where the csm object resides.
This PR: Added a new function that identifies the namespaces having csm objects and returns it. Also added a new yaml manifest file that specifies the Role/Rolebinding rules.
=> Added function to get the csm namespaces from the cluster.

api/v1/types.go, config/crd/bases/storage.dell.com_apexconnectivityclients.yaml, config/crd/bases/storage.dell.com_containerstoragemodules.yaml, controllers/csm_controller.go, controllers/csm_controller_test.go, deploy/crds/storage.dell.com.crds.all.yaml, pkg/modules/authorization.go, pkg/modules/authorization_test.go, pkg/modules/testdata/cr_auth_proxy.yaml, pkg/modules/testdata/cr_auth_proxy_certs.yaml, pkg/modules/testdata/cr_auth_proxy_certs_missing_key.yaml, pkg/modules/testdata/cr_auth_proxy_no_redis.yaml, samples/authorization/csm_authorization_proxy_server_v200-alpha.yaml, tests/e2e/testfiles/authorization-templates/csm_authorization_proxy_server.yaml, tests/e2e/testfiles/authorization-templates/csm_authorization_proxy_server_alt_ns.yaml, tests/e2e/testfiles/authorization-templates/csm_authorization_proxy_server_default_redis.yaml, tests/e2e/testfiles/authorization-templates/csm_authorization_proxy_server_ocp.yaml
1. Discover OpenShift setup instead of providing whether it is OpenShift or not in deployment configuration.
2. Add Storage poll interval in deployment yaml for ease of configuration!
```
2024-06-05T15:48:48.488-0400    INFO    utils/utils.go:748      Creating a new Object   {"Name:": "csipowermax-reverseproxy", "Kind:": "Deployment"}
--- PASS: TestReverseProxyServer (0.07s)
--- PASS: TestReverseProxyServer/fail_-_authorization_module_not_found (0.00s)
--- PASS: TestReverseProxyServer/success_-_deleting (0.02s)
--- PASS: …
```
=> Remove OpenShift parameter from config and discover it on runtime

controllers/acc_controller.go, controllers/acc_controller_test.go, controllers/csm_controller.go, pkg/utils/utils.go
When the DN client is deployed through ApexConnectivityClient CR, the csm-operator looks for the existing CSM objects as part of client reconciliation and the operator adds the required roles(similar to the one for dell-csm namespace) for the namespaces where the csm object resides.
When the cluster is already on-boarded to ANK8s and csm is directly deployed on the cluster, as part of csm-reconciliation, the roles are created to the new namespace where csm id deployed
=> changes to support brownfield onboarding to ANK8s

api/v1/types.go, config/crd/bases/storage.dell.com_apexconnectivityclients.yaml, config/crd/bases/storage.dell.com_containerstoragemodules.yaml, deploy/crds/storage.dell.com.crds.all.yaml, operatorconfig/moduleconfig/authorization/v2.0.0-alpha/deployment.yaml, pkg/modules/authorization.go, pkg/modules/testdata/cr_auth_proxy.yaml, pkg/modules/testdata/cr_auth_proxy_bad_vault_ca.yaml, pkg/modules/testdata/cr_auth_proxy_bad_vault_cert.yaml, pkg/modules/testdata/cr_auth_proxy_bad_vault_key.yaml, pkg/modules/testdata/cr_auth_proxy_certs.yaml, pkg/modules/testdata/cr_auth_proxy_certs_missing_key.yaml, pkg/modules/testdata/cr_auth_proxy_no_redis.yaml, pkg/modules/testdata/cr_auth_proxy_openshift.yaml, pkg/modules/testdata/cr_auth_proxy_vault_cert.yaml, samples/authorization/csm_authorization_proxy_server_v200-alpha.yaml, tests/e2e/testfiles/authorization-templates/csm_authorization_proxy_server.yaml, tests/e2e/testfiles/authorization-templates/csm_authorization_proxy_server_alt_ns.yaml, tests/e2e/testfiles/authorization-templates/csm_authorization_proxy_server_default_redis.yaml, tests/e2e/testfiles/authorization-templates/csm_authorization_proxy_server_ocp.yaml
Add configurable authorization controller reconcile interval. 
=> Add configurable controller reconcile interval

controllers/acc_controller.go, controllers/csm_controller.go, go.mod, go.sum, pkg/utils/utils.go
Removing the role and role bindings which were added as part of apex-connectivity-client from the CSM-objects, when the delete CSM object is triggered.
| |
=> Removing the role and rolebindings from the brownfield deployment

tests/e2e/steps/steps_def.go, tests/e2e/steps/steps_runner.go, tests/e2e/testfiles/connectivity-values.yaml
Added a new test scenario:
-deploy and validate powerflex is installed
-deploy connectivity-client
-validate rolebinding is created pointed to the role: Role/connectivity-client-docker-k8s in the namespace where driver is deployed
test case execution logs
[e2e-test-scenario.txt](https://github.com/user-attachments/files/15871660/e2e-test-scenario.txt)
=> New e2e test scenario

config/samples/storage_v1_csm_unity.yaml, operatorconfig/driverconfig/unity/v2.11.0/node.yaml, samples/storage_csm_unity_v2110.yaml
This PR update the usage of the env X_CSI_ALLOWED_NETWORKS in Unity driver sample to include comma separated values.
| https://github.com/dell/csm/issues/1335 |
=> CSI-Unity: Update usage of env X_CSI_ALLOWED_NETWORKS

operatorconfig/driverconfig/powerflex/v2.11.0/upgrade-path.yaml, operatorconfig/driverconfig/powerscale/v2.10.1/upgrade-path.yaml, operatorconfig/driverconfig/powerscale/v2.11.0/upgrade-path.yaml, operatorconfig/driverconfig/powerstore/v2.10.0/upgrade-path.yaml, operatorconfig/driverconfig/powerstore/v2.10.1/upgrade-path.yaml, operatorconfig/driverconfig/powerstore/v2.11.0/upgrade-path.yaml, operatorconfig/driverconfig/powerstore/v2.9.0/upgrade-path.yaml, operatorconfig/driverconfig/powerstore/v2.9.1/upgrade-path.yaml
A few files were missing n-2 upgrade/downgrade support for drivers.
Added them so that powerflex, powerstore and powerscale supports n-2 version of upgrade/downgrade
| |
=> Add n-2 downgrade support

config/samples/storage_v1_csm_powermax.yaml, operatorconfig/driverconfig/powermax/v2.10.0/node.yaml, operatorconfig/moduleconfig/resiliency/v1.10.0/container-powermax-controller.yaml, operatorconfig/moduleconfig/resiliency/v1.10.0/container-powermax-node.yaml, pkg/modules/resiliency.go, pkg/modules/resiliency_test.go, pkg/modules/testdata/cr_powermax_resiliency.yaml, tests/e2e/testfiles/scenarios.yaml, tests/e2e/testfiles/storage_csm_powermax_resiliency.yaml
Adding resiliency support for PowerMax.
| https://github.com/dell/csm/issues/1082|
=> Resiliency support powermax

samples/storage_csm_powerflex_v2110.yaml
Provide instruction for driver config version and authorization v2-alpha.
Driver configVersion will be 1.11.0 and user should use csm-authorization-sidecar:v2.0.0-alpha for PowerFlex Tech-Preview
| #https://github.com/dell/csm/issues/1281 |
- [x ] I have maintained backward compatibility
=> Provide instruction for driver config version and authorization v2-alpha

.github/containerscan/allowedlist.yaml, Makefile, tests/e2e/go.mod, tests/e2e/go.sum
Fixed podman image build of csm-operator due to go mod issue.
* Fix go mod issue
* Added `make tidy` target to update both mod files synchronously in parent folder and e2e folder
| https://github.com/dell/csm/issues/1360 |
=> Fix podman build of csm-operator

samples/authorization/csm_authorization_proxy_server_v200-alpha.yaml
PR for extending the support of dellctl for Powerscale volumes
```
[root@master-1-20JuIZwsvfcbQ csm-operator]# kubectl get pods -n authorization
NAME                                                    READY   STATUS    RESTARTS       AGE
authorization-controller-856484c445-qcb92               1/1     Running   0              118s
authorization-ingress-nginx-controller-fc999b64-m9c7m   1/1     Running   0              117s
cert-manager-69b6b795b8-64kx5                           1/1     Running   0              3m38s …
```
=> Dellctl support for Powerscale

operatorconfig/driverconfig/powerstore/v2.11.0/controller.yaml, operatorconfig/driverconfig/powerstore/v2.11.0/csidriver.yaml
Making default value of allowAutoRoundOffFilesystemSize param for powerstore true. So that the non-supported min size volume provisioning won't fail.
|https://github.com/dell/csm/issues/1377 |
-
=> make allowAutoRoundOffFilesystemSize param to true

tests/e2e/run-e2e-test.sh, tests/e2e/testfiles/application-mobility-templates/csm_application_mobility_old.yaml, tests/e2e/testfiles/stand-alone-upgrade.yaml
This PR adds a e2e test to velero-upgrade branch. 
This new test will install AM v1.0.3 and upgrade to v1.1.0. Then it will downgrade AM again. 
Adds standalone yaml and sets test file to point to it, to run only this test; we'll need to revert this change before merging velero-upgrade into main, but I left as is in case others want to add/edit tests for velero-upgrade 
- 
| |
```
Will run 1 of 1 specs
------------------------------
[BeforeSuite]
/root/csm-operator/tests/e2e/e2e_test.go:78
STEP: Getting test environment variables @ 07/12/24 17:43:38.267
STEP: [sanity] @ 07/12/24 …
```
=> Add e2e test

tests/e2e/testfiles/connectivity_client.yaml, tests/e2e/testfiles/connectivity_client_1.yaml
- connectivity client images pointed to dockerhub
|https://github.com/dell/csm/issues/1221|
=> client image update

operatorconfig/driverconfig/powermax/v2.10.1/node.yaml, pkg/modules/reverseproxy.go, tests/config/driverconfig/powermax/v2.10.0/node.yaml, tests/config/driverconfig/powermax/v2.10.1/node.yaml, tests/config/driverconfig/powermax/v2.9.1/node.yaml
This PR:
- Corrects the CHROOT env param in 2.10.1
- Corrects the unit tests file to point to correct param
- Minor update in reverseproxy to reflect CR image when installed as sidecar.
|https://github.com/dell/csm/issues/1221|
=> CSI PowerMax: Corrects CHROOT param in older version

controllers/csm_controller_test.go, pkg/resources/configmap/configmap.go, pkg/resources/csidriver/csidriver.go, pkg/utils/utils.go, samples/storage_csm_powerflex_v2101.yaml, samples/storage_csm_powerflex_v2110.yaml, samples/storage_csm_powerflex_v292.yaml, samples/storage_csm_powermax_v2101.yaml, samples/storage_csm_powermax_v2110.yaml, samples/storage_csm_powermax_v291.yaml, samples/storage_csm_powerscale_v2101.yaml, samples/storage_csm_powerscale_v2110.yaml, samples/storage_csm_powerscale_v291.yaml, samples/storage_csm_powerstore_v2101.yaml, samples/storage_csm_powerstore_v2110.yaml, samples/storage_csm_powerstore_v291.yaml, samples/storage_csm_unity_v2101.yaml, samples/storage_csm_unity_v2110.yaml, samples/storage_csm_unity_v291.yaml, tests/e2e/testfiles/scenarios.yaml, tests/shared/common.go
PR to add immutable note for fsGroupPolicy.
Added app mobility unit tests to boost coverage on controllers.
| https://github.com/dell/csm/issues/1322|
=> Add note for fsGroupPolicy

bundle/manifests/dell-csm-operator.clusterserviceversion.yaml, bundle/manifests/storage.dell.com_apexconnectivityclients.yaml, bundle/manifests/storage.dell.com_containerstoragemodules.yaml, bundle/metadata/annotations.yaml, config/manifests/bases/dell-csm-operator.clusterserviceversion.yaml, deploy/operator.yaml
Final Manifest Update for csm-operator release 1.6.0
| https://github.com/dell/csm/issues/1221|
=> Final Manifest Update for csm-operator release 1.6.0

pkg/drivers/commonconfig.go, pkg/drivers/powerflex.go
=> Draft PR,  do not merge: disable sdc-monito and health-monitor by default

operatorconfig/driverconfig/powermax/v2.11.0/controller.yaml, operatorconfig/driverconfig/powermax/v2.11.0/node.yaml, pkg/drivers/powermax.go, samples/minimal-samples/powermax.yaml
=> Pmax minimal changes

bundle/manifests/dell-csm-operator.clusterserviceversion.yaml, bundle/metadata/annotations.yaml
Updating the manifests and corrected auto generated code 
| https://github.com/dell/csm/issues/1221|
- Operator posting is done with the following changes.
=> Correcting the manifest files

samples/ocp/1.6.0/connectivity_client_v110.yaml, samples/ocp/1.6.0/storage_csm_powerflex_v2110.yaml, samples/ocp/1.6.0/storage_csm_powermax_v2110.yaml, samples/ocp/1.6.0/storage_csm_powerscale_v2110.yaml, samples/ocp/1.6.0/storage_csm_powerstore_v2110.yaml, samples/ocp/1.6.0/storage_csm_unity_v2110.yaml
Created a folder under samples folder for ocp and added the latest samples of CSM 1.6.0 which reflects the redhat registry and SHA ids specific to the release
| https://github.com/dell/csm/issues/1221|
- The samples added are already tested after the certification and these samples are added for reference so that customers can avoid manual work of finding out the SHA ids and registry details for different images used
=> Added OCP samples to reflect redhat registry and sha ids used for certification

tests/e2e/run-e2e-test.sh
In the operator test suite, there were several flags the user could use to specify what subset of the whole test suite they wanted to run. There was no way to only run the tests that didn't test any of the CSM modules. These commits add that functionality through a flag called --no-modules. Any test scenarios tagged with one of the modules (authentication, resiliency, etc.) will be skipped with this flag.
See below: The following test has the powerflex tag but also the authorization module so it's skipped
=> Added a --no-module flag to the Operator e2e tests

Dockerfile, bundle/manifests/dell-csm-operator.clusterserviceversion.yaml, config/install/kustomization.yaml, config/manager/kustomization.yaml, config/manifests/bases/dell-csm-operator.clusterserviceversion.yaml, controllers/csm_controller.go, deploy/olm/operator_community.yaml, deploy/operator.yaml, docker.mk
Initial PR to bump up the Operator version
|https://github.com/dell/csm/issues/1435|
Initial PR doesn't need any tests as those Images are not yet published.
=> operator version bump up

k8s/client.go, k8s/client_test.go
Fixed k8s client unit test panic when running on a machine without kube config. The client GetKubeAPIServerVersion() function did not allow setting fake client, instead it always tried to initialize a real k8s client and crashed if there were no kube config present on the machine.
Example of the failure:
```
[root@lglw1113 csm-operator]#
[root@lglw1113 csm-operator]# make test
test -s /root/csm/csm-operator/bin/controller-gen && /root/csm/csm-operator/bin/controller-gen --version | grep -q v0.15.0 || \
GOBIN=/root/csm/csm-operator/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.15.0
/root/csm/csm-operator/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
/root/csm/csm-operator/bin/controller-gen …
```
=> Fixed k8s client unit test panic

operatorconfig/driverconfig/common/default.yaml, operatorconfig/driverconfig/common/k8s-1.24-values.yaml, operatorconfig/driverconfig/common/k8s-1.25-values.yaml, operatorconfig/driverconfig/common/k8s-1.26-values.yaml, operatorconfig/driverconfig/common/k8s-1.27-values.yaml, operatorconfig/driverconfig/common/k8s-1.28-values.yaml, operatorconfig/driverconfig/common/k8s-1.29-values.yaml, operatorconfig/driverconfig/common/k8s-1.30-values.yaml, operatorconfig/driverconfig/powerflex/v2.11.0/controller.yaml, operatorconfig/driverconfig/powerflex/v2.11.0/node.yaml, operatorconfig/driverconfig/powermax/v2.12.0/controller.yaml, operatorconfig/driverconfig/powermax/v2.12.0/csidriver.yaml, operatorconfig/driverconfig/powermax/v2.12.0/driver-config-params.yaml, operatorconfig/driverconfig/powermax/v2.12.0/node.yaml, operatorconfig/driverconfig/powermax/v2.12.0/upgrade-path.yaml, pkg/drivers/commonconfig.go, pkg/drivers/powerflex.go, pkg/drivers/powerflex_test.go, pkg/drivers/powermax.go, pkg/drivers/powerscale.go, pkg/drivers/powerstore.go, pkg/drivers/unity.go, pkg/modules/reverseproxy.go, pkg/modules/reverseproxy_test.go, pkg/utils/utils.go, samples/minimal-samples/powerflex.yaml, samples/minimal-samples/powermax.yaml, samples/minimal-samples/powerscale.yaml, samples/minimal-samples/powerstore.yaml, samples/minimal-samples/unity.yaml
Need for a simple and minimal manifest file using existing Operator CRD.
Changes include adding the below default values in the code:
- Reverse proxy module for PowerMax driver
- Disable sdc-monitor and health-monitor by default
- Added the default check for kubelet config directory
- Fixed issues with initContainer and MDM key not found issue in PowerFlex driver
cert-csi  Test report for certify suite for ISCSI powerstore driver   
[report-test-run-bfdfd42b.txt](https://github.com/user-attachments/files/16942534/report-test-run-bfdfd42b.t …
=> Added support for minimal manifests

operatorconfig/driverconfig/common/k8s-1.31-values.yaml, operatorconfig/driverconfig/powermax/v2.12.0/node.yaml, samples/storage_csm_powerflex_v2120.yaml, samples/storage_csm_powerscale_v2120.yaml, samples/storage_csm_powerstore_v2120.yaml, tests/README.md, tests/e2e/array-info.sh, tests/e2e/e2e_test.go, tests/e2e/run-e2e-test.sh
This PR fixes some issues found while testing Pstore. 
These issues were:
```   ./run-e2e-test.sh --pstore  
./run-e2e-test.sh: line 274: APPLICATIONMOBILITY: unbound variable
```
and 
```
./run-e2e-test.sh --pstore  --no-modules
```
resulting in the modules tests being ran anyway 
[nohup-pstore-all-final.txt](https://github.com/user-attachments/files/16999452/nohup-pstore-all-final.txt)
[nohup-pstore-nomod-final.txt](https://github.com/user-attachments/files/16999463/nohup-pstore-nomod-final.txt)
=> Fix --no-modules on e2e tests

operatorconfig/driverconfig/powerscale/v2.12.0/csidriver.yaml
Setting storageCapacity spec value to False so while updating it during the runtime it will be synchronized at csidriver level. 
|https://github.com/dell/csm/issues/1475|
=> storage capacity update

operatorconfig/moduleconfig/resiliency/v1.11.0/container-powerscale-controller.yaml, operatorconfig/moduleconfig/resiliency/v1.11.0/container-powerscale-node.yaml, samples/minimal-samples/powerscale.yaml
Support was added to enable the resiliency module in the minimal manifest file.
|https://github.com/dell/csm/issues/1449 |
=> Enables resiliency module for powerscale in the minimal manifest file

bundle/manifests/dell-csm-operator.clusterserviceversion.yaml, config/default/manager_auth_proxy_patch.yaml, config/manager/manager.yaml, config/manifests/bases/dell-csm-operator.clusterserviceversion.yaml, deploy/operator.yaml, operatorconfig/moduleconfig/application-mobility/v1.0.0/app-mobility-controller-manager.yaml, operatorconfig/moduleconfig/application-mobility/v1.0.1/app-mobility-controller-manager.yaml, operatorconfig/moduleconfig/application-mobility/v1.0.2/app-mobility-controller-manager.yaml, operatorconfig/moduleconfig/application-mobility/v1.0.3/app-mobility-controller-manager.yaml, operatorconfig/moduleconfig/application-mobility/v1.1.0/app-mobility-controller-manager.yaml
Updated kube-rbac-proxy image to the repackaged by Redhat:
**Existing image**: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
**New image**: registry.redhat.io/openshift4/ose-kube-rbac-proxy-rhel9:v4.16.0-202409051837.p0.g8ea2c99.assembly.stream.el9
|https://github.com/dell/csm/issues/1435 |
Did basic sanity by creating an image using these updates. Installed CSM Operator and created Unity CSM Object on top of that and brought up application pods with PVC s on that.. All looks good.
=> Updated kube-rbac-proxy image to the one packaged by Redhat

tests/e2e/testfiles/scenarios.yaml
Fix pmaxCreds not set correctly in e2e.
| https://github.com/dell/csm/issues/1478 |
=> Fix pmaxCreds not set correctly in e2e

samples/minimal-samples/powerflex.yaml, samples/minimal-samples/powermax.yaml, samples/minimal-samples/powerscale.yaml
Support Auth module deployment with Powerflex using minimal CR
| (https://github.com/dell/csm/issues/1449) |
[powerflex-auth-cert-csi.txt](https://github.com/user-attachments/files/17160781/powerflex-auth-cert-csi.txt)
=> Support auth module in pflex minimal CR

operatorconfig/driverconfig/powermax/v2.12.0/controller.yaml, operatorconfig/driverconfig/powermax/v2.12.0/node.yaml, pkg/drivers/commonconfig.go
This PR has the changes for minimizing the manifest file for the AuthorizationV2.0 Module in the PowerMax Driver
| https://github.com/dell/csm/issues/1449|
=> Minimal manifest for Powermax with authorization 2.0 

pkg/utils/utils.go, samples/minimal-samples/powermax.yaml
Added support to install Replication module with the minimal manifest.
=> Added support for replication with minimal manifest

samples/storage_csm_powerflex_v2101.yaml, samples/storage_csm_powerflex_v2110.yaml, samples/storage_csm_powerflex_v2120.yaml, samples/storage_csm_powermax_v2101.yaml, samples/storage_csm_powermax_v2110.yaml, samples/storage_csm_powermax_v2120.yaml, samples/storage_csm_powerscale_v2101.yaml, samples/storage_csm_powerscale_v2110.yaml, samples/storage_csm_powerscale_v2120.yaml, samples/storage_csm_powerstore_v2101.yaml, samples/storage_csm_powerstore_v2110.yaml, samples/storage_csm_powerstore_v2120.yaml, samples/storage_csm_unity_v2101.yaml, samples/storage_csm_unity_v2110.yaml, samples/storage_csm_unity_v2120.yaml
- Add Resiliency tolerations of PowerStore, PowerFLex, PowerMax, PowerScale and Unity
|https://github.com/dell/csm/issues/1510 |
=> Add Resileincy Tolerations

tests/e2e/testfiles/minimal-testfiles/scenarios.yaml, tests/e2e/testfiles/minimal-testfiles/storage_csm_powerflex.yaml, tests/e2e/testfiles/minimal-testfiles/storage_csm_powerflex_auth.yaml, tests/e2e/testfiles/minimal-testfiles/storage_csm_powerflex_auth_v1.yaml, tests/e2e/testfiles/minimal-testfiles/storage_csm_powerflex_observability.yaml, tests/e2e/testfiles/minimal-testfiles/storage_csm_powerflex_observability_otel_custom_cert.yaml, tests/e2e/testfiles/minimal-testfiles/storage_csm_powerflex_resiliency.yaml
E2E test for the powerflex driver for Minimal Manifest file
- [X ] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [ X] I have verified that new and existing unit tests pass locally with my changes
- [ X] I have not allowed coverage numbers to degenerate
- [ X] I have maintained at least 90% code coverage
- [ X] I have commented my code, particularly in hard-to-understand areas
- [ X] I have made corresponding changes to the documentation
- [ X] I have added tests that prove my fix is effective or that my feature works
- [ X] I have maintained backward compatibility
Please describe the tests …
=> E2E tests for powerflex driver in the minimal manifest file

controllers/acc_controller.go, controllers/acc_controller_test.go, pkg/drivers/powermax.go, pkg/drivers/powermax_test.go, pkg/modules/reverseproxy.go, pkg/modules/reverseproxy_test.go, pkg/utils/status.go, pkg/utils/utils.go
1. Added deployAsSidecar for reversproxy as default for minimal manifests
2. Updated code coverage
=> Added deployAsSidecar for reversproxy as default for minimal manifests

tests/e2e/testfiles/powermax-templates/powermax_reverse_proxy_config.yaml, tests/e2e/testfiles/powermax-templates/powermax_reverse_proxy_config_auth.yaml, tests/e2e/testfiles/scenarios.yaml, tests/e2e/testfiles/storage_csm_powermax.yaml, tests/e2e/testfiles/storage_csm_powermax_authorization.yaml, tests/e2e/testfiles/storage_csm_powermax_observability.yaml, tests/e2e/testfiles/storage_csm_powermax_observability_authorization.yaml, tests/e2e/testfiles/storage_csm_powermax_resiliency.yaml, tests/e2e/testfiles/storage_csm_powermax_reverseproxy_authorization.yaml, tests/e2e/testfiles/storage_csm_powermax_sidecar.yaml
This PR fixes the pmax e2e tests in CSM Operator repo so that they may be run sequentially 
- Adds configmap creation/restore for pmax v1 scenarios 
- Adjusts cert-csi to lower the inconsistent error of failing to find device when running cert-csi
- Adjusts images/replica count to make tests more consistently pass 
| https://github.com/dell/csm/issues/1507 |
=> Fix PowerMax E2E

Makefile, pkg/utils/utils.go, pkg/utils/utils_test.go
Add UT for utils pkg.
[utils-unit-test.log](https://github.com/user-attachments/files/17432125/utils-unit-test.log)
=> Add UT for utils pkg

tests/e2e/testfiles/minimal-testfiles/storage_csm_powermax_reverseproxy_authorization.yaml, tests/e2e/testfiles/minimal-testfiles/storage_csm_powermax_reverseproxy_authorization_v2.yaml
- Added e2e for Powermax Auth v1 
|https://github.com/dell/csm/issues/1449 |
- [X ] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [ X] I have verified that new and existing unit tests pass locally with my changes
- [ X] I have not allowed coverage numbers to degenerate
- [ X] I have maintained at least 90% code coverage
- [ X] I have commented my code, particularly in hard-to-understand areas
- [ X] I have made corresponding changes to the documentation
- [ X] I have added tests that prove my fix is effective or that my feature works
- [ X] I have maintained backward compatibility
Please describe the tests that you ran to verify your …
=> E2E tests for PMax driver in minimal manifest file Auth v1

tests/e2e/go.mod
This PR fixes the operator e2e tests not working because toolchain version is missing.
```
go: downloading go1.23 (linux/amd64)
go: download go1.23 for linux/amd64: toolchain not available
```
| https://github.com/dell/csm/issues/1435 |
Before:
Test suite fails and exists with the following logs:
```
go: downloading go1.23 (linux/amd64)
go: download go1.23 for linux/amd64: toolchain not available
```
After:
Test suite passes as expected:
```
go: downloading go1.23.2 (linux/amd64)
```
=> Add toolchain version to tests/e2e/go.mod

operatorconfig/driverconfig/powerflex/v2.12.0/node.yaml
Add private mount for /disks in the PowerFlex node pod. Similar change made to Helm chart, see https://github.com/dell/helm-charts/pull/545.
| https://github.com/dell/csm/issues/1546 |
=> Add private mount for PowerFlex /disks path.

bundle.Dockerfile
Update bundle.Dockerfile lowerbound to support installation on n-3 version clusters. (to install the CSM Operator on older OCP versions (up to n-3). More details in release activities feature)
| https://github.com/dell/csm/issues/1435 |
> [2024-10-29 19:26:42]  INFO During this run 100.0% of suites succeeded
STEP:      Executing  Enable forceRemoveDriver on CR [1] @ 10/29/24 19:26:42.652
STEP:      Executing  Delete custom resource [1] @ 10/29/24 19:26:42.657
STEP:      Executing  Restore template [testfiles/powerflex-templates/powerflex-secret-template.yaml] for [pflex] @ 10/29/24 19:26:42.68
STEP: …
=> Update bundle.Dockerfile file for the supported openshift lower bound(n-3) version

bundle/manifests/csm-config-params_v1_configmap.yaml, bundle/manifests/dell-csm-operator.clusterserviceversion.yaml, config/manager/manager.yaml, config/manifests/bases/dell-csm-operator.clusterserviceversion.yaml, config/rbac/role.yaml, config/samples/kustomization.yaml, config/samples/storage_v1_csm_authorization_v2.yaml, config/samples/storage_v1_csm_powerflex.yaml, config/samples/storage_v1_csm_powermax.yaml, config/samples/storage_v1_csm_powerscale.yaml, deploy/operator.yaml
`bundle/manifests/dell-csm-operator.clusterserviceversion.yaml`, used to build an image manifest when building the offline bundle, is updated with the Authorization Server images. 
- Authorization v2 sample is created under `config/samples` for `make bundle` to generate an Authorization section in `alm-examples` in the bundle CSV.
- `bundle/manifests/csm-config-params_v1_configmap.yaml` is created because the Authorization v2 sample file contains this
- csm-authorization-sidecar images tags in the driver `config/samples` now use v2.0.0 to point to the latest release
- RELATED_IMAGE environment variables and fields are updated with Authorization v2
| https://github.com/dell/csm/issues/1581|
Please describe …
=> [bug-1581]: Offline bundle contains Authorization v2 server images

tests/e2e/testfiles/storage_csm_powerflex_alt_vals_1.yaml, tests/e2e/testfiles/storage_csm_powerflex_alt_vals_2.yaml, tests/e2e/testfiles/storage_csm_powerflex_alt_vals_3.yaml, tests/shared/common.go
In OCP clusters, the master nodes have the taint - key: "node-role.kubernetes.io/master" and not - key: "node-role.kubernetes.io/control-plane" so the controller pods are looking for a taint that doesn't exist in the E2E test scenarios that uses existing alternate values file. The toleration - key: "node-role.kubernetes.io/master" should be added. More details in the ticket
| https://github.com/dell/csm/issues/1591 |
Executed the E2E scenarios that uses updated values file in OCP and K8S clusters and the tests pass. Results attached below:
[KRV-30363-e2e.txt](https://github.com/user-attachments/files/17745681/KRV-30363-e2e.txt)
=> Fix Powerflex e2e alternate values tests in OCP cluster

samples/csireverseproxy/config.yaml, tests/e2e/testfiles/powermax-templates/powermax_reverse_proxy_config.yaml, tests/e2e/testfiles/powermax-templates/powermax_reverse_proxy_config_auth.yaml
Remove mode: StandAlone from reverseproxy config.yaml
| https://github.com/dell/csm/issues/1567
-Executed cert-csi successfully
[cert-csi-logs.txt.txt](https://github.com/user-attachments/files/17798819/cert-csi-logs.txt.txt)
E2E powermax scenario has passed:
```
[root@master-1-vxa4Qh4cj2ZFH e2e]# ./run-e2e-test.sh --pmax --cert-csi=/root/cert-csi
/root/kk/new-defect/csm-operator/tests/e2e
W1122 10:04:14.081149  609344 test_context.go:538] Unable to find in-cluster config, using default host : https://127.0.0    .1:6443
I1122 10:04:14.081329 609344 test_context.go:561] The --provider flag is not set. Continuing as if --provider=skeleton ha    d been used.
Running Suite: CSM Operator End-to-End Tests - …
```
=> Remove mode: StandAlone from reverseproxy config.yaml

.github/pull_request_template.md, pkg/drivers/powermax.go, samples/storage_csm_powermax_v2120.yaml, tests/e2e/testfiles/storage_csm_powermax.yaml, tests/e2e/testfiles/storage_csm_powermax_sidecar.yaml
Remove stale entries from CSI Powermax Reverseproxy CR
| https://github.com/dell/csm/issues/1585 |
The operator e2e tests were executed successfully. Full log attached in Jira ticket.
=> [BUG]: Remove entries in CSI PowerMax Samples of CSM operator

pkg/drivers/common_test.go, pkg/drivers/powerscale_test.go
Increase coverage for driver package
| |
make driver-unit-test
=> [WIP] Increase coverage for driver package

samples/ocp/1.7.0/storage_csm_powerflex_v2120.yaml, samples/ocp/1.7.0/storage_csm_powermax_v2120.yaml, samples/ocp/1.7.0/storage_csm_powerscale_v2120.yaml, samples/ocp/1.7.0/storage_csm_powerstore_v2120.yaml, samples/ocp/1.7.0/storage_csm_unity_v2120.yaml
The image shaID is updated to latest in driver samples for CSM deployment in OCP
| https://github.com/dell/csm/issues/1435 |
Verified by pulling the images from there respective registry:
=> Updated the Image SHA ID in driver samples for OCP

pkg/drivers/powerflex.go, pkg/drivers/powerflex_test.go
PR adds the method to read the zoning information from the PowerFlex array secret
|https://github.com/dell/csm/issues/1613|
```
github.com/dell/csm-operator/api/v1             coverage: 0.0% of statements
github.com/dell/csm-operator            coverage: 0.0% of statements
github.com/dell/csm-operator/core/semver                coverage: 0.0% of statements
?       github.com/dell/csm-operator/pkg/constants      [no test files]
github.com/dell/csm-operator/core               coverage: 0.0% of statements
github.com/dell/csm-operator/pkg/logger         coverage: 0.0% of statements …
```
=> Read zone information from PowerFlex secret

controllers/csm_controller.go, controllers/csm_controller_test.go, tests/shared/common.go, tests/shared/crclient/client.go
Detect Zone info in node labels and return the list of nodes with this label-value pair.
| https://github.com/dell/csm/issues/1613|
=> Detect Zone info in node labels 

samples/storage_csm_powerflex_v2101.yaml, samples/storage_csm_powerflex_v2110.yaml, samples/storage_csm_powerflex_v2120.yaml
updated the default value in comment for fSGroupPolicy in  powerflex samples
| https://github.com/dell/csm/issues/1559|
=> updated the default value in comment for fSGroupPolicy in  powerflex samples

pkg/drivers/powerflex.go, pkg/drivers/powerflex_test.go
PR fixes retrieving zone information from multi array secret
|https://github.com/dell/csm/issues/1613|
```
github.com/dell/csm-operator            coverage: 0.0% of statements
github.com/dell/csm-operator/api/v1             coverage: 0.0% of statements
github.com/dell/csm-operator/core               coverage: 0.0% of statements
?       github.com/dell/csm-operator/pkg/constants      [no test files]
github.com/dell/csm-operator/core/semver                coverage: 0.0% of statements
github.com/dell/csm-operator/pkg/logger         coverage: 0.0% of statements …
```
=> Retrieve zone information from multi array secret

tests/e2e/steps/steps_def.go
Filepath imported 2 times causing E2E compilation issue.
|https://github.com/dell/csm/issues/1642|
This compilation issue was coming before 
[root@e2e]# ./run-e2e-test.sh --unity --cert-csi=/root/cert-csi/cert-csi --dellctl=/root/dellctl --karavictl=/root/karavictl
go: downloading golang.org/x/sys v0.28.0
go: downloading golang.org/x/term v0.27.0
go: downloading golang.org/x/text v0.21.0
go: downloading golang.org/x/sync v0.10.0
go: downloading golang.org/x/crypto v0.31.0
/root/taran/csm-operator/tests/e2e
Failed to compile e2e:
steps/steps_def.go:30:2: filepath redeclared in this block
steps/steps_def.go:28:2: other declaration of filepath
steps/steps_def.go:30:2: "path/filepath" imported and not used …
=> removed redeclared filepath

config/samples/storage_v1_csm_powermax.yaml, samples/storage_csm_powermax_v2130.yaml, tests/e2e/testfiles/storage_csm_powermax.yaml, tests/e2e/testfiles/storage_csm_powermax_authorization.yaml, tests/e2e/testfiles/storage_csm_powermax_observability.yaml, tests/e2e/testfiles/storage_csm_powermax_observability_authorization.yaml, tests/e2e/testfiles/storage_csm_powermax_resiliency.yaml, tests/e2e/testfiles/storage_csm_powermax_reverseproxy_authorization.yaml, tests/e2e/testfiles/storage_csm_powermax_sidecar.yaml
Fixing default value for X_CSI_K8S_CLUSTER_PREFIX
|https://github.com/dell/csm/issues/1638 |
I ran e2e powermax standalone and sidecar  test and it passed successfully.
[e2e with default value for cluster prefix.txt](https://github.com/user-attachments/files/18146080/e2e.with.default.value.for.cluster.prefix.txt)
=> Fixing default value for X_CSI_K8S_CLUSTER_PREFIX

tests/e2e/testfiles/powermax-templates/powermax_reverse_proxy_config.yaml
This PR includes updates to the PowerMax reverse proxy configuration file for e2e.
|dell/csm#1594|
For minimal it ran successfully: ./run-e2e-test.sh --minimal --cert-csi=/root/cert-csi --no-modules --pmax
For maximal it ran successfully: ./run-e2e-test.sh --cert-csi=/root/cert-csi --no-modules --pmax
=> Fix for reverse proxy config

pkg/drivers/commonconfig.go
Setting ownerReference was failing because the GroupVersion used is incorrect "apps/v1" instead of "storage.dell.com/v1".
So when in maximal/minimal CR, when forceRemoveDriver: false, CSM installation was failing when Operator deployed from UI
| https://github.com/dell/csm/issues/1605 |
The operator e2e tests were executed successfully. Full log attached in Jira ticket.
>  oc get csm -A
> NAMESPACE   NAME       CREATIONTIME   CSIDRIVERTYPE   CONFIGVERSION   STATE
> vxflexos    vxflexos   20m            powerflex       v2.12.0         Succeeded
> 
> oc get pods -n vxflexos
> NAME …
=> change incorrect GroupVersion

tests/e2e/testfiles/scenarios.yaml
- Updated one test scenario name Operator E2E for PowerMax. It was still named as `Install PowerMax Driver(Standalone)` while the sample yaml file is deploying as sidecar now.
- Removed the duplicated test scenario of deploying as sidecar.
Related to PR #831 as Operator E2E is needed for it.
```
STEP: Starting: Install PowerMax Driver  @ 12/30/24 12:35:44.918
STEP: Returning false at end @ 12/30/24 12:35:44.918
STEP:      Executing  Given an environment with k8s or openshift, and CSM operator installed @ 12/30/24 12:35:44.918
STEP: …
```
=> Updated Operator E2E Test for PowerMax

operatorconfig/driverconfig/powermax/v2.13.0/node.yaml
Extra and unused mount caused mount to double on every pod restart and uninstall/reinstall cycle. This will eventually cause some processes (e.g. system scanners, antivirus) to experience high CPU usage which renders the worker node unusable.
| https://github.com/dell/csm/issues/1659 |
We could add a test to check every node to validate the fix but given that the mount will no longer be present it may be more work than needed. Ideally we could have a general purpose e2e test that check for uninstall cleanup to cover all Operator installation and uninstallation cases.
=> Remove redundant volume mount from the pmax driver container

samples/authorization/csm_authorization_proxy_server_v1110.yaml, samples/authorization/csm_authorization_proxy_server_v1120.yaml, samples/authorization/csm_authorization_proxy_server_v1130.yaml, samples/authorization/csm_authorization_proxy_server_v200-alpha.yaml, samples/authorization/csm_authorization_proxy_server_v200.yaml, samples/authorization/csm_authorization_proxy_server_v210.yaml, tests/e2e/testfiles/authorization-templates/storage_csm_authorization_v1_proxy_server.yaml, tests/e2e/testfiles/authorization-templates/storage_csm_authorization_v1_proxy_server_alt_ns.yaml, tests/e2e/testfiles/authorization-templates/storage_csm_authorization_v1_proxy_server_n_minus_1.yaml, tests/e2e/testfiles/authorization-templates/storage_csm_authorization_v1_proxy_server_no_cert.yaml, tests/e2e/testfiles/authorization-templates/storage_csm_authorization_v2_multiple_vaults.yaml, tests/e2e/testfiles/authorization-templates/storage_csm_authorization_v2_proxy_server.yaml, tests/e2e/testfiles/authorization-templates/storage_csm_authorization_v2_proxy_server_default_redis.yaml
OPA 1.0.0 fails to parse Authorization policies, so we will use the previous version which works.
| https://github.com/dell/csm/issues/1661|
Ran Authorization e2e and manually verified that policy config maps have correct OPA annotations.
Installed Authorization via the Operator and verified that the policies are successfully parsed.
```
kubectl -n authorization get cm volumes-create -o yaml
...
metadata:
annotations:
openpolicyagent.org/kube-mgmt-retries: "0"
openpolicyagent.org/kube-mgmt-status: '{"status":"ok"}'
```
=> [bug-1661]: Use OPA 0.70.0

operatorconfig/driverconfig/powermax/v2.13.0/controller.yaml, operatorconfig/driverconfig/powermax/v2.13.0/node.yaml, pkg/drivers/powermax.go, pkg/modules/reverseproxy.go, samples/storage_csm_powermax_v2130.yaml, tests/config/driverconfig/powermax/v2.13.0/controller.yaml, tests/config/driverconfig/powermax/v2.13.0/node.yaml, tests/e2e/steps/steps_def.go, tests/e2e/steps/steps_runner.go, tests/e2e/testfiles/powermax-templates/san.cnf, tests/e2e/testfiles/scenarios.yaml, tests/e2e/testfiles/storage_csm_powermax.yaml, tests/e2e/testfiles/storage_csm_powermax_sidecar_tls.yaml, tests/e2e/testfiles/storage_csm_powermax_tls.yaml
Update operator to mount the reverse proxy TLS secret within the powermax driver container. This PR resolves the `cannot validate certificate for 0.0.0.0 because it doesn't contain any IP SANs` error when `skipCertificateValidation` is set to `false`.
| dell/csm#1571 |
=> Mount reverse proxy TLS secret within powermax driver container

api/v1/types.go, controllers/csm_controller.go, controllers/csm_controller_test.go, operatorconfig/driverconfig/powerflex/v2.12.0/node.yaml, operatorconfig/driverconfig/powermax/v2.14.0/controller.yaml, operatorconfig/driverconfig/powermax/v2.14.0/csidriver.yaml, operatorconfig/driverconfig/powermax/v2.14.0/driver-config-params.yaml, operatorconfig/driverconfig/powermax/v2.14.0/node.yaml, operatorconfig/driverconfig/powermax/v2.14.0/upgrade-path.yaml, operatorconfig/moduleconfig/csireverseproxy/v2.13.0/container.yaml, operatorconfig/moduleconfig/csireverseproxy/v2.13.0/controller.yaml, operatorconfig/moduleconfig/csireverseproxy/v2.13.0/service.yaml, pkg/drivers/powermax.go, pkg/drivers/powermax_test.go, pkg/modules/reverseproxy.go, pkg/modules/reverseproxy_test.go, pkg/modules/testdata/cr_powermax_reverseproxy_use_secret.yaml, tests/e2e/steps/steps_def.go, tests/e2e/testfiles/powermax-templates/powermax-use-secret-template.yaml, tests/e2e/testfiles/scenarios.yaml, tests/e2e/testfiles/storage_csm_powermax_observability.yaml, tests/e2e/testfiles/storage_csm_powermax_observability_authorization.yaml, tests/e2e/testfiles/storage_csm_powermax_reverseproxy_authorization.yaml, tests/e2e/testfiles/storage_csm_powermax_secret.yaml, tests/e2e/testfiles/storage_csm_powermax_secret_sidecar.yaml
Add mount credentials support to PowerMax. This introduces the ability to create a create a secret that will be mounted as a volume instead of the usage of a ConfigMap for communication to the backend array.
Both ConfigMap and Secret approaches are supported for backwards compatibility. Depending on the the `X_CSI_REVPROXY_USE_SECRET` environment variable, either the secret or configMap will be dynamically mounted for the PowerMax `controller`, `nodes`, and `reverseProxy`.
<details>
<summary>controller/driver:</summary>
``` …
```
=> Add PowerMax Mount Credentials Support

controllers/csm_controller.go, operatorconfig/driverconfig/powermax/v2.14.0/controller.yaml, operatorconfig/driverconfig/powermax/v2.14.0/node.yaml, operatorconfig/moduleconfig/common/version-values.yaml, pkg/drivers/powermax.go, pkg/drivers/powermax_test.go, pkg/modules/reverseproxy.go, pkg/modules/reverseproxy_test.go, pkg/utils/utils.go, tests/e2e/steps/steps_def.go, tests/e2e/testfiles/minimal-testfiles/scenarios.yaml, tests/e2e/testfiles/minimal-testfiles/storage_csm_powermax_secret.yaml
Fix dynamically adding parameters for the config map and mount credentials approach for Powermax. Also, fix the processing of the minimal manifest installation for Powermax to work with the mount credentials.
<details>
```
-> # make test
test -s /root/git/public/dell/csm-operator/bin/controller-gen && /root/git/public/dell/csm-operator/bin/controller-gen --version | grep -q v0.16.5 || \
GOBIN=/root/git/public/dell/csm-operator/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.16.5 …
```
=> Update Powermax to handle Minimal Manifests with Mount Credentials

deploy/crds/storage.dell.com.crds.all.yaml, scripts/uninstall.sh, tests/e2e/testfiles/minimal-testfiles/scenarios.yaml, tests/e2e/testfiles/minimal-testfiles/storage_csm_powerflex_with_false_forceRemoveDriver.yaml, tests/e2e/testfiles/minimal-testfiles/storage_csm_powerflex_with_no_forceRemoveDriver.yaml
Update the CRDs in the `deploy` folder with the autogenerated CRDs from the `config` folder.
**Note:** Most of the changes are formatting descriptions. Main change, the replicas default to `2` for CRs that don't a replica field. This would be most important for `minimal manifest` since this is not supplied.
| https://github.com/dell/csm/issues/1721 |
<details>
```
$ bash scripts/uninstall.sh
******
Deleting the Operator Deployment
******
serviceaccount "dell-csm-operator-manager-service-account" deleted
role.rbac.authorization.k8s.io "dell-csm-operator-leader-election-role" deleted …
```
=> Align CRD in Deploy Folder with Generated CRDs

operatorconfig/moduleconfig/common/version-values.yaml, operatorconfig/moduleconfig/observability/v1.12.0/custom-cert.yaml, operatorconfig/moduleconfig/observability/v1.12.0/karavi-metrics-powerflex.yaml, operatorconfig/moduleconfig/observability/v1.12.0/karavi-metrics-powermax.yaml, operatorconfig/moduleconfig/observability/v1.12.0/karavi-metrics-powerscale.yaml, operatorconfig/moduleconfig/observability/v1.12.0/karavi-otel-collector.yaml, operatorconfig/moduleconfig/observability/v1.12.0/karavi-topology.yaml, operatorconfig/moduleconfig/observability/v1.12.0/selfsigned-cert.yaml, pkg/drivers/powermax.go, pkg/modules/observability.go, pkg/modules/observability_test.go, pkg/modules/reverseproxy.go, tests/e2e/testfiles/minimal-testfiles/scenarios.yaml, tests/e2e/testfiles/scenarios.yaml, tests/e2e/testfiles/storage_csm_powermax_secret.yaml, tests/e2e/testfiles/storage_csm_powermax_secret_sidecar.yaml
Dynamically add and mount the config map or secret depending on which approach is defined during the Powermax CR installation.
```
karavi-metrics-powermax:
...
X_CSI_REVPROXY_SECRET_FILEPATH:  /etc/powermax/config
X_CSI_REVPROXY_USE_SECRET:       true
X_CSI_POWERMAX_CONFIG_PATH:      /powermax-config-params/driver-config-params.yaml
Mounts:
/certs from certs (rw)
/etc/config from karavi-metrics-powermax-configmap (rw)
/etc/powermax from powermax-reverseproxy-secret (rw)
/etc/ssl/certs from tls-secret (ro)
powermax-config-params from …
```
=> Dynamically mount secret or config map on Powermax observability

tests/e2e/testfiles/scenarios.yaml, tests/e2e/testfiles/storage_csm_powermax_secret.yaml, tests/e2e/testfiles/storage_csm_powermax_secret_sidecar.yaml
Add E2E tests that installs the Powermax driver using mount credentials and enables Authorization v1.
<details>
```
-> # bash run-e2e-test.sh --pmax
/root/git/public/dell/csm-operator/tests/e2e
W0204 15:58:22.205666   24432 test_context.go:541] Unable to find in-cluster config, using default host : https://127.0.0.1:6443
I0204 15:58:22.206486 24432 test_context.go:564] The --provider flag is not set. Continuing as if --provider=skeleton had been used.
Running Suite: CSM Operator End-to-End Tests - …
```
=> Add auth v1 e2e tests using PowerMax mount credentials

samples/storage_csm_powerflex_v2110.yaml, samples/storage_csm_powerflex_v2120.yaml, samples/storage_csm_powerflex_v2130.yaml, samples/storage_csm_powermax_v2110.yaml, samples/storage_csm_powermax_v2120.yaml, samples/storage_csm_powermax_v2130.yaml
Appropriate flags for logging have been added to PowerFlex and PowerMax sample CSM files. 
| https://github.com/dell/csm/issues/1762 |
For csi-powerflex, I have added appropriate env variable to the sample and verified that it propagates to the driver on installation. When set to trace: 
```
opensuse154:~/git/csm-operator/scripts # k logs -n vxflexos vxflexos-controller-5b5d9f48d6-b6dz4 -c driver
time="2025-02-26T16:23:16Z" level=info msg="configured <REDACT>" allSystemNames= endpoint=<REDACT>" isDefault=true nasName=none password="********" skipCertificateValidation=true systemID=<REDACT> user=admin
time="2025-02-26T16:23:16Z" level=info msg="driver configuration file " …
```
=> Add debug flags to samples - PowerFlex + PowerMax

operatorconfig/moduleconfig/observability/v1.10.0/karavi-topology.yaml, operatorconfig/moduleconfig/observability/v1.11.0/karavi-topology.yaml, operatorconfig/moduleconfig/observability/v1.12.0/karavi-topology.yaml, operatorconfig/moduleconfig/observability/v1.9.0/karavi-topology.yaml
- Update to karavi topology template for powermax
|https://github.com/dell/csm/issues/1747|
```
=== RUN   Test_Query_Topology
2025/03/04 01:05:23 TestTimeout=7, DumpOutput=false
time="2025-03-04T01:05:23-02:00" level=info msg="Running: /root/.local/bin/cert-csi test vio --sc powermax-iscsi-xfs --chainNumber 5 --chainLength 1 --no-metrics --no-reports --longevity %s 10m"
length of volume map 0
length of volume map 0
length of volume map 0
length of volume map 4
time="2025-03-04T01:05:23-02:00" level=info msg="Sending signal to stop cert-csi process..."
time="2025-03-04T01:05:23-02:00" level=info msg="Signal SIGKILL sent to 348342. Waiting for process to exit..."
time="2025-03-04T01:05:23-02:00" level=info …
```
=> powermax karavi topology e2e fix

samples/minimal-samples/powermax_v2140.yaml, samples/storage_csm_powermax_v2140.yaml, tests/e2e/testfiles/minimal-testfiles/scenarios.yaml, tests/e2e/testfiles/scenarios.yaml
Reintroduce the PowerMax mount credentials e2e tests since the nightly image has been created for Powermax.
Also, add the sample files for v2.14.0 with the new `X_CSI_REVPROXY_USE_SECRET` variable that can be used to enable/disable mount credentials.
=> Reintroduce PowerMax Mount Credentials E2E Tests

pkg/drivers/powerstore.go, pkg/drivers/powerstore_test.go, samples/storage_csm_powerstore_v2110.yaml, samples/storage_csm_powerstore_v2120.yaml, samples/storage_csm_powerstore_v2130.yaml, tests/config/driverconfig/powerstore/v2.11.0/controller.yaml, tests/config/driverconfig/powerstore/v2.11.0/node.yaml, tests/config/driverconfig/powerstore/v2.12.0/controller.yaml, tests/config/driverconfig/powerstore/v2.12.0/node.yaml, tests/config/driverconfig/powerstore/v2.13.0/controller.yaml, tests/config/driverconfig/powerstore/v2.13.0/node.yaml
Per stakeholder feedback I am moving the default for GOPOWERSTORE_DEBUG to false, consistent with other library debug flags. 
| https://github.com/dell/csm/issues/1762 |
=> Changed GOPOWERSTORE_DEBUG default to false

operatorconfig/driverconfig/powerflex/v2.14.0/node.yaml, samples/storage_csm_powerflex_v2140.yaml
This PR:
- Adds RELEASE_NAME env in driver container for node to facilitate driver configmap update in case of dynamic configmap name used in the driver.
- Adds v2.14.0 sample for powerflex driver.
| https://github.com/dell/csm/issues/1774 |
- Used custom release name to install the driver, driver pods running
- Driver configmap is created with custom release name
- Executed operator E2E for PowerFlex driver scenarios
Logs: [powerflex-driver-e2e.txt](https://github.com/user-attachments/files/19326814/powerflex-driver-e2e.txt)
=> Add RELEASE_NAME env in driver container for node

controllers/csm_controller.go, controllers/csm_controller_test.go, k8s/client.go, k8s/client_test.go, main_test.go, operatorconfig/driverconfig/powerflex/v2.14.0/node.yaml, pkg/drivers/powerflex.go, pkg/drivers/powerflex_test.go
One of the Operator changes for a mounted volume is incompatible with OpenShift environments, because OCP denies write access to the root filesystem. This PR covers changes to identify and remove that mount when on OCP environments. 
| https://github.com/dell/csm/issues/1782 |
Manually tested on OCP 4.16.37.
=> Remove Invalid Mount from OCP - PowerFlex

pkg/drivers/commonconfig.go, tests/e2e/go.mod, tests/e2e/go.sum, tests/e2e/steps/steps_def.go, tests/e2e/testfiles/minimal-testfiles/storage_csm_powermax_secret.yaml
The recent changes of updating all image versions to a tagged version has led to the issue of the minimal manifests attempting to pull unreleased images in the testfiles. After further investigation, the fix appears to be to override the `image` field for all modules/drivers that would be needed.
| https://github.com/dell/csm/issues/1824 |
<details>
```
$ bash run-e2e-test.sh --pmax
/home/falfaroc/git/public/dell/csm-operator/tests/e2e
W0402 13:56:11.436403   95804 test_context.go:541] Unable to find in-cluster config, using default host : https://127.0.0.1:6443
I0402 …
```
=> PowerMax Mount Credentials: Override Minimal Manifest Images

pkg/drivers/powerstore_test.go, tests/e2e/testfiles/minimal-testfiles/scenarios.yaml, tests/e2e/testfiles/minimal-testfiles/storage_csm_powerstore.yaml
Add/Verify HBNFS support for PowerStore with minimal manifest
| https://github.com/dell/csm/issues/1742 |
<details>
```
$ bash run-e2e-test.sh --minimal --hbnfs
/home/falfaroc/git/public/dell/csm-operator/tests/e2e
Running Suite: CSM Operator End-to-End Tests - /home/falfaroc/git/public/dell/csm-operator/tests/e2e
====================================================================================================
Random Seed: 1744038233
Will run 1 of 1 specs
------------------------------
[BeforeSuite]
/home/falfaroc/git/public/dell/csm-operator/tests/e2e/e2e_test.go:98
STEP: …
```
=> PowerStore: Support HBNFS with Minimal

tests/e2e/testfiles/storage_csm_powerflex_downgrade.yaml
The downgrade scenario for pflex e2e was failing due to incorrect downgrade version in the CR. 
| https://github.com/dell/csm/issues/1707 |
Ran Install PowerFlex Driver, Downgrade driver to supported version testcase
=> Fix E2E downgrade scenario failure

controllers/csm_controller.go, controllers/csm_controller_test.go, operatorconfig/moduleconfig/resiliency/v1.13.0/controller-clusterroles.yaml, operatorconfig/moduleconfig/resiliency/v1.13.0/node-clusterroles.yaml, pkg/modules/resiliency.go, pkg/modules/resiliency_test.go
RBAC changes for Resiliency module.
| https://github.com/dell/csm/issues/1751 |
Interface down scenario:
Node reboot scenario:
Driver pods down scenario:
Kubelet down scenario:
Interface down scenario:
Node reboot scenario:
Driver pods down scenario:
Kubelet down scenario:
=> Resiliency RBAC changes

operatorconfig/driverconfig/powerstore/v2.14.0/controller.yaml, operatorconfig/driverconfig/powerstore/v2.14.0/node.yaml
PR to pass the Namespace name as environment variable for Powerstore required for HBNFS.
| https://github.com/dell/csm/issues/1742|
=> Passing namespace name as environment variable

config/samples/storage_v1_csm_powerflex.yaml, config/samples/storage_v1_csm_powermax.yaml, config/samples/storage_v1_csm_powerscale.yaml, operatorconfig/moduleconfig/replication/v1.12.0/controller.yaml, pkg/modules/replication.go, pkg/modules/testdata/cr_powerflex_replica.yaml, pkg/modules/testdata/cr_powermax_replica.yaml, pkg/modules/testdata/cr_powerscale_replica.yaml, samples/storage_csm_powerflex_v2140.yaml, samples/storage_csm_powermax_v2140.yaml, samples/storage_csm_powerscale_v2140.yaml
- Parameterize PVC creation on Target cluster
[ provided an option, to decide whether PVC can be provisioned on Target cluster or not, Instead can simply populate claimref on target PV ]
|https://github.com/dell/csm/issues/1862|
Installed replication controller with both the flags -
=> pvc on target param

.github/scripts/module-version-update.sh, .github/workflows/module-version-update.yaml
It updates modules version to csm-operator -
- Observability
- Resiliency
- Replication
- Authorization v2
- Csireverseproxy
This workflow has support for updating the images to "nightly" and later towards the content lock those "nightly" images can be updated to actual release "tags"
Make sure https://github.com/dell/csm/blob/main/config/csm-versions.yaml is updated with all the latest versions for the release and then module update workflow can be triggered. 
| https://github.com/dell/csm/issues/1490 |
Verified workflow with forked repo of both common-github-action and …
=> module version update nightly/tag

.github/scripts/driver-version-update.sh, .github/workflows/driver-version-update.yaml
Add workflow for nightly and tag update of drivers in csm-operator.
It updates driver version to csm-operator namely-
- Powerscale
- Powerstore
- Powerflex
- Powermax
- Unity
| https://github.com/dell/csm/issues/1490 |
=> Add workflow for nightly and tag update of drivers in csm-operator

bundle/manifests/dell-csm-operator.clusterserviceversion.yaml
The certification CI pipeline compares the count of referenced images with the count of related images and fails the CI checks if they do not match.
| |
=> Add relatedImages needed for certification CI to pass

k8s/client.go, k8s/client_test.go, main.go, main_test.go
k8sClientSet.Discovery().ServerGroupsAndResources() may fail and still contain valid serverGroups, we should therefore handle this. See here: https://github.com/kubernetes/client-go/blob/e7397e54da6d91094f2a8ca6224af45c25682f7f/discovery/discovery_client.go#L130
**Operator will now not immediately fail on the call to k8s to get the service groups. If there is a failure on this call, it will now be logged, so we can see why it failed.**
| |
=> operator does not handle k8sClientSet.Discovery().ServerGroupsAndResources() correctly

controllers/csm_controller.go, controllers/csm_controller_test.go, main.go, tests/shared/clientgoclient/client.go, tests/shared/clientgoclient/fakeDaemonset.go, tests/shared/clientgoclient/fakeDeployment.go, tests/shared/clientgoclient/fakePod.go, tests/shared/clientgoclient/fakeStatefulset.go, tests/shared/clientgoclient/fakecorev1.go
**Current behavior:**
After successful reconciliation, CRs are not requeued. Informers are running in the background, outside of the reconcile function, to receive update events on all deployments, daemonsets, and pods. On update events, the CSM state is calculated and the CSM status is updated to be Failed or Succeeded. This mostly works but it's not reliable because there are timing issues between the update event received and the result of the CSM's calculated state. Sometimes, but frequently enough, the CSM state is Failed even though all driver pods are running after reconciliation and won't be Succeeded until another update event.
**Changes:**
The informers are started after reconciliation and on a per CSM basis. Reconciliation updates the CSM status and after it is successful, the …
=> [bug-1910]: CSM Powermax is intermittently left in a Failed state

deploy/operator.yaml, scripts/uninstall.sh
Added clusterrole with permissions required to install the powerstore driver. 
Added clusterrole with permissions required to cleanup replication controller namespace after uninstallation.
Added a cleanup procedure to the Operator uninistal script to remove clusterrole that was eliminated in this release.
| https://github.com/dell/csm/issues/1986 |
- Successfully installed PowerStore with the fixed Operator
- Successfully executed operator e2e test with '--pstore' (log attached to the defect)
=> ClusterRole with permissions required to install PowerStore

samples/v2.15.0/storage_csm_powerflex_v2150.yaml
Port over the `X_CSI_PROBE_TIMEOUT` to latest PowerFlex sample.
All work has previously been ported over, see: https://github.com/dell/csm-operator/pull/1073
| https://github.com/dell/csm/issues/1956 |
```
time="2025-08-21T19:37:07Z" level=info msg="env variable 'X_CSI_PROBE_TIMEOUT' provided with value 15s"
```
```
$ k get csm -A
NAMESPACE    NAME         CREATIONTIME   CSIDRIVERTYPE   CONFIGVERSION   STATE
vxflexos     vxflexos     3m59s          powerflex       v2.15.0         Succeeded
```
=> Add X_CSI_PROBE_TIMEOUT to PowerFlex sample

scripts/install.sh
Report success/failure on outcome of a step instead of on "checking" operation.
| https://github.com/dell/csm/issues/1896|
```
Installing Dell Container Storage Modules Operator
******
Checking for existing Dell Container Storage Modules Operator installation  
No existing Operator installation found. Proceeding with fresh install.     
******
Environment configuration
Kubernetes Version: 1.33
Openshift: false
******
Checking for kubectl installation                                           Success
Checking for VolumeSnapshotClasses CRD                                      Success …
```
=> Clarify logging in install script

pkg/modules/authorization.go, pkg/modules/authorization_deployment_scaffold.go, pkg/modules/authorization_test.go
Fixed Authorization upgrade from 2.2 to 2.3 where the vault references needs to be removed from the deployment. New storage system credentials and redis configurations are used during upgrade.
| https://github.com/dell/csm/issues/1468 |
```bash
=== RUN   TestVolume
2025/09/05 09:56:46 Starting volume test
Feature: CSM Authorization
As a consumer of the CSM Authorization
I want to test various volume creation scenarios
So that they are known to work
2025/09/05 09:56:47 === Creating Stateless Storage for powerscale === 
2025/09/05 09:56:49 === Completed Stateless Storage === …
```
=> Fixed Authorization Upgrade from 2.2 to 2.3

bundle/manifests/dell-csm-operator.clusterserviceversion.yaml, config/manager/manager.yaml, deploy/operator.yaml
Outdated docker.io tags are replaced with quay.io tags per our policy to use quay.io. This is a follow-up to #1122 that hits some images added as a part of RedHat certification.
| https://github.com/dell/csm/issues/1896 |
Basic Operator E2E test case (standalone PowerMax install) completed with no issues.
=> Replace Docker.io References - nginxinc (2)

pkg/drivers/powerstore.go, pkg/drivers/powerstore_test.go
Fixed multiple entries of `X_CSM_AUTH_ENABLED` env. variable
| https://github.com/dell/csm/issues/1947|
=> Added check for auth env.

tests/e2e/testfiles/scenarios.yaml, tests/e2e/testfiles/storage_csm_unity_extra_arg.yaml
--skip_headers argument is not supported with csi provisioner v5.3.0. Updated tests file with new argument.
|https://github.com/dell/csm/issues/1896 |
Manually tested the new argument working. Operator E2E is passing.
=> Add new argument for tests/e2e - Unity
